// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: branches.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const actualizarSucursal = `-- name: ActualizarSucursal :one
UPDATE branches SET
    name        = coalesce($1::text, name),
    address     = CASE WHEN $2::boolean
                       THEN $3::text ELSE address END,
    lat         = coalesce($4::double precision, lat),
    lng         = coalesce($5::double precision, lng),
    area_km2    = coalesce($6::double precision, area_km2),
    external_id = CASE WHEN $7::boolean
                       THEN $8::text ELSE external_id END,
    origin_configured = CASE
        WHEN $4::double precision IS NOT NULL
          OR $5::double precision IS NOT NULL THEN true
        ELSE origin_configured
    END
WHERE id = $9
  AND ($10::uuid IS NULL OR id = $10::uuid)
RETURNING id, name, address, lat, lng, area_km2, external_id,
          origin_configured, creado_por, created_at, updated_at
`

type ActualizarSucursalParams struct {
	Name            *string     `json:"name"`
	TocarAddress    bool        `json:"tocar_address"`
	Address         *string     `json:"address"`
	Lat             *float64    `json:"lat"`
	Lng             *float64    `json:"lng"`
	AreaKm2         *float64    `json:"area_km2"`
	TocarExternalID bool        `json:"tocar_external_id"`
	ExternalID      *string     `json:"external_id"`
	ID              uuid.UUID   `json:"id"`
	Sucursal        pgtype.UUID `json:"sucursal"`
}

// Tocar lat o lng da el punto de partida por configurado: si alguien se molestó en
// ponerle coordenadas, ya está fijado.
func (q *Queries) ActualizarSucursal(ctx context.Context, arg ActualizarSucursalParams) (Branch, error) {
	row := q.db.QueryRow(ctx, actualizarSucursal,
		arg.Name,
		arg.TocarAddress,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.AreaKm2,
		arg.TocarExternalID,
		arg.ExternalID,
		arg.ID,
		arg.Sucursal,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.AreaKm2,
		&i.ExternalID,
		&i.OriginConfigured,
		&i.CreadoPor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const borrarOrigen = `-- name: BorrarOrigen :execrows
DELETE FROM saved_origins
WHERE id = $1
  AND ($2::uuid IS NULL OR branch_id = $2::uuid)
`

type BorrarOrigenParams struct {
	ID       uuid.UUID   `json:"id"`
	Sucursal pgtype.UUID `json:"sucursal"`
}

func (q *Queries) BorrarOrigen(ctx context.Context, arg BorrarOrigenParams) (int64, error) {
	result, err := q.db.Exec(ctx, borrarOrigen, arg.ID, arg.Sucursal)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const borrarSucursal = `-- name: BorrarSucursal :execrows
DELETE FROM branches
WHERE id = $1
  AND ($2::uuid IS NULL OR id = $2::uuid)
`

type BorrarSucursalParams struct {
	ID       uuid.UUID   `json:"id"`
	Sucursal pgtype.UUID `json:"sucursal"`
}

func (q *Queries) BorrarSucursal(ctx context.Context, arg BorrarSucursalParams) (int64, error) {
	result, err := q.db.Exec(ctx, borrarSucursal, arg.ID, arg.Sucursal)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const buscarSucursalPorCodigo = `-- name: BuscarSucursalPorCodigo :one
SELECT b.id, b.name, b.external_id, b.lat, b.lng, b.area_km2, b.origin_configured
FROM branches b
WHERE b.external_id = $1
`

type BuscarSucursalPorCodigoRow struct {
	ID               uuid.UUID `json:"id"`
	Name             string    `json:"name"`
	ExternalID       *string   `json:"external_id"`
	Lat              float64   `json:"lat"`
	Lng              float64   `json:"lng"`
	AreaKm2          float64   `json:"area_km2"`
	OriginConfigured bool      `json:"origin_configured"`
}

// La sucursal por su código de PEDIDO/Ventra (CAM, HAB, STG...). Es por lo que PEDIDO
// cotiza: manda su código y aquí se busca la nuestra.
func (q *Queries) BuscarSucursalPorCodigo(ctx context.Context, externalID *string) (BuscarSucursalPorCodigoRow, error) {
	row := q.db.QueryRow(ctx, buscarSucursalPorCodigo, externalID)
	var i BuscarSucursalPorCodigoRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExternalID,
		&i.Lat,
		&i.Lng,
		&i.AreaKm2,
		&i.OriginConfigured,
	)
	return i, err
}

const codigosDeSucursalesVisibles = `-- name: CodigosDeSucursalesVisibles :many
SELECT b.id, b.name, b.external_id
FROM branches b
WHERE b.external_id IS NOT NULL
  AND ($1::uuid IS NULL OR b.id = $1::uuid)
ORDER BY b.name ASC
`

type CodigosDeSucursalesVisiblesRow struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	ExternalID *string   `json:"external_id"`
}

// Los códigos a los que esta persona puede llegar. Es lo que filtra la respuesta de
// Accesos en `/api/almacenes`: Accesos devuelve las ocho sucursales y aquí se descartan
// las que no le tocan. Sólo las que TIENEN código: sin él no hay nada que cotejar.
func (q *Queries) CodigosDeSucursalesVisibles(ctx context.Context, sucursal pgtype.UUID) ([]CodigosDeSucursalesVisiblesRow, error) {
	rows, err := q.db.Query(ctx, codigosDeSucursalesVisibles, sucursal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodigosDeSucursalesVisiblesRow
	for rows.Next() {
		var i CodigosDeSucursalesVisiblesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ExternalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contarOrigenesDeSucursal = `-- name: ContarOrigenesDeSucursal :one
SELECT count(*) FROM saved_origins so
WHERE so.branch_id = $1
`

// ¿Tiene ya algún punto de partida? Se pregunta al crear o al corregir una sucursal con
// coordenadas: si no tiene ninguno se le crea el de por defecto. Una sucursal con
// coordenadas y sin origen no puede armar una ruta y no lo dice en ninguna parte.
func (q *Queries) ContarOrigenesDeSucursal(ctx context.Context, sucursalID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, contarOrigenesDeSucursal, sucursalID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const crearOrigen = `-- name: CrearOrigen :one
INSERT INTO saved_origins (name, address, lat, lng, creado_por, branch_id)
VALUES (
    $1, $2, $3, $4,
    $5, $6
)
RETURNING id, name, address, lat, lng, creado_por, branch_id, created_at, updated_at
`

type CrearOrigenParams struct {
	Name      string      `json:"name"`
	Address   string      `json:"address"`
	Lat       float64     `json:"lat"`
	Lng       float64     `json:"lng"`
	CreadoPor *string     `json:"creado_por"`
	BranchID  pgtype.UUID `json:"branch_id"`
}

func (q *Queries) CrearOrigen(ctx context.Context, arg CrearOrigenParams) (SavedOrigin, error) {
	row := q.db.QueryRow(ctx, crearOrigen,
		arg.Name,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.CreadoPor,
		arg.BranchID,
	)
	var i SavedOrigin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.CreadoPor,
		&i.BranchID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const crearSucursal = `-- name: CrearSucursal :one
INSERT INTO branches (name, address, lat, lng, area_km2, external_id, origin_configured, creado_por)
VALUES (
    $1, $2, $3, $4,
    $5, $6, true, $7
)
RETURNING id, name, address, lat, lng, area_km2, external_id,
          origin_configured, creado_por, created_at, updated_at
`

type CrearSucursalParams struct {
	Name       string  `json:"name"`
	Address    *string `json:"address"`
	Lat        float64 `json:"lat"`
	Lng        float64 `json:"lng"`
	AreaKm2    float64 `json:"area_km2"`
	ExternalID *string `json:"external_id"`
	CreadoPor  *string `json:"creado_por"`
}

// `origin_configured` nace en true al darla de alta con coordenadas: el alta ya fija el
// punto de partida. Mientras sea false, el cálculo de domicilios NO corre para esa
// sucursal, y eso es deliberado — medir desde un punto que no es el almacén da un precio
// que parece bueno y no lo es.
func (q *Queries) CrearSucursal(ctx context.Context, arg CrearSucursalParams) (Branch, error) {
	row := q.db.QueryRow(ctx, crearSucursal,
		arg.Name,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.AreaKm2,
		arg.ExternalID,
		arg.CreadoPor,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.AreaKm2,
		&i.ExternalID,
		&i.OriginConfigured,
		&i.CreadoPor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listarOrigenes = `-- name: ListarOrigenes :many

SELECT
    so.id, so.name, so.address, so.lat, so.lng, so.creado_por, so.branch_id,
    so.created_at, so.updated_at,
    b.name AS sucursal_nombre
FROM saved_origins so
LEFT JOIN branches b ON b.id = so.branch_id
WHERE ($1::uuid IS NULL OR so.branch_id = $1::uuid)
ORDER BY so.created_at DESC
`

type ListarOrigenesRow struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	Address        string             `json:"address"`
	Lat            float64            `json:"lat"`
	Lng            float64            `json:"lng"`
	CreadoPor      *string            `json:"creado_por"`
	BranchID       pgtype.UUID        `json:"branch_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	SucursalNombre *string            `json:"sucursal_nombre"`
}

// ---------------------------------------------------------------------------
// Puntos de partida guardados  (/api/origins)
// ---------------------------------------------------------------------------
// Los orígenes desde los que se puede armar una ruta.
//
// Con alcance se ven los de la sucursal; sin alcance, o todos o los de la que se pida.
// Los orígenes SIN sucursal no se cuelan en el alcance de nadie: un punto de partida
// suelto en la lista de Holguín es una ruta que empieza a 800 km de donde debía.
func (q *Queries) ListarOrigenes(ctx context.Context, sucursal pgtype.UUID) ([]ListarOrigenesRow, error) {
	rows, err := q.db.Query(ctx, listarOrigenes, sucursal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarOrigenesRow
	for rows.Next() {
		var i ListarOrigenesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.CreadoPor,
			&i.BranchID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SucursalNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarSucursales = `-- name: ListarSucursales :many


SELECT
    b.id, b.name, b.address, b.lat, b.lng, b.area_km2, b.external_id,
    b.origin_configured, b.creado_por, b.created_at, b.updated_at,
    (SELECT count(*) FROM saved_origins so WHERE so.branch_id = b.id) AS origenes
FROM branches b
WHERE ($1::uuid IS NULL
       OR b.id = $1::uuid)
ORDER BY b.created_at DESC
`

type ListarSucursalesRow struct {
	ID               uuid.UUID          `json:"id"`
	Name             string             `json:"name"`
	Address          *string            `json:"address"`
	Lat              float64            `json:"lat"`
	Lng              float64            `json:"lng"`
	AreaKm2          float64            `json:"area_km2"`
	ExternalID       *string            `json:"external_id"`
	OriginConfigured bool               `json:"origin_configured"`
	CreadoPor        *string            `json:"creado_por"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Origenes         int64              `json:"origenes"`
}

// Sucursales y puntos de partida guardados.
//
// OJO, AQUÍ EL ALCANCE ES DISTINTO Y NO ES UN DESCUIDO.
//
// En la LISTA de sucursales no se pregunta «qué estoy mirando ahora» sino «a cuáles puedo
// llegar», que sólo depende de la persona y no de la que tenga elegida arriba. Si se
// acotara por la elegida, elegir una devolvería una sola, el selector se volvería una
// etiqueta fija y no habría forma de cambiar a otra: la elección se comería la lista con
// la que se elige. Por eso el parámetro se llama `sucursal_de_la_persona` y no `sucursal`.
//
// Y OTRA COSA QUE TAMPOCO ES UN DESCUIDO: si el id que llega no existe, el llamante pasa
// NULL y se ven todas. Filtrar por un id inexistente NO da error: da CERO. Cero pedidos,
// cero clientes, cero rutas y hasta cero sucursales —con lo que desaparece el selector con
// el que se podría arreglar—, todo con 200 y sin una traza. El token del login único dura
// siete días y lleva dentro la sucursal que la persona tenía al entrar, y las sucursales
// se recrearon en algún momento: pasa de verdad, y se vio en producción.
// ---------------------------------------------------------------------------
// Sucursales
// ---------------------------------------------------------------------------
func (q *Queries) ListarSucursales(ctx context.Context, sucursalDeLaPersona pgtype.UUID) ([]ListarSucursalesRow, error) {
	rows, err := q.db.Query(ctx, listarSucursales, sucursalDeLaPersona)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarSucursalesRow
	for rows.Next() {
		var i ListarSucursalesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.AreaKm2,
			&i.ExternalID,
			&i.OriginConfigured,
			&i.CreadoPor,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Origenes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerSucursal = `-- name: ObtenerSucursal :one
SELECT
    b.id, b.name, b.address, b.lat, b.lng, b.area_km2, b.external_id,
    b.origin_configured, b.creado_por, b.created_at, b.updated_at
FROM branches b
WHERE b.id = $1
  AND ($2::uuid IS NULL OR b.id = $2::uuid)
`

type ObtenerSucursalParams struct {
	ID       uuid.UUID   `json:"id"`
	Sucursal pgtype.UUID `json:"sucursal"`
}

func (q *Queries) ObtenerSucursal(ctx context.Context, arg ObtenerSucursalParams) (Branch, error) {
	row := q.db.QueryRow(ctx, obtenerSucursal, arg.ID, arg.Sucursal)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.AreaKm2,
		&i.ExternalID,
		&i.OriginConfigured,
		&i.CreadoPor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolverSucursal = `-- name: ResolverSucursal :one
SELECT b.id, b.name, b.external_id, b.lat, b.lng, b.origin_configured
FROM branches b
WHERE b.id = $1
`

type ResolverSucursalRow struct {
	ID               uuid.UUID `json:"id"`
	Name             string    `json:"name"`
	ExternalID       *string   `json:"external_id"`
	Lat              float64   `json:"lat"`
	Lng              float64   `json:"lng"`
	OriginConfigured bool      `json:"origin_configured"`
}

// ¿Existe esta sucursal? Es la comprobación de `resolveScope`, y el único sitio donde se
// resuelve el alcance. Devuelve también el `external_id` porque clientes y catálogo se
// acotan por CÓDIGO, no por uuid, y sin esa traducción el filtro no se puede armar.
func (q *Queries) ResolverSucursal(ctx context.Context, id uuid.UUID) (ResolverSucursalRow, error) {
	row := q.db.QueryRow(ctx, resolverSucursal, id)
	var i ResolverSucursalRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExternalID,
		&i.Lat,
		&i.Lng,
		&i.OriginConfigured,
	)
	return i, err
}
