// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const actualizarClienteDelEspejo = `-- name: ActualizarClienteDelEspejo :one
UPDATE customers SET
    name            = $1,
    phone           = $2,
    address         = $3,
    municipio       = $4,
    zona            = $5,
    codigo          = $6,
    vendedor        = $7,
    lat             = $8,
    lng             = $9,
    sucursal_codigo = $10,
    synced_at       = now()
WHERE id = $11
RETURNING id, source, external_id, name, sucursal_codigo, synced_at
`

type ActualizarClienteDelEspejoParams struct {
	Name           string    `json:"name"`
	Phone          *string   `json:"phone"`
	Address        *string   `json:"address"`
	Municipio      *string   `json:"municipio"`
	Zona           *string   `json:"zona"`
	Codigo         *string   `json:"codigo"`
	Vendedor       *string   `json:"vendedor"`
	Lat            float64   `json:"lat"`
	Lng            float64   `json:"lng"`
	SucursalCodigo *string   `json:"sucursal_codigo"`
	ID             uuid.UUID `json:"id"`
}

type ActualizarClienteDelEspejoRow struct {
	ID             uuid.UUID          `json:"id"`
	Source         *Procedencia       `json:"source"`
	ExternalID     *string            `json:"external_id"`
	Name           string             `json:"name"`
	SucursalCodigo *string            `json:"sucursal_codigo"`
	SyncedAt       pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) ActualizarClienteDelEspejo(ctx context.Context, arg ActualizarClienteDelEspejoParams) (ActualizarClienteDelEspejoRow, error) {
	row := q.db.QueryRow(ctx, actualizarClienteDelEspejo,
		arg.Name,
		arg.Phone,
		arg.Address,
		arg.Municipio,
		arg.Zona,
		arg.Codigo,
		arg.Vendedor,
		arg.Lat,
		arg.Lng,
		arg.SucursalCodigo,
		arg.ID,
	)
	var i ActualizarClienteDelEspejoRow
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Name,
		&i.SucursalCodigo,
		&i.SyncedAt,
	)
	return i, err
}

const buscarClienteDelEspejo = `-- name: BuscarClienteDelEspejo :one
SELECT c.id, c.sucursal_codigo, c.synced_at
FROM customers c
WHERE c.source = $1::procedencia
  AND c.external_id = $2::text
`

type BuscarClienteDelEspejoParams struct {
	Source     Procedencia `json:"source"`
	ExternalID string      `json:"external_id"`
}

type BuscarClienteDelEspejoRow struct {
	ID             uuid.UUID          `json:"id"`
	SucursalCodigo *string            `json:"sucursal_codigo"`
	SyncedAt       pgtype.Timestamptz `json:"synced_at"`
}

// Idempotencia del espejo: `source` + `external_id` es lo que reconoce a un cliente entre
// pasadas. Sin alcance — el espejo entra con clave de servicio y trae las ocho sucursales.
//
// Como en pedidos: `customers_origen_idx` NO es único, así que no hay `ON CONFLICT` que
// valga. Se busca y se escribe, que es lo que hace el contrato.
func (q *Queries) BuscarClienteDelEspejo(ctx context.Context, arg BuscarClienteDelEspejoParams) (BuscarClienteDelEspejoRow, error) {
	row := q.db.QueryRow(ctx, buscarClienteDelEspejo, arg.Source, arg.ExternalID)
	var i BuscarClienteDelEspejoRow
	err := row.Scan(&i.ID, &i.SucursalCodigo, &i.SyncedAt)
	return i, err
}

const contarClientes = `-- name: ContarClientes :one
SELECT count(*)
FROM customers c
WHERE
    ($1::text IS NULL
     OR c.sucursal_codigo = $1::text
     OR c.sucursal_codigo IS NULL)
    AND ($2::text IS NULL
         OR c.sucursal_codigo = $2::text)
    AND (
        $3::text IS NULL
        OR c.name      ILIKE '%' || $3::text || '%'
        OR c.address   ILIKE '%' || $3::text || '%'
        OR c.municipio ILIKE '%' || $3::text || '%'
        OR c.zona      ILIKE '%' || $3::text || '%'
        OR c.phone     ILIKE '%' || $3::text || '%'
        OR c.codigo    ILIKE '%' || $3::text || '%'
        OR c.vendedor  ILIKE '%' || $3::text || '%'
    )
    AND ($4::text IS NULL OR c.municipio = $4::text)
    AND ($5::text      IS NULL OR c.zona      = $5::text)
    AND ($6::text  IS NULL OR c.vendedor  = $6::text)
    AND (
        $7::text IS NULL
        OR ($7::text = 'pedido' AND c.source = 'pedido')
        OR ($7::text = 'manual' AND c.source IS NULL)
    )
    AND (
        $8::boolean IS NULL
        OR ($8::boolean AND c.phone IS NOT NULL AND c.phone <> '')
        OR (NOT $8::boolean AND (c.phone IS NULL OR c.phone = ''))
    )
    AND ($9::double precision IS NULL OR c.lat >= $9::double precision)
    AND ($10::double precision IS NULL OR c.lat <= $10::double precision)
    AND ($11::double precision IS NULL OR c.lng >= $11::double precision)
    AND ($12::double precision IS NULL OR c.lng <= $12::double precision)
`

type ContarClientesParams struct {
	SucursalDelAlcance *string  `json:"sucursal_del_alcance"`
	SucursalCodigo     *string  `json:"sucursal_codigo"`
	Q                  *string  `json:"q"`
	Municipio          *string  `json:"municipio"`
	Zona               *string  `json:"zona"`
	Vendedor           *string  `json:"vendedor"`
	Origen             *string  `json:"origen"`
	ConTelefono        *bool    `json:"con_telefono"`
	LatMin             *float64 `json:"lat_min"`
	LatMax             *float64 `json:"lat_max"`
	LngMin             *float64 `json:"lng_min"`
	LngMax             *float64 `json:"lng_max"`
}

// El total, con el MISMO where. Es el `total` de la respuesta: se cuenta antes del filtro
// de distancia exacto, igual que en el contrato, y por eso puede ser mayor que `count`.
func (q *Queries) ContarClientes(ctx context.Context, arg ContarClientesParams) (int64, error) {
	row := q.db.QueryRow(ctx, contarClientes,
		arg.SucursalDelAlcance,
		arg.SucursalCodigo,
		arg.Q,
		arg.Municipio,
		arg.Zona,
		arg.Vendedor,
		arg.Origen,
		arg.ConTelefono,
		arg.LatMin,
		arg.LatMax,
		arg.LngMin,
		arg.LngMax,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const contarClientesSinTelefono = `-- name: ContarClientesSinTelefono :one
SELECT count(*)
FROM customers c
WHERE (c.phone IS NULL OR c.phone = '')
  AND ($1::text IS NULL
       OR c.sucursal_codigo = $1::text
       OR c.sucursal_codigo IS NULL)
`

// Cuántos no tienen a quién llamar. Es un aviso de calidad del espejo, no un filtro más:
// un cliente sin teléfono es una entrega que, si falla, no se puede avisar.
func (q *Queries) ContarClientesSinTelefono(ctx context.Context, sucursalDelAlcance *string) (int64, error) {
	row := q.db.QueryRow(ctx, contarClientesSinTelefono, sucursalDelAlcance)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const crearClienteDelEspejo = `-- name: CrearClienteDelEspejo :one
INSERT INTO customers (
    source, external_id, name, phone, address, municipio, zona, codigo,
    vendedor, lat, lng, sucursal_codigo, synced_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11,
    $12, now()
)
RETURNING id, source, external_id, name, sucursal_codigo, synced_at
`

type CrearClienteDelEspejoParams struct {
	Source         *Procedencia `json:"source"`
	ExternalID     *string      `json:"external_id"`
	Name           string       `json:"name"`
	Phone          *string      `json:"phone"`
	Address        *string      `json:"address"`
	Municipio      *string      `json:"municipio"`
	Zona           *string      `json:"zona"`
	Codigo         *string      `json:"codigo"`
	Vendedor       *string      `json:"vendedor"`
	Lat            float64      `json:"lat"`
	Lng            float64      `json:"lng"`
	SucursalCodigo *string      `json:"sucursal_codigo"`
}

type CrearClienteDelEspejoRow struct {
	ID             uuid.UUID          `json:"id"`
	Source         *Procedencia       `json:"source"`
	ExternalID     *string            `json:"external_id"`
	Name           string             `json:"name"`
	SucursalCodigo *string            `json:"sucursal_codigo"`
	SyncedAt       pgtype.Timestamptz `json:"synced_at"`
}

// `synced_at` es «cuándo lo trajo el origen» y NO es `updated_at`, que lo mueve el trigger
// al tocar la fila. Confundirlas rompe el espejo: la segunda cambia aunque el dato de
// Ventra sea de hace tres días porque la VPN lleva caída desde el lunes.
func (q *Queries) CrearClienteDelEspejo(ctx context.Context, arg CrearClienteDelEspejoParams) (CrearClienteDelEspejoRow, error) {
	row := q.db.QueryRow(ctx, crearClienteDelEspejo,
		arg.Source,
		arg.ExternalID,
		arg.Name,
		arg.Phone,
		arg.Address,
		arg.Municipio,
		arg.Zona,
		arg.Codigo,
		arg.Vendedor,
		arg.Lat,
		arg.Lng,
		arg.SucursalCodigo,
	)
	var i CrearClienteDelEspejoRow
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Name,
		&i.SucursalCodigo,
		&i.SyncedAt,
	)
	return i, err
}

const facetasClientesMunicipios = `-- name: FacetasClientesMunicipios :many

SELECT c.municipio AS valor, count(*) AS clientes
FROM customers c
WHERE c.municipio IS NOT NULL
  AND ($1::text IS NULL
       OR c.sucursal_codigo = $1::text
       OR c.sucursal_codigo IS NULL)
GROUP BY c.municipio
ORDER BY c.municipio ASC
`

type FacetasClientesMunicipiosRow struct {
	Valor    *string `json:"valor"`
	Clientes int64   `json:"clientes"`
}

// ---------------------------------------------------------------------------
// Facetas de clientes
// ---------------------------------------------------------------------------
//
// Se calculan sobre TODO el alcance y SIN los filtros de búsqueda, a propósito: los
// desplegables tienen que seguir ofreciendo a dónde ir después de filtrar. Si se
// recalcularan con la búsqueda puesta, cada filtro dejaría los demás con una sola opción
// —la ya elegida— y no habría forma de cambiar de idea sin borrarlo todo.
func (q *Queries) FacetasClientesMunicipios(ctx context.Context, sucursalDelAlcance *string) ([]FacetasClientesMunicipiosRow, error) {
	rows, err := q.db.Query(ctx, facetasClientesMunicipios, sucursalDelAlcance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FacetasClientesMunicipiosRow
	for rows.Next() {
		var i FacetasClientesMunicipiosRow
		if err := rows.Scan(&i.Valor, &i.Clientes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const facetasClientesSucursales = `-- name: FacetasClientesSucursales :many
SELECT c.sucursal_codigo AS valor, count(*) AS clientes
FROM customers c
WHERE c.sucursal_codigo IS NOT NULL
  AND ($1::text IS NULL
       OR c.sucursal_codigo = $1::text
       OR c.sucursal_codigo IS NULL)
GROUP BY c.sucursal_codigo
ORDER BY c.sucursal_codigo ASC
`

type FacetasClientesSucursalesRow struct {
	Valor    *string `json:"valor"`
	Clientes int64   `json:"clientes"`
}

func (q *Queries) FacetasClientesSucursales(ctx context.Context, sucursalDelAlcance *string) ([]FacetasClientesSucursalesRow, error) {
	rows, err := q.db.Query(ctx, facetasClientesSucursales, sucursalDelAlcance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FacetasClientesSucursalesRow
	for rows.Next() {
		var i FacetasClientesSucursalesRow
		if err := rows.Scan(&i.Valor, &i.Clientes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const facetasClientesVendedores = `-- name: FacetasClientesVendedores :many
SELECT c.vendedor AS valor, count(*) AS clientes
FROM customers c
WHERE c.vendedor IS NOT NULL
  AND ($1::text IS NULL
       OR c.sucursal_codigo = $1::text
       OR c.sucursal_codigo IS NULL)
GROUP BY c.vendedor
ORDER BY c.vendedor ASC
`

type FacetasClientesVendedoresRow struct {
	Valor    *string `json:"valor"`
	Clientes int64   `json:"clientes"`
}

func (q *Queries) FacetasClientesVendedores(ctx context.Context, sucursalDelAlcance *string) ([]FacetasClientesVendedoresRow, error) {
	rows, err := q.db.Query(ctx, facetasClientesVendedores, sucursalDelAlcance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FacetasClientesVendedoresRow
	for rows.Next() {
		var i FacetasClientesVendedoresRow
		if err := rows.Scan(&i.Valor, &i.Clientes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const facetasClientesZonas = `-- name: FacetasClientesZonas :many
SELECT c.zona AS valor, count(*) AS clientes
FROM customers c
WHERE c.zona IS NOT NULL
  AND ($1::text IS NULL
       OR c.sucursal_codigo = $1::text
       OR c.sucursal_codigo IS NULL)
GROUP BY c.zona
ORDER BY c.zona ASC
`

type FacetasClientesZonasRow struct {
	Valor    *string `json:"valor"`
	Clientes int64   `json:"clientes"`
}

func (q *Queries) FacetasClientesZonas(ctx context.Context, sucursalDelAlcance *string) ([]FacetasClientesZonasRow, error) {
	rows, err := q.db.Query(ctx, facetasClientesZonas, sucursalDelAlcance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FacetasClientesZonasRow
	for rows.Next() {
		var i FacetasClientesZonasRow
		if err := rows.Scan(&i.Valor, &i.Clientes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarClientes = `-- name: ListarClientes :many


SELECT
    c.id, c.source, c.external_id, c.name, c.phone, c.address, c.municipio,
    c.zona, c.lat, c.lng, c.sucursal_codigo, c.codigo, c.vendedor, c.synced_at
FROM customers c
WHERE
    -- alcance por sucursal, traducido a código; los manuales (sin código) se ven siempre
    ($1::text IS NULL
     OR c.sucursal_codigo = $1::text
     OR c.sucursal_codigo IS NULL)
    -- filtro de la query: estrecha dentro del alcance, nunca lo amplía
    AND ($2::text IS NULL
         OR c.sucursal_codigo = $2::text)
    AND (
        $3::text IS NULL
        OR c.name      ILIKE '%' || $3::text || '%'
        OR c.address   ILIKE '%' || $3::text || '%'
        OR c.municipio ILIKE '%' || $3::text || '%'
        OR c.zona      ILIKE '%' || $3::text || '%'
        OR c.phone     ILIKE '%' || $3::text || '%'
        OR c.codigo    ILIKE '%' || $3::text || '%'
        OR c.vendedor  ILIKE '%' || $3::text || '%'
    )
    AND ($4::text IS NULL OR c.municipio = $4::text)
    AND ($5::text      IS NULL OR c.zona      = $5::text)
    AND ($6::text  IS NULL OR c.vendedor  = $6::text)
    -- ` + "`" + `origen` + "`" + `: 'pedido' = vino del espejo; 'manual' = alta a mano, que es ` + "`" + `source` + "`" + ` NULL.
    -- NULL no se compara con ` + "`" + `=` + "`" + `, así que la rama del manual se nombra a mano o no sale.
    AND (
        $7::text IS NULL
        OR ($7::text = 'pedido' AND c.source = 'pedido')
        OR ($7::text = 'manual' AND c.source IS NULL)
    )
    -- «Sin teléfono» incluye la cadena vacía: un campo en blanco no es un teléfono.
    AND (
        $8::boolean IS NULL
        OR ($8::boolean AND c.phone IS NOT NULL AND c.phone <> '')
        OR (NOT $8::boolean AND (c.phone IS NULL OR c.phone = ''))
    )
    -- caja previa del filtro por kilómetros (el haversine exacto va después, en Go)
    AND ($9::double precision IS NULL OR c.lat >= $9::double precision)
    AND ($10::double precision IS NULL OR c.lat <= $10::double precision)
    AND ($11::double precision IS NULL OR c.lng >= $11::double precision)
    AND ($12::double precision IS NULL OR c.lng <= $12::double precision)
ORDER BY c.name ASC
LIMIT $14 OFFSET $13
`

type ListarClientesParams struct {
	SucursalDelAlcance *string  `json:"sucursal_del_alcance"`
	SucursalCodigo     *string  `json:"sucursal_codigo"`
	Q                  *string  `json:"q"`
	Municipio          *string  `json:"municipio"`
	Zona               *string  `json:"zona"`
	Vendedor           *string  `json:"vendedor"`
	Origen             *string  `json:"origen"`
	ConTelefono        *bool    `json:"con_telefono"`
	LatMin             *float64 `json:"lat_min"`
	LatMax             *float64 `json:"lat_max"`
	LngMin             *float64 `json:"lng_min"`
	LngMax             *float64 `json:"lng_max"`
	Desplazamiento     int32    `json:"desplazamiento"`
	Limite             int32    `json:"limite"`
}

type ListarClientesRow struct {
	ID             uuid.UUID          `json:"id"`
	Source         *Procedencia       `json:"source"`
	ExternalID     *string            `json:"external_id"`
	Name           string             `json:"name"`
	Phone          *string            `json:"phone"`
	Address        *string            `json:"address"`
	Municipio      *string            `json:"municipio"`
	Zona           *string            `json:"zona"`
	Lat            float64            `json:"lat"`
	Lng            float64            `json:"lng"`
	SucursalCodigo *string            `json:"sucursal_codigo"`
	Codigo         *string            `json:"codigo"`
	Vendedor       *string            `json:"vendedor"`
	SyncedAt       pgtype.Timestamptz `json:"synced_at"`
}

// Clientes: espejo de Ventra vía PEDIDO. Sólo los GEOLOCALIZADOS — sin coordenadas no se
// cotiza y no hay parada que visitar.
//
// EL ALCANCE AQUÍ VA POR CÓDIGO, NO POR `branch_id`.
//
// `customers` no tiene `branch_id`: tiene `sucursal_codigo`, que es el código de Ventra
// (CAM, HAB, STG...). Quien llama traduce su sucursal a código —`branches.external_id`—
// y lo pasa en `sucursal_del_alcance`. El filtro deja pasar además los clientes SIN
// código: son los que no vinieron de ninguna sucursal concreta, y esconderlos haría
// desaparecer clientes que sí se atienden, sin decir nada.
//
// Si la sucursal del alcance NO tiene `external_id`, el llamante debe pasar NULL aquí:
// pasar el uuid de la sucursal como si fuera un código no da error, da CERO CLIENTES.
// ---------------------------------------------------------------------------
// La lista  (GET /api/customers)
// ---------------------------------------------------------------------------
// La página de clientes con todos sus filtros.
//
// El filtro por distancia va en DOS pasos y sólo el primero está aquí: la CAJA
// (`lat`/`lng` entre unos grados) es lo único que un índice puede resolver. La distancia
// exacta se calcula después, sólo sobre las 50 filas de la página. Meter el haversine en
// el WHERE obliga a recorrer los siete mil clientes fila a fila en cada búsqueda.
// Los grados vienen ya calculados de Go: `km/111` en latitud y `km/(111*cos(lat))` en
// longitud, que es donde el meridiano se estrecha.
func (q *Queries) ListarClientes(ctx context.Context, arg ListarClientesParams) ([]ListarClientesRow, error) {
	rows, err := q.db.Query(ctx, listarClientes,
		arg.SucursalDelAlcance,
		arg.SucursalCodigo,
		arg.Q,
		arg.Municipio,
		arg.Zona,
		arg.Vendedor,
		arg.Origen,
		arg.ConTelefono,
		arg.LatMin,
		arg.LatMax,
		arg.LngMin,
		arg.LngMax,
		arg.Desplazamiento,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarClientesRow
	for rows.Next() {
		var i ListarClientesRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Name,
			&i.Phone,
			&i.Address,
			&i.Municipio,
			&i.Zona,
			&i.Lat,
			&i.Lng,
			&i.SucursalCodigo,
			&i.Codigo,
			&i.Vendedor,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerCliente = `-- name: ObtenerCliente :one

SELECT
    c.id, c.source, c.external_id, c.name, c.phone, c.address, c.municipio,
    c.zona, c.codigo, c.vendedor, c.lat, c.lng, c.sucursal_codigo,
    c.synced_at, c.created_at, c.updated_at
FROM customers c
WHERE c.id = $1
  AND ($2::text IS NULL
       OR c.sucursal_codigo = $2::text
       OR c.sucursal_codigo IS NULL)
`

type ObtenerClienteParams struct {
	ID                 uuid.UUID `json:"id"`
	SucursalDelAlcance *string   `json:"sucursal_del_alcance"`
}

// ---------------------------------------------------------------------------
// Un cliente suelto y el espejo
// ---------------------------------------------------------------------------
func (q *Queries) ObtenerCliente(ctx context.Context, arg ObtenerClienteParams) (Customer, error) {
	row := q.db.QueryRow(ctx, obtenerCliente, arg.ID, arg.SucursalDelAlcance)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.Municipio,
		&i.Zona,
		&i.Codigo,
		&i.Vendedor,
		&i.Lat,
		&i.Lng,
		&i.SucursalCodigo,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
