// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const actualizarPedido = `-- name: ActualizarPedido :one

UPDATE orders SET
    operation_number = coalesce($1::text, operation_number),
    customer_name    = coalesce($2::text, customer_name),
    address          = coalesce($3::text, address),
    end_address      = coalesce($4::text, end_address),
    end_lat          = coalesce($5::double precision, end_lat),
    end_lng          = coalesce($6::double precision, end_lng),
    lat              = coalesce($7::double precision, lat),
    lng              = coalesce($8::double precision, lng),
    weight           = coalesce($9::double precision, weight),
    notes            = coalesce($10::text, notes),
    status           = coalesce($11::order_status, status),
    trip_leg         = coalesce($12::trip_leg, trip_leg),
    price            = coalesce($13::double precision, price),
    stop_order       = coalesce($14::integer, stop_order),
    -- ` + "`" + `route_id` + "`" + ` va con interruptor y no con coalesce porque ponerlo a NULL es la mitad
    -- de su utilidad: es como se baja un pedido de un camión a mano. Y NO toca
    -- ` + "`" + `ultima_ruta_id` + "`" + `, igual que en delivery: en qué ruta viajó no se reescribe desde
    -- una corrección suelta. Meter o sacar pedidos de una ruta de verdad es cosa de
    -- /api/routes; esto es el parche de una equivocación.
    route_id         = CASE WHEN $15::boolean
                            THEN $16::uuid ELSE route_id END,
    delivered_at     = CASE
        WHEN $11::order_status = 'delivered' THEN now()
        ELSE delivered_at
    END
WHERE id = $17
  AND ($18::uuid IS NULL OR branch_id = $18::uuid)
RETURNING id, operation_number, customer_name, address, end_address, end_lat,
          end_lng, lat, lng, weight, status, trip_leg, notes, route_id,
          ultima_ruta_id, price, segment_km, stop_order, delivered_at,
          branch_id, updated_at
`

type ActualizarPedidoParams struct {
	OperationNumber *string      `json:"operation_number"`
	CustomerName    *string      `json:"customer_name"`
	Address         *string      `json:"address"`
	EndAddress      *string      `json:"end_address"`
	EndLat          *float64     `json:"end_lat"`
	EndLng          *float64     `json:"end_lng"`
	Lat             *float64     `json:"lat"`
	Lng             *float64     `json:"lng"`
	Weight          *float64     `json:"weight"`
	Notes           *string      `json:"notes"`
	Status          *OrderStatus `json:"status"`
	TripLeg         *TripLeg     `json:"trip_leg"`
	Price           *float64     `json:"price"`
	StopOrder       *int32       `json:"stop_order"`
	TocarRouteID    bool         `json:"tocar_route_id"`
	RouteID         pgtype.UUID  `json:"route_id"`
	ID              uuid.UUID    `json:"id"`
	Sucursal        pgtype.UUID  `json:"sucursal"`
}

type ActualizarPedidoRow struct {
	ID              uuid.UUID          `json:"id"`
	OperationNumber *string            `json:"operation_number"`
	CustomerName    string             `json:"customer_name"`
	Address         string             `json:"address"`
	EndAddress      *string            `json:"end_address"`
	EndLat          *float64           `json:"end_lat"`
	EndLng          *float64           `json:"end_lng"`
	Lat             *float64           `json:"lat"`
	Lng             *float64           `json:"lng"`
	Weight          float64            `json:"weight"`
	Status          OrderStatus        `json:"status"`
	TripLeg         TripLeg            `json:"trip_leg"`
	Notes           *string            `json:"notes"`
	RouteID         pgtype.UUID        `json:"route_id"`
	UltimaRutaID    pgtype.UUID        `json:"ultima_ruta_id"`
	Price           *float64           `json:"price"`
	SegmentKm       *float64           `json:"segment_km"`
	StopOrder       *int32             `json:"stop_order"`
	DeliveredAt     pgtype.Timestamptz `json:"delivered_at"`
	BranchID        pgtype.UUID        `json:"branch_id"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// ---------------------------------------------------------------------------
// Escrituras del catálogo
// ---------------------------------------------------------------------------
// PATCH de un pedido a mano. `coalesce` deja pasar sólo lo que viene: lo que no se manda
// no se pisa con NULL. `delivered_at` se pone solo al marcar `delivered` — no se le pide
// al cliente que lo mande, que es como acaban dos pedidos con la misma hora de entrega.
func (q *Queries) ActualizarPedido(ctx context.Context, arg ActualizarPedidoParams) (ActualizarPedidoRow, error) {
	row := q.db.QueryRow(ctx, actualizarPedido,
		arg.OperationNumber,
		arg.CustomerName,
		arg.Address,
		arg.EndAddress,
		arg.EndLat,
		arg.EndLng,
		arg.Lat,
		arg.Lng,
		arg.Weight,
		arg.Notes,
		arg.Status,
		arg.TripLeg,
		arg.Price,
		arg.StopOrder,
		arg.TocarRouteID,
		arg.RouteID,
		arg.ID,
		arg.Sucursal,
	)
	var i ActualizarPedidoRow
	err := row.Scan(
		&i.ID,
		&i.OperationNumber,
		&i.CustomerName,
		&i.Address,
		&i.EndAddress,
		&i.EndLat,
		&i.EndLng,
		&i.Lat,
		&i.Lng,
		&i.Weight,
		&i.Status,
		&i.TripLeg,
		&i.Notes,
		&i.RouteID,
		&i.UltimaRutaID,
		&i.Price,
		&i.SegmentKm,
		&i.StopOrder,
		&i.DeliveredAt,
		&i.BranchID,
		&i.UpdatedAt,
	)
	return i, err
}

const actualizarPesoDePedido = `-- name: ActualizarPesoDePedido :exec
UPDATE orders SET weight = $1::double precision
WHERE id = $2
`

type ActualizarPesoDePedidoParams struct {
	Weight float64   `json:"weight"`
	ID     uuid.UUID `json:"id"`
}

// Recalcular el peso desde el catálogo (POST /api/orders/recompute-weights). Va sin
// alcance a propósito: es una faena de servicio sobre todo el espejo, con clave de API.
func (q *Queries) ActualizarPesoDePedido(ctx context.Context, arg ActualizarPesoDePedidoParams) error {
	_, err := q.db.Exec(ctx, actualizarPesoDePedido, arg.Weight, arg.ID)
	return err
}

const borrarPedido = `-- name: BorrarPedido :execrows
DELETE FROM orders
WHERE id = $1
  AND ($2::uuid IS NULL OR branch_id = $2::uuid)
`

type BorrarPedidoParams struct {
	ID       uuid.UUID   `json:"id"`
	Sucursal pgtype.UUID `json:"sucursal"`
}

// :execrows y no :exec: cero filas es «no existe O no es de tu sucursal», que es el 404.
// Con :exec no hay forma de distinguirlo de un borrado hecho.
func (q *Queries) BorrarPedido(ctx context.Context, arg BorrarPedidoParams) (int64, error) {
	result, err := q.db.Exec(ctx, borrarPedido, arg.ID, arg.Sucursal)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const borrarRenglonesDePedido = `-- name: BorrarRenglonesDePedido :exec
DELETE FROM order_items WHERE order_id = $1
`

// Los renglones se reescriben enteros en cada pasada del espejo: PEDIDO puede haber
// quitado una línea, y un UPDATE línea a línea dejaría la vieja colgada. Se borran y se
// vuelven a poner dentro de la MISMA transacción que el upsert de arriba.
func (q *Queries) BorrarRenglonesDePedido(ctx context.Context, pedidoID uuid.UUID) error {
	_, err := q.db.Exec(ctx, borrarRenglonesDePedido, pedidoID)
	return err
}

const contarPedidos = `-- name: ContarPedidos :one
SELECT count(*)
FROM orders o
LEFT JOIN routes r ON r.id = o.route_id
WHERE
    ($1::uuid  IS NULL OR o.branch_id = $1::uuid)
    AND ($2::uuid IS NULL OR o.branch_id = $2::uuid)
    AND (
        $3::text IS NULL
        OR o.customer_name    ILIKE '%' || $3::text || '%'
        OR o.operation_number ILIKE '%' || $3::text || '%'
        OR o.end_address      ILIKE '%' || $3::text || '%'
        OR o.address          ILIKE '%' || $3::text || '%'
        OR o.municipio        ILIKE '%' || $3::text || '%'
        OR o.vendedor         ILIKE '%' || $3::text || '%'
        OR EXISTS (
            SELECT 1 FROM order_items oi
            WHERE oi.order_id = o.id
              AND oi.description ILIKE '%' || $3::text || '%'
        )
    )
    AND (
        $4::text IS NULL
        OR ($4::text = 'completada' AND o.estado = 'completada')
        OR ($4::text = 'en_proceso'
            AND (o.estado IS NULL OR o.estado <> 'completada')
            AND (o.fecha_comprometida IS NULL OR o.fecha_comprometida >= now()))
        OR ($4::text = 'expirada'
            AND (o.estado IS NULL OR o.estado <> 'completada')
            AND o.fecha_comprometida < now())
    )
    AND ($5::boolean IS NULL OR o.archivado = $5::boolean)
    AND (
        $6::boolean IS NULL
        OR ($6::boolean AND o.requiere_domicilio)
        OR (NOT $6::boolean
            AND (o.requiere_domicilio IS NULL OR NOT o.requiere_domicilio))
    )
    AND (
        $7::boolean IS NULL
        OR ($7::boolean AND o.pedido_costo IS NOT NULL)
        OR (NOT $7::boolean AND o.pedido_costo IS NULL)
    )
    AND ($8::text IS NULL OR o.municipio = $8::text)
    AND ($9::text  IS NULL OR o.vendedor  = $9::text)
    AND (
        $10::text IS NULL
        OR ($10::text = 'sin_entregar'
            AND o.route_id IS NULL AND o.delivered_at IS NULL
            AND (o.resultado IS NULL OR o.resultado <> 'entregado'))
        OR ($10::text = 'en_despacho' AND r.status = 'planned')
        OR ($10::text = 'en_ruta'     AND r.status = 'in_progress')
        OR ($10::text = 'entregado'
            AND (o.resultado = 'entregado' OR o.delivered_at IS NOT NULL))
        OR ($10::text = 'devuelto'
            AND o.resultado IN ('devuelto', 'cancelado'))
    )
    AND (
        $11::text IS NULL
        OR ($11::text = 'con_factura' AND o.factura_estado IN ('igual', 'cambiado'))
        OR ($11::text = 'cuadra'      AND o.factura_estado = 'igual')
        OR ($11::text = 'sin_cotejar' AND o.factura_estado IS NULL)
        OR ($11::text NOT IN ('con_factura', 'cuadra', 'sin_cotejar')
            AND o.factura_estado::text = $11::text)
    )
    AND (
        ($12::timestamptz IS NULL AND $13::timestamptz IS NULL)
        OR (o.order_date IS NOT NULL
            AND ($12::timestamptz IS NULL OR o.order_date >= $12::timestamptz)
            AND ($13::timestamptz IS NULL OR o.order_date <= $13::timestamptz))
        OR (o.order_date IS NULL
            AND ($12::timestamptz IS NULL OR o.created_at >= $12::timestamptz)
            AND ($13::timestamptz IS NULL OR o.created_at <= $13::timestamptz))
    )
`

type ContarPedidosParams struct {
	Sucursal  pgtype.UUID        `json:"sucursal"`
	BranchID  pgtype.UUID        `json:"branch_id"`
	Q         *string            `json:"q"`
	Estado    *string            `json:"estado"`
	Archivado *bool              `json:"archivado"`
	Domicilio *bool              `json:"domicilio"`
	Cotizado  *bool              `json:"cotizado"`
	Municipio *string            `json:"municipio"`
	Vendedor  *string            `json:"vendedor"`
	Reparto   *string            `json:"reparto"`
	Factura   *string            `json:"factura"`
	Desde     pgtype.Timestamptz `json:"desde"`
	Hasta     pgtype.Timestamptz `json:"hasta"`
}

// El total del catálogo, para la paginación. Mismo WHERE que `ListarPedidos`.
func (q *Queries) ContarPedidos(ctx context.Context, arg ContarPedidosParams) (int64, error) {
	row := q.db.QueryRow(ctx, contarPedidos,
		arg.Sucursal,
		arg.BranchID,
		arg.Q,
		arg.Estado,
		arg.Archivado,
		arg.Domicilio,
		arg.Cotizado,
		arg.Municipio,
		arg.Vendedor,
		arg.Reparto,
		arg.Factura,
		arg.Desde,
		arg.Hasta,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const contarPedidosDisponibles = `-- name: ContarPedidosDisponibles :one
SELECT count(*)
FROM orders o
WHERE
    o.source = 'pedido'
    AND o.route_id IS NULL
    -- UN PEDIDO ENTREGADO NO SE VUELVE A OFRECER. ` + "`" + `route_id IS NULL` + "`" + ` no basta: un
    -- entregado conserva su ` + "`" + `route_id` + "`" + `, pero la clave ajena es ` + "`" + `ON DELETE SET NULL` + "`" + `
    -- (` + "`" + `db/migrations/00001_init.sql:446` + "`" + `), así que borrar la ruta de ayer deja sueltos
    -- a los que ya se repartieron y esta lista los volvería a ofrecer para el camión de
    -- mañana. Es el mismo par de columnas de ` + "`" + `reparto = 'sin_entregar'` + "`" + `, ahí abajo.
    AND o.delivered_at IS NULL
    AND (o.resultado IS NULL OR o.resultado <> 'entregado')
    AND o.end_lat IS NOT NULL
    AND o.end_lng IS NOT NULL
    AND o.factura_estado IN ('igual', 'cambiado')
    -- ARCHIVADO EN PEDIDO = NO SE REPARTE. Ver el porqué en ListarPedidosDisponibles.
    -- Aquí importa el doble: este recuento es el ` + "`" + `total` + "`" + ` que la pantalla enseña encima de
    -- la lista, así que sin esto diría «2.771 disponibles» sobre una lista de 1.423.
    AND NOT o.archivado
    AND ($1::uuid  IS NULL OR o.branch_id = $1::uuid)
    AND ($2::uuid IS NULL OR o.branch_id = $2::uuid)
    AND (
        $3::text IS NULL
        OR o.customer_name    ILIKE '%' || $3::text || '%'
        OR o.operation_number ILIKE '%' || $3::text || '%'
        OR o.end_address      ILIKE '%' || $3::text || '%'
        OR o.address          ILIKE '%' || $3::text || '%'
        OR o.municipio        ILIKE '%' || $3::text || '%'
        OR o.vendedor         ILIKE '%' || $3::text || '%'
        OR EXISTS (
            SELECT 1 FROM order_items oi
            WHERE oi.order_id = o.id
              AND oi.description ILIKE '%' || $3::text || '%'
        )
    )
    AND (
        $4::text IS NULL
        OR ($4::text = 'completada' AND o.estado = 'completada')
        OR ($4::text = 'en_proceso'
            AND (o.estado IS NULL OR o.estado <> 'completada')
            AND (o.fecha_comprometida IS NULL OR o.fecha_comprometida >= now()))
        OR ($4::text = 'expirada'
            AND (o.estado IS NULL OR o.estado <> 'completada')
            AND o.fecha_comprometida < now())
    )
    AND ($5::boolean IS NULL OR o.archivado = $5::boolean)
    AND (
        $6::boolean IS NULL
        OR ($6::boolean AND o.requiere_domicilio)
        OR (NOT $6::boolean
            AND (o.requiere_domicilio IS NULL OR NOT o.requiere_domicilio))
    )
    AND (
        $7::boolean IS NULL
        OR ($7::boolean AND o.pedido_costo IS NOT NULL)
        OR (NOT $7::boolean AND o.pedido_costo IS NULL)
    )
    AND ($8::text IS NULL OR o.municipio = $8::text)
    AND ($9::text  IS NULL OR o.vendedor  = $9::text)
    AND (
        $10::text IS NULL
        OR ($10::text = 'sin_entregar'
            AND o.route_id IS NULL AND o.delivered_at IS NULL
            AND (o.resultado IS NULL OR o.resultado <> 'entregado'))
        OR ($10::text = 'en_despacho'
            AND EXISTS (SELECT 1 FROM routes r WHERE r.id = o.route_id AND r.status = 'planned'))
        OR ($10::text = 'en_ruta'
            AND EXISTS (SELECT 1 FROM routes r WHERE r.id = o.route_id AND r.status = 'in_progress'))
        OR ($10::text = 'entregado'
            AND (o.resultado = 'entregado' OR o.delivered_at IS NOT NULL))
        OR ($10::text = 'devuelto'
            AND o.resultado IN ('devuelto', 'cancelado'))
    )
    AND (
        $11::text IS NULL
        OR ($11::text = 'con_factura' AND o.factura_estado IN ('igual', 'cambiado'))
        OR ($11::text = 'cuadra'      AND o.factura_estado = 'igual')
        OR ($11::text = 'sin_cotejar' AND o.factura_estado IS NULL)
        OR ($11::text NOT IN ('con_factura', 'cuadra', 'sin_cotejar')
            AND o.factura_estado::text = $11::text)
    )
    AND (
        ($12::timestamptz IS NULL AND $13::timestamptz IS NULL)
        OR (o.order_date IS NOT NULL
            AND ($12::timestamptz IS NULL OR o.order_date >= $12::timestamptz)
            AND ($13::timestamptz IS NULL OR o.order_date <= $13::timestamptz))
        OR (o.order_date IS NULL
            AND ($12::timestamptz IS NULL OR o.created_at >= $12::timestamptz)
            AND ($13::timestamptz IS NULL OR o.created_at <= $13::timestamptz))
    )
    AND (
        $14::timestamptz IS NULL
        OR (o.order_date IS NOT NULL
            AND o.order_date >= $14::timestamptz
            AND o.order_date <  $15::timestamptz)
        OR (o.order_date IS NULL
            AND o.created_at >= $14::timestamptz
            AND o.created_at <  $15::timestamptz)
    )
`

type ContarPedidosDisponiblesParams struct {
	Sucursal  pgtype.UUID        `json:"sucursal"`
	BranchID  pgtype.UUID        `json:"branch_id"`
	Q         *string            `json:"q"`
	Estado    *string            `json:"estado"`
	Archivado *bool              `json:"archivado"`
	Domicilio *bool              `json:"domicilio"`
	Cotizado  *bool              `json:"cotizado"`
	Municipio *string            `json:"municipio"`
	Vendedor  *string            `json:"vendedor"`
	Reparto   *string            `json:"reparto"`
	Factura   *string            `json:"factura"`
	Desde     pgtype.Timestamptz `json:"desde"`
	Hasta     pgtype.Timestamptz `json:"hasta"`
	DiaDesde  pgtype.Timestamptz `json:"dia_desde"`
	DiaHasta  pgtype.Timestamptz `json:"dia_hasta"`
}

// El `total` de la pantalla de disponibles: el mismo WHERE, sin tope ni orden.
// Tiene que ser EL MISMO o el contador dice una cosa y la tabla otra.
func (q *Queries) ContarPedidosDisponibles(ctx context.Context, arg ContarPedidosDisponiblesParams) (int64, error) {
	row := q.db.QueryRow(ctx, contarPedidosDisponibles,
		arg.Sucursal,
		arg.BranchID,
		arg.Q,
		arg.Estado,
		arg.Archivado,
		arg.Domicilio,
		arg.Cotizado,
		arg.Municipio,
		arg.Vendedor,
		arg.Reparto,
		arg.Factura,
		arg.Desde,
		arg.Hasta,
		arg.DiaDesde,
		arg.DiaHasta,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const crearRenglonDePedido = `-- name: CrearRenglonDePedido :one
INSERT INTO order_items (order_id, linea, description, quantity, packs, product_id)
VALUES (
    $1, $2, $3,
    $4, $5, $6
)
RETURNING id, order_id, linea, description, quantity, packs, product_id
`

type CrearRenglonDePedidoParams struct {
	PedidoID    uuid.UUID   `json:"pedido_id"`
	Linea       int32       `json:"linea"`
	Description string      `json:"description"`
	Quantity    float64     `json:"quantity"`
	Packs       *float64    `json:"packs"`
	ProductID   pgtype.UUID `json:"product_id"`
}

type CrearRenglonDePedidoRow struct {
	ID          uuid.UUID   `json:"id"`
	OrderID     uuid.UUID   `json:"order_id"`
	Linea       int32       `json:"linea"`
	Description string      `json:"description"`
	Quantity    float64     `json:"quantity"`
	Packs       *float64    `json:"packs"`
	ProductID   pgtype.UUID `json:"product_id"`
}

func (q *Queries) CrearRenglonDePedido(ctx context.Context, arg CrearRenglonDePedidoParams) (CrearRenglonDePedidoRow, error) {
	row := q.db.QueryRow(ctx, crearRenglonDePedido,
		arg.PedidoID,
		arg.Linea,
		arg.Description,
		arg.Quantity,
		arg.Packs,
		arg.ProductID,
	)
	var i CrearRenglonDePedidoRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Linea,
		&i.Description,
		&i.Quantity,
		&i.Packs,
		&i.ProductID,
	)
	return i, err
}

const diferenciasDePedidos = `-- name: DiferenciasDePedidos :many

WITH tocados AS (
    -- Los pedidos tocados por sí mismos...
    SELECT o.id
    FROM orders o
    WHERE $3::timestamptz IS NULL
       OR o.updated_at > $3::timestamptz
    UNION
    -- ...y los que arrastra un renglón suyo. UNION y no UNION ALL: un pedido con tres
    -- renglones tocados es un pedido, no tres.
    SELECT oi.order_id AS id
    FROM order_items oi
    WHERE $3::timestamptz IS NOT NULL
      AND oi.updated_at > $3::timestamptz
),
marcados AS (
    SELECT
        o.id, o.operation_number, o.customer_name, o.customer_phone, o.address,
        o.end_address, o.end_lat, o.end_lng, o.lat, o.lng, o.weight, o.status,
        o.trip_leg, o.notes, o.route_id, o.ultima_ruta_id, o.vehicle_id, o.price,
        o.segment_km, o.delivery_price, o.delivery_distance_km, o.branch_id,
        o.source, o.external_id, o.order_date, o.pedido_updated_at, o.estado,
        o.archivado, o.fecha_comprometida, o.requiere_domicilio, o.pedido_costo,
        o.municipio, o.vendedor, o.sucursal_codigo, o.factura_estado,
        o.factura_numero, o.factura_at, o.factura_domicilio, o.factura_corregido_at,
        o.stop_order, o.delivered_at, o.resultado, o.resultado_at, o.resultado_nota,
        o.created_at, o.updated_at,
        GREATEST(
            o.updated_at,
            coalesce(
                (SELECT max(oi.updated_at) FROM order_items oi WHERE oi.order_id = o.id),
                o.updated_at
            )
        )::timestamptz AS cambiado_at
    FROM orders o
    JOIN tocados t ON t.id = o.id
    WHERE ($4::uuid  IS NULL OR o.branch_id = $4::uuid)
      AND ($5::uuid IS NULL OR o.branch_id = $5::uuid)
      AND ($6::boolean OR NOT o.archivado)
)
SELECT
    id, operation_number, customer_name, customer_phone, address, end_address,
    end_lat, end_lng, lat, lng, weight, status, trip_leg, notes, route_id,
    ultima_ruta_id, vehicle_id, price, segment_km, delivery_price,
    delivery_distance_km, branch_id, source, external_id, order_date,
    pedido_updated_at, estado, archivado, fecha_comprometida, requiere_domicilio,
    pedido_costo, municipio, vendedor, sucursal_codigo, factura_estado,
    factura_numero, factura_at, factura_domicilio, factura_corregido_at,
    stop_order, delivered_at, resultado, resultado_at, resultado_nota,
    created_at, updated_at, cambiado_at
FROM marcados
WHERE $1::timestamptz IS NULL
   OR cambiado_at <= $1::timestamptz
ORDER BY cambiado_at ASC, id ASC
LIMIT $2
`

type DiferenciasDePedidosParams struct {
	Hasta         pgtype.Timestamptz `json:"hasta"`
	Tope          int32              `json:"tope"`
	Desde         pgtype.Timestamptz `json:"desde"`
	Sucursal      pgtype.UUID        `json:"sucursal"`
	BranchID      pgtype.UUID        `json:"branch_id"`
	ConArchivados bool               `json:"con_archivados"`
}

type DiferenciasDePedidosRow struct {
	ID                 uuid.UUID          `json:"id"`
	OperationNumber    *string            `json:"operation_number"`
	CustomerName       string             `json:"customer_name"`
	CustomerPhone      *string            `json:"customer_phone"`
	Address            string             `json:"address"`
	EndAddress         *string            `json:"end_address"`
	EndLat             *float64           `json:"end_lat"`
	EndLng             *float64           `json:"end_lng"`
	Lat                *float64           `json:"lat"`
	Lng                *float64           `json:"lng"`
	Weight             float64            `json:"weight"`
	Status             OrderStatus        `json:"status"`
	TripLeg            TripLeg            `json:"trip_leg"`
	Notes              *string            `json:"notes"`
	RouteID            pgtype.UUID        `json:"route_id"`
	UltimaRutaID       pgtype.UUID        `json:"ultima_ruta_id"`
	VehicleID          pgtype.UUID        `json:"vehicle_id"`
	Price              *float64           `json:"price"`
	SegmentKm          *float64           `json:"segment_km"`
	DeliveryPrice      *float64           `json:"delivery_price"`
	DeliveryDistanceKm *float64           `json:"delivery_distance_km"`
	BranchID           pgtype.UUID        `json:"branch_id"`
	Source             *Procedencia       `json:"source"`
	ExternalID         *string            `json:"external_id"`
	OrderDate          pgtype.Timestamptz `json:"order_date"`
	PedidoUpdatedAt    pgtype.Timestamptz `json:"pedido_updated_at"`
	Estado             *PedidoEstado      `json:"estado"`
	Archivado          bool               `json:"archivado"`
	FechaComprometida  pgtype.Timestamptz `json:"fecha_comprometida"`
	RequiereDomicilio  *bool              `json:"requiere_domicilio"`
	PedidoCosto        *float64           `json:"pedido_costo"`
	Municipio          *string            `json:"municipio"`
	Vendedor           *string            `json:"vendedor"`
	SucursalCodigo     *string            `json:"sucursal_codigo"`
	FacturaEstado      *FacturaEstado     `json:"factura_estado"`
	FacturaNumero      *string            `json:"factura_numero"`
	FacturaAt          pgtype.Timestamptz `json:"factura_at"`
	FacturaDomicilio   *float64           `json:"factura_domicilio"`
	FacturaCorregidoAt pgtype.Timestamptz `json:"factura_corregido_at"`
	StopOrder          *int32             `json:"stop_order"`
	DeliveredAt        pgtype.Timestamptz `json:"delivered_at"`
	Resultado          *StopResult        `json:"resultado"`
	ResultadoAt        pgtype.Timestamptz `json:"resultado_at"`
	ResultadoNota      *string            `json:"resultado_nota"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CambiadoAt         pgtype.Timestamptz `json:"cambiado_at"`
}

// ---------------------------------------------------------------------------
// La bajada del aparato  (GET /api/sync/cambios, colección `orders`)
// ---------------------------------------------------------------------------
// LO QUE CAMBIÓ DESDE UNA MARCA, en una sucursal. Es la consulta que faltaba y sin la
// cual el trabajo sin conexión no existe: el logístico se baja los pedidos por la mañana
// y los prepara todo el día sin red.
//
// `cambiado_at` NO ES `o.updated_at`, y ésa es la razón de ser de esta consulta.
//
//	Es el más nuevo de los dos: el del pedido y el de sus renglones. Si cambia un renglón
//	—PEDIDO reescribe las líneas con lo que dijo la factura— el pedido NO se toca, así que
//	su `updated_at` se queda quieto y el pedido no saldría en las diferencias. El aparato
//	se quedaría con la lista de mercancía vieja y el camión cargaría lo que ya no es.
//	Por eso el renglón arrastra a su pedido.
//
//	Y es también LA MARCA QUE SE DEVUELVE: el aparato la guarda y con ella pide la
//	siguiente vez. Devolver `o.updated_at` y filtrar por el otro sería darle una marca
//	atrasada con la que volvería a bajarse lo mismo una y otra vez.
//
// EL `desde` ES ESTRICTO (`>`) y el `hasta` INCLUSIVO (`<=`): así dos bajadas seguidas
// —`(a,b]` y `(b,c]`— no se pisan ni dejan un hueco en `b`.
//
// LOS ARCHIVADOS ENTRAN CON INTERRUPTOR, `con_archivados`:
//   - En la carga inicial va en false. Un pedido archivado hace ocho meses no tiene por
//     qué bajarse: el aparato empieza vacío y no hay nada que quitarle. Con true, el tope
//     se lo comerían los archivados del histórico y lo del día no cabría.
//   - En las diferencias va en true, porque archivar es justamente lo que hay que
//     contarle al aparato para que lo BORRE. Quien contesta la bajada mira `archivado` y
//     lo manda a `quitados`.
//
// Las dos sucursales del WHERE son las de la casa: `sucursal` es el alcance, que lo pone
// `internal/alcance` y no se puede pasar desde fuera, y `branch_id` es la que pide quien
// llama. Van en AND: la segunda estrecha, nunca amplía.
// POR LA MARCA Y HACIA ADELANTE, que es lo que hace que el tope no pierda nada: lo que no
// cabe en esta tanda se pide en la siguiente con la marca de la última fila servida. Con
// cualquier otro orden, «los 2.000 primeros» son 2.000 cualesquiera y el resto no vuelve.
// El `id` desempata para que dos tandas iguales salgan iguales.
func (q *Queries) DiferenciasDePedidos(ctx context.Context, arg DiferenciasDePedidosParams) ([]DiferenciasDePedidosRow, error) {
	rows, err := q.db.Query(ctx, diferenciasDePedidos,
		arg.Hasta,
		arg.Tope,
		arg.Desde,
		arg.Sucursal,
		arg.BranchID,
		arg.ConArchivados,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiferenciasDePedidosRow
	for rows.Next() {
		var i DiferenciasDePedidosRow
		if err := rows.Scan(
			&i.ID,
			&i.OperationNumber,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.Address,
			&i.EndAddress,
			&i.EndLat,
			&i.EndLng,
			&i.Lat,
			&i.Lng,
			&i.Weight,
			&i.Status,
			&i.TripLeg,
			&i.Notes,
			&i.RouteID,
			&i.UltimaRutaID,
			&i.VehicleID,
			&i.Price,
			&i.SegmentKm,
			&i.DeliveryPrice,
			&i.DeliveryDistanceKm,
			&i.BranchID,
			&i.Source,
			&i.ExternalID,
			&i.OrderDate,
			&i.PedidoUpdatedAt,
			&i.Estado,
			&i.Archivado,
			&i.FechaComprometida,
			&i.RequiereDomicilio,
			&i.PedidoCosto,
			&i.Municipio,
			&i.Vendedor,
			&i.SucursalCodigo,
			&i.FacturaEstado,
			&i.FacturaNumero,
			&i.FacturaAt,
			&i.FacturaDomicilio,
			&i.FacturaCorregidoAt,
			&i.StopOrder,
			&i.DeliveredAt,
			&i.Resultado,
			&i.ResultadoAt,
			&i.ResultadoNota,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CambiadoAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const facetasMunicipios = `-- name: FacetasMunicipios :many

SELECT o.municipio AS valor, count(*) AS pedidos
FROM orders o
WHERE o.municipio IS NOT NULL
  AND ($1::uuid IS NULL OR o.branch_id = $1::uuid)
GROUP BY o.municipio
ORDER BY o.municipio ASC
`

type FacetasMunicipiosRow struct {
	Valor   *string `json:"valor"`
	Pedidos int64   `json:"pedidos"`
}

// ---------------------------------------------------------------------------
// Facetas del catálogo  (GET /api/orders/facetas)
// ---------------------------------------------------------------------------
// Los municipios que EXISTEN de verdad en lo que esta persona puede ver, para llenar el
// desplegable. Si se sacaran de una lista fija, ofrecería municipios sin un solo pedido.
func (q *Queries) FacetasMunicipios(ctx context.Context, sucursal pgtype.UUID) ([]FacetasMunicipiosRow, error) {
	rows, err := q.db.Query(ctx, facetasMunicipios, sucursal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FacetasMunicipiosRow
	for rows.Next() {
		var i FacetasMunicipiosRow
		if err := rows.Scan(&i.Valor, &i.Pedidos); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const facetasSucursales = `-- name: FacetasSucursales :many
SELECT
    o.branch_id AS valor,
    b.name        AS sucursal_nombre,
    b.external_id AS sucursal_codigo,
    count(*)      AS pedidos
FROM orders o
LEFT JOIN branches b ON b.id = o.branch_id
WHERE o.branch_id IS NOT NULL
  AND ($1::uuid IS NULL OR o.branch_id = $1::uuid)
GROUP BY o.branch_id, b.name, b.external_id
ORDER BY b.name ASC NULLS LAST
`

type FacetasSucursalesRow struct {
	Valor          pgtype.UUID `json:"valor"`
	SucursalNombre *string     `json:"sucursal_nombre"`
	SucursalCodigo *string     `json:"sucursal_codigo"`
	Pedidos        int64       `json:"pedidos"`
}

// Las sucursales con pedidos. El nombre se compone aquí —«Nombre (COD)»— porque es lo que
// la gente reconoce: el código a secas no dice nada y el nombre solo se repite.
func (q *Queries) FacetasSucursales(ctx context.Context, sucursal pgtype.UUID) ([]FacetasSucursalesRow, error) {
	rows, err := q.db.Query(ctx, facetasSucursales, sucursal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FacetasSucursalesRow
	for rows.Next() {
		var i FacetasSucursalesRow
		if err := rows.Scan(
			&i.Valor,
			&i.SucursalNombre,
			&i.SucursalCodigo,
			&i.Pedidos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const facetasVendedores = `-- name: FacetasVendedores :many
SELECT o.vendedor AS valor, count(*) AS pedidos
FROM orders o
WHERE o.vendedor IS NOT NULL
  AND ($1::uuid IS NULL OR o.branch_id = $1::uuid)
GROUP BY o.vendedor
ORDER BY o.vendedor ASC
`

type FacetasVendedoresRow struct {
	Valor   *string `json:"valor"`
	Pedidos int64   `json:"pedidos"`
}

func (q *Queries) FacetasVendedores(ctx context.Context, sucursal pgtype.UUID) ([]FacetasVendedoresRow, error) {
	rows, err := q.db.Query(ctx, facetasVendedores, sucursal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FacetasVendedoresRow
	for rows.Next() {
		var i FacetasVendedoresRow
		if err := rows.Scan(&i.Valor, &i.Pedidos); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const guardarPedidoDelEspejo = `-- name: GuardarPedidoDelEspejo :one

INSERT INTO orders (
    operation_number, customer_name, customer_phone, address, end_address,
    lat, lng, end_lat, end_lng, weight, branch_id, source, external_id, order_date,
    pedido_updated_at, estado, archivado, fecha_comprometida, requiere_domicilio,
    pedido_costo, municipio, vendedor, sucursal_codigo, factura_estado,
    factura_numero, factura_at, factura_domicilio, factura_corregido_at,
    delivery_distance_km, delivery_price
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13,
    $14, $15, $16,
    $17, $18, $19,
    $20, $21, $22,
    $23, $24, $25,
    $26, $27, $28,
    $29, $30
)
ON CONFLICT (source, external_id) WHERE source IS NOT NULL AND external_id IS NOT NULL
DO UPDATE SET
    operation_number     = excluded.operation_number,
    customer_name        = excluded.customer_name,
    customer_phone       = excluded.customer_phone,
    address              = excluded.address,
    end_address          = excluded.end_address,
    lat                  = excluded.lat,
    lng                  = excluded.lng,
    end_lat              = excluded.end_lat,
    end_lng              = excluded.end_lng,
    weight               = excluded.weight,
    branch_id            = excluded.branch_id,
    order_date           = excluded.order_date,
    pedido_updated_at    = excluded.pedido_updated_at,
    estado               = excluded.estado,
    archivado            = excluded.archivado,
    fecha_comprometida   = excluded.fecha_comprometida,
    requiere_domicilio   = excluded.requiere_domicilio,
    pedido_costo         = excluded.pedido_costo,
    municipio            = excluded.municipio,
    vendedor             = excluded.vendedor,
    sucursal_codigo      = excluded.sucursal_codigo,
    factura_estado       = excluded.factura_estado,
    factura_numero       = excluded.factura_numero,
    factura_at           = excluded.factura_at,
    factura_domicilio    = excluded.factura_domicilio,
    factura_corregido_at = excluded.factura_corregido_at,
    delivery_distance_km = excluded.delivery_distance_km,
    delivery_price       = excluded.delivery_price
RETURNING id, branch_id, external_id, (xmax = 0)::boolean AS es_nuevo
`

type GuardarPedidoDelEspejoParams struct {
	OperationNumber    *string            `json:"operation_number"`
	CustomerName       string             `json:"customer_name"`
	CustomerPhone      *string            `json:"customer_phone"`
	Address            string             `json:"address"`
	EndAddress         *string            `json:"end_address"`
	Lat                *float64           `json:"lat"`
	Lng                *float64           `json:"lng"`
	EndLat             *float64           `json:"end_lat"`
	EndLng             *float64           `json:"end_lng"`
	Weight             float64            `json:"weight"`
	BranchID           pgtype.UUID        `json:"branch_id"`
	Source             *Procedencia       `json:"source"`
	ExternalID         *string            `json:"external_id"`
	OrderDate          pgtype.Timestamptz `json:"order_date"`
	PedidoUpdatedAt    pgtype.Timestamptz `json:"pedido_updated_at"`
	Estado             *PedidoEstado      `json:"estado"`
	Archivado          bool               `json:"archivado"`
	FechaComprometida  pgtype.Timestamptz `json:"fecha_comprometida"`
	RequiereDomicilio  *bool              `json:"requiere_domicilio"`
	PedidoCosto        *float64           `json:"pedido_costo"`
	Municipio          *string            `json:"municipio"`
	Vendedor           *string            `json:"vendedor"`
	SucursalCodigo     *string            `json:"sucursal_codigo"`
	FacturaEstado      *FacturaEstado     `json:"factura_estado"`
	FacturaNumero      *string            `json:"factura_numero"`
	FacturaAt          pgtype.Timestamptz `json:"factura_at"`
	FacturaDomicilio   *float64           `json:"factura_domicilio"`
	FacturaCorregidoAt pgtype.Timestamptz `json:"factura_corregido_at"`
	DeliveryDistanceKm *float64           `json:"delivery_distance_km"`
	DeliveryPrice      *float64           `json:"delivery_price"`
}

type GuardarPedidoDelEspejoRow struct {
	ID         uuid.UUID   `json:"id"`
	BranchID   pgtype.UUID `json:"branch_id"`
	ExternalID *string     `json:"external_id"`
	EsNuevo    bool        `json:"es_nuevo"`
}

// ---------------------------------------------------------------------------
// El espejo de PEDIDO  (POST /api/quote/batch)
// ---------------------------------------------------------------------------
// Alta o actualización idempotente por (`source`, `external_id`): volver a pasar el mismo
// lote no duplica. Va sin alcance porque el espejo entra con clave de servicio y trae las
// ocho sucursales de una vez; la sucursal de cada pedido la decide el propio lote.
//
// POR QUÉ UNA SOLA CONSULTA CON `ON CONFLICT` Y NO BUSCAR-Y-ESCRIBIR: `orders_origen_idx`
// es un índice ÚNICO parcial (ver la migración). Con buscar-y-escribir, dos pasadas del
// espejo a la vez leen «no existe» antes de que ninguna escriba y crean el mismo pedido
// DOS VECES — y entonces sale dos veces en la lista del armador, con el mismo folio, y
// alguien lo carga dos veces en el camión. Con el upsert la carrera la resuelve Postgres.
//
// El `WHERE` del `ON CONFLICT` repite el del índice parcial: sin él Postgres no sabe qué
// índice inferir y rechaza la consulta al ejecutarla.
//
// LO QUE NO SE PISA NUNCA al actualizar: `route_id`, `ultima_ruta_id`, `stop_order`,
// `resultado`, `resultado_nota` y `delivered_at`. Eso es del reparto y PEDIDO no sabe nada
// de ello: dejarlo entrar borraría de un plumazo el resultado de una parada ya cerrada,
// que es justo el dato que dice qué mercancía bajó del camión.
//
// `xmax = 0` es el truco de Postgres para saber si la fila se INSERTÓ o se ACTUALIZÓ: en
// una fila recién insertada el id de la transacción que la borró todavía es cero. Hace
// falta para poder decir en el registro cuántos pedidos son nuevos sin una consulta más.
func (q *Queries) GuardarPedidoDelEspejo(ctx context.Context, arg GuardarPedidoDelEspejoParams) (GuardarPedidoDelEspejoRow, error) {
	row := q.db.QueryRow(ctx, guardarPedidoDelEspejo,
		arg.OperationNumber,
		arg.CustomerName,
		arg.CustomerPhone,
		arg.Address,
		arg.EndAddress,
		arg.Lat,
		arg.Lng,
		arg.EndLat,
		arg.EndLng,
		arg.Weight,
		arg.BranchID,
		arg.Source,
		arg.ExternalID,
		arg.OrderDate,
		arg.PedidoUpdatedAt,
		arg.Estado,
		arg.Archivado,
		arg.FechaComprometida,
		arg.RequiereDomicilio,
		arg.PedidoCosto,
		arg.Municipio,
		arg.Vendedor,
		arg.SucursalCodigo,
		arg.FacturaEstado,
		arg.FacturaNumero,
		arg.FacturaAt,
		arg.FacturaDomicilio,
		arg.FacturaCorregidoAt,
		arg.DeliveryDistanceKm,
		arg.DeliveryPrice,
	)
	var i GuardarPedidoDelEspejoRow
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ExternalID,
		&i.EsNuevo,
	)
	return i, err
}

const listarPedidos = `-- name: ListarPedidos :many

SELECT
    o.id, o.operation_number, o.customer_name, o.customer_phone, o.address,
    o.end_address, o.end_lat, o.end_lng, o.weight, o.status, o.notes,
    o.route_id, o.delivery_price, o.delivery_distance_km, o.order_date,
    o.created_at, o.delivered_at, o.resultado, o.resultado_nota, o.stop_order,
    o.estado, o.archivado, o.fecha_comprometida, o.requiere_domicilio,
    o.pedido_costo, o.factura_estado, o.factura_numero, o.factura_domicilio,
    o.municipio, o.vendedor, o.sucursal_codigo, o.branch_id, o.updated_at,
    r.name          AS ruta_nombre,
    r.route_code    AS ruta_codigo,
    r.status        AS ruta_estado,
    r.delivery_date AS ruta_fecha,
    v.name          AS vehiculo_nombre,
    v.plate         AS vehiculo_matricula,
    b.name          AS sucursal_nombre,
    b.lat           AS sucursal_lat,
    b.lng           AS sucursal_lng
FROM orders o
LEFT JOIN routes   r ON r.id = o.route_id
LEFT JOIN vehicles v ON v.id = r.vehicle_id
LEFT JOIN branches b ON b.id = o.branch_id
WHERE
    ($1::uuid  IS NULL OR o.branch_id = $1::uuid)
    AND ($2::uuid IS NULL OR o.branch_id = $2::uuid)
    AND (
        $3::text IS NULL
        OR o.customer_name    ILIKE '%' || $3::text || '%'
        OR o.operation_number ILIKE '%' || $3::text || '%'
        OR o.end_address      ILIKE '%' || $3::text || '%'
        OR o.address          ILIKE '%' || $3::text || '%'
        OR o.municipio        ILIKE '%' || $3::text || '%'
        OR o.vendedor         ILIKE '%' || $3::text || '%'
        OR EXISTS (
            SELECT 1 FROM order_items oi
            WHERE oi.order_id = o.id
              AND oi.description ILIKE '%' || $3::text || '%'
        )
    )
    AND (
        $4::text IS NULL
        OR ($4::text = 'completada' AND o.estado = 'completada')
        OR ($4::text = 'en_proceso'
            AND (o.estado IS NULL OR o.estado <> 'completada')
            AND (o.fecha_comprometida IS NULL OR o.fecha_comprometida >= now()))
        OR ($4::text = 'expirada'
            AND (o.estado IS NULL OR o.estado <> 'completada')
            AND o.fecha_comprometida < now())
    )
    AND ($5::boolean IS NULL OR o.archivado = $5::boolean)
    AND (
        $6::boolean IS NULL
        OR ($6::boolean AND o.requiere_domicilio)
        OR (NOT $6::boolean
            AND (o.requiere_domicilio IS NULL OR NOT o.requiere_domicilio))
    )
    AND (
        $7::boolean IS NULL
        OR ($7::boolean AND o.pedido_costo IS NOT NULL)
        OR (NOT $7::boolean AND o.pedido_costo IS NULL)
    )
    AND ($8::text IS NULL OR o.municipio = $8::text)
    AND ($9::text  IS NULL OR o.vendedor  = $9::text)
    AND (
        $10::text IS NULL
        OR ($10::text = 'sin_entregar'
            AND o.route_id IS NULL AND o.delivered_at IS NULL
            AND (o.resultado IS NULL OR o.resultado <> 'entregado'))
        OR ($10::text = 'en_despacho' AND r.status = 'planned')
        OR ($10::text = 'en_ruta'     AND r.status = 'in_progress')
        OR ($10::text = 'entregado'
            AND (o.resultado = 'entregado' OR o.delivered_at IS NOT NULL))
        OR ($10::text = 'devuelto'
            AND o.resultado IN ('devuelto', 'cancelado'))
    )
    AND (
        $11::text IS NULL
        OR ($11::text = 'con_factura' AND o.factura_estado IN ('igual', 'cambiado'))
        OR ($11::text = 'cuadra'      AND o.factura_estado = 'igual')
        OR ($11::text = 'sin_cotejar' AND o.factura_estado IS NULL)
        OR ($11::text NOT IN ('con_factura', 'cuadra', 'sin_cotejar')
            AND o.factura_estado::text = $11::text)
    )
    AND (
        ($12::timestamptz IS NULL AND $13::timestamptz IS NULL)
        OR (o.order_date IS NOT NULL
            AND ($12::timestamptz IS NULL OR o.order_date >= $12::timestamptz)
            AND ($13::timestamptz IS NULL OR o.order_date <= $13::timestamptz))
        OR (o.order_date IS NULL
            AND ($12::timestamptz IS NULL OR o.created_at >= $12::timestamptz)
            AND ($13::timestamptz IS NULL OR o.created_at <= $13::timestamptz))
    )
ORDER BY o.order_date DESC NULLS LAST, o.created_at DESC
LIMIT $15 OFFSET $14
`

type ListarPedidosParams struct {
	Sucursal       pgtype.UUID        `json:"sucursal"`
	BranchID       pgtype.UUID        `json:"branch_id"`
	Q              *string            `json:"q"`
	Estado         *string            `json:"estado"`
	Archivado      *bool              `json:"archivado"`
	Domicilio      *bool              `json:"domicilio"`
	Cotizado       *bool              `json:"cotizado"`
	Municipio      *string            `json:"municipio"`
	Vendedor       *string            `json:"vendedor"`
	Reparto        *string            `json:"reparto"`
	Factura        *string            `json:"factura"`
	Desde          pgtype.Timestamptz `json:"desde"`
	Hasta          pgtype.Timestamptz `json:"hasta"`
	Desplazamiento int32              `json:"desplazamiento"`
	Limite         int32              `json:"limite"`
}

type ListarPedidosRow struct {
	ID                 uuid.UUID          `json:"id"`
	OperationNumber    *string            `json:"operation_number"`
	CustomerName       string             `json:"customer_name"`
	CustomerPhone      *string            `json:"customer_phone"`
	Address            string             `json:"address"`
	EndAddress         *string            `json:"end_address"`
	EndLat             *float64           `json:"end_lat"`
	EndLng             *float64           `json:"end_lng"`
	Weight             float64            `json:"weight"`
	Status             OrderStatus        `json:"status"`
	Notes              *string            `json:"notes"`
	RouteID            pgtype.UUID        `json:"route_id"`
	DeliveryPrice      *float64           `json:"delivery_price"`
	DeliveryDistanceKm *float64           `json:"delivery_distance_km"`
	OrderDate          pgtype.Timestamptz `json:"order_date"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	DeliveredAt        pgtype.Timestamptz `json:"delivered_at"`
	Resultado          *StopResult        `json:"resultado"`
	ResultadoNota      *string            `json:"resultado_nota"`
	StopOrder          *int32             `json:"stop_order"`
	Estado             *PedidoEstado      `json:"estado"`
	Archivado          bool               `json:"archivado"`
	FechaComprometida  pgtype.Timestamptz `json:"fecha_comprometida"`
	RequiereDomicilio  *bool              `json:"requiere_domicilio"`
	PedidoCosto        *float64           `json:"pedido_costo"`
	FacturaEstado      *FacturaEstado     `json:"factura_estado"`
	FacturaNumero      *string            `json:"factura_numero"`
	FacturaDomicilio   *float64           `json:"factura_domicilio"`
	Municipio          *string            `json:"municipio"`
	Vendedor           *string            `json:"vendedor"`
	SucursalCodigo     *string            `json:"sucursal_codigo"`
	BranchID           pgtype.UUID        `json:"branch_id"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	RutaNombre         *string            `json:"ruta_nombre"`
	RutaCodigo         *string            `json:"ruta_codigo"`
	RutaEstado         *RouteStatus       `json:"ruta_estado"`
	RutaFecha          pgtype.Timestamptz `json:"ruta_fecha"`
	VehiculoNombre     *string            `json:"vehiculo_nombre"`
	VehiculoMatricula  *string            `json:"vehiculo_matricula"`
	SucursalNombre     *string            `json:"sucursal_nombre"`
	SucursalLat        *float64           `json:"sucursal_lat"`
	SucursalLng        *float64           `json:"sucursal_lng"`
}

// ---------------------------------------------------------------------------
// El catálogo de pedidos  (GET /api/orders)
// ---------------------------------------------------------------------------
// La lista paginada, con su ruta y su sucursal. Mismos filtros que los disponibles —tienen
// que significar lo MISMO en las dos pantallas o los números no cuadran y nadie sabe cuál
// creerse—, pero SIN las cinco condiciones fijas: aquí se ve todo el histórico.
func (q *Queries) ListarPedidos(ctx context.Context, arg ListarPedidosParams) ([]ListarPedidosRow, error) {
	rows, err := q.db.Query(ctx, listarPedidos,
		arg.Sucursal,
		arg.BranchID,
		arg.Q,
		arg.Estado,
		arg.Archivado,
		arg.Domicilio,
		arg.Cotizado,
		arg.Municipio,
		arg.Vendedor,
		arg.Reparto,
		arg.Factura,
		arg.Desde,
		arg.Hasta,
		arg.Desplazamiento,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarPedidosRow
	for rows.Next() {
		var i ListarPedidosRow
		if err := rows.Scan(
			&i.ID,
			&i.OperationNumber,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.Address,
			&i.EndAddress,
			&i.EndLat,
			&i.EndLng,
			&i.Weight,
			&i.Status,
			&i.Notes,
			&i.RouteID,
			&i.DeliveryPrice,
			&i.DeliveryDistanceKm,
			&i.OrderDate,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.Resultado,
			&i.ResultadoNota,
			&i.StopOrder,
			&i.Estado,
			&i.Archivado,
			&i.FechaComprometida,
			&i.RequiereDomicilio,
			&i.PedidoCosto,
			&i.FacturaEstado,
			&i.FacturaNumero,
			&i.FacturaDomicilio,
			&i.Municipio,
			&i.Vendedor,
			&i.SucursalCodigo,
			&i.BranchID,
			&i.UpdatedAt,
			&i.RutaNombre,
			&i.RutaCodigo,
			&i.RutaEstado,
			&i.RutaFecha,
			&i.VehiculoNombre,
			&i.VehiculoMatricula,
			&i.SucursalNombre,
			&i.SucursalLat,
			&i.SucursalLng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPedidosDisponibles = `-- name: ListarPedidosDisponibles :many


SELECT
    o.id, o.order_date, o.created_at, o.operation_number, o.customer_name,
    o.address, o.end_address, o.end_lat, o.end_lng, o.weight,
    o.delivery_price, o.delivery_distance_km, o.estado, o.archivado,
    o.requiere_domicilio, o.pedido_costo, o.municipio, o.vendedor,
    o.branch_id, o.factura_estado, o.sucursal_codigo
FROM orders o
WHERE
    o.source = 'pedido'
    AND o.route_id IS NULL
    -- UN PEDIDO ENTREGADO NO SE VUELVE A OFRECER. ` + "`" + `route_id IS NULL` + "`" + ` no basta: un
    -- entregado conserva su ` + "`" + `route_id` + "`" + `, pero la clave ajena es ` + "`" + `ON DELETE SET NULL` + "`" + `
    -- (` + "`" + `db/migrations/00001_init.sql:446` + "`" + `), así que borrar la ruta de ayer deja sueltos
    -- a los que ya se repartieron y esta lista los volvería a ofrecer para el camión de
    -- mañana. Es el mismo par de columnas de ` + "`" + `reparto = 'sin_entregar'` + "`" + `, ahí abajo.
    AND o.delivered_at IS NULL
    AND (o.resultado IS NULL OR o.resultado <> 'entregado')
    AND o.end_lat IS NOT NULL
    AND o.end_lng IS NOT NULL
    AND o.factura_estado IN ('igual', 'cambiado')
    -- ARCHIVADO EN PEDIDO = NO SE REPARTE.
    --
    -- Faltaba, y con los datos reales del 15/09/2026 eso metia 1.348 pedidos archivados
    -- en la lista del armador: casi la mitad de los 2.771 que se ofrecian. PEDIDO los dio
    -- de baja y aqui salian como disponibles, sin un solo error — la lista se veia
    -- perfectamente normal y el camion salia con mercancia que nadie esperaba.
    --
    -- ` + "`" + `archivado` + "`" + ` es el borrado blando de PEDIDO y son la INMENSA MAYORIA del historico
    -- (50.810 de 55.622), asi que olvidarlo no es un detalle: es ofrecer el archivo entero.
    AND NOT o.archivado
    -- alcance por sucursal
    AND ($1::uuid IS NULL OR o.branch_id = $1::uuid)
    -- ` + "`" + `branch_id` + "`" + ` de la query: estrecha, nunca amplía. Va en AND con el alcance, así que
    -- quien sólo ve una sucursal no puede pedir la de otro poniéndolo a mano.
    AND ($2::uuid IS NULL OR o.branch_id = $2::uuid)
    -- Una sola caja de búsqueda: quien la usa no se para a pensar en qué campo está lo
    -- que recuerda. El EXISTS es la pregunta del despacho: «¿qué pedidos llevan malta?».
    AND (
        $3::text IS NULL
        OR o.customer_name    ILIKE '%' || $3::text || '%'
        OR o.operation_number ILIKE '%' || $3::text || '%'
        OR o.end_address      ILIKE '%' || $3::text || '%'
        OR o.address          ILIKE '%' || $3::text || '%'
        OR o.municipio        ILIKE '%' || $3::text || '%'
        OR o.vendedor         ILIKE '%' || $3::text || '%'
        OR EXISTS (
            SELECT 1 FROM order_items oi
            WHERE oi.order_id = o.id
              AND oi.description ILIKE '%' || $3::text || '%'
        )
    )
    -- ` + "`" + `expirada` + "`" + ` se CALCULA con ` + "`" + `now()` + "`" + ` en cada llamada y no se guarda: un booleano
    -- guardado se queda viejo al día siguiente y empieza a mentir solo.
    -- El ` + "`" + `estado IS NULL` + "`" + ` explícito es obligatorio: ` + "`" + `estado <> 'completada'` + "`" + ` sobre un NULL
    -- da NULL, que no es TRUE, y la fila se cae de los tres filtros a la vez.
    AND (
        $4::text IS NULL
        OR ($4::text = 'completada' AND o.estado = 'completada')
        OR ($4::text = 'en_proceso'
            AND (o.estado IS NULL OR o.estado <> 'completada')
            AND (o.fecha_comprometida IS NULL OR o.fecha_comprometida >= now()))
        OR ($4::text = 'expirada'
            AND (o.estado IS NULL OR o.estado <> 'completada')
            AND o.fecha_comprometida < now())
    )
    AND ($5::boolean IS NULL OR o.archivado = $5::boolean)
    -- «Sin domicilio» incluye los que no traen el dato: no saberlo no es llevarlo.
    AND (
        $6::boolean IS NULL
        OR ($6::boolean AND o.requiere_domicilio)
        OR (NOT $6::boolean
            AND (o.requiere_domicilio IS NULL OR NOT o.requiere_domicilio))
    )
    AND (
        $7::boolean IS NULL
        OR ($7::boolean AND o.pedido_costo IS NOT NULL)
        OR (NOT $7::boolean AND o.pedido_costo IS NULL)
    )
    AND ($8::text IS NULL OR o.municipio = $8::text)
    AND ($9::text  IS NULL OR o.vendedor  = $9::text)
    -- El estado de REPARTO es propio del reparto: no tiene nada que ver con el estado del
    -- pedido en PEDIDO ni con el de la factura. Manda el RESULTADO de la parada y NO el
    -- estado de la ruta: una ruta completada no dice nada de cada parada, y darlo por
    -- bueno convertía en «entregado» lo que el propio cierre había grabado como devuelto.
    AND (
        $10::text IS NULL
        OR ($10::text = 'sin_entregar'
            AND o.route_id IS NULL AND o.delivered_at IS NULL
            AND (o.resultado IS NULL OR o.resultado <> 'entregado'))
        OR ($10::text = 'en_despacho'
            AND EXISTS (SELECT 1 FROM routes r WHERE r.id = o.route_id AND r.status = 'planned'))
        OR ($10::text = 'en_ruta'
            AND EXISTS (SELECT 1 FROM routes r WHERE r.id = o.route_id AND r.status = 'in_progress'))
        OR ($10::text = 'entregado'
            AND (o.resultado = 'entregado' OR o.delivered_at IS NOT NULL))
        OR ($10::text = 'devuelto'
            AND o.resultado IN ('devuelto', 'cancelado'))
    )
    -- ` + "`" + `sin_cotejar` + "`" + ` tiene opción propia porque NULL NO es «cuadra»: quiere decir que no se
    -- sabe —VPN a Ventra caída, pedido fuera de los días que se repasan, sucursal sin base—.
    AND (
        $11::text IS NULL
        OR ($11::text = 'con_factura' AND o.factura_estado IN ('igual', 'cambiado'))
        OR ($11::text = 'cuadra'      AND o.factura_estado = 'igual')
        OR ($11::text = 'sin_cotejar' AND o.factura_estado IS NULL)
        OR ($11::text NOT IN ('con_factura', 'cuadra', 'sin_cotejar')
            AND o.factura_estado::text = $11::text)
    )
    -- La segunda rama es para los pedidos anteriores a que se guardara ` + "`" + `order_date` + "`" + `:
    -- con sólo la primera desaparecerían de toda búsqueda por fechas, y desaparecer sin
    -- decir nada es peor que salir con la fecha aproximada, que la pantalla ya marca.
    -- ` + "`" + `hasta` + "`" + ` lo manda el llamante ya como fin de día: quien escribe el 24 quiere los del 24.
    AND (
        ($12::timestamptz IS NULL AND $13::timestamptz IS NULL)
        OR (o.order_date IS NOT NULL
            AND ($12::timestamptz IS NULL OR o.order_date >= $12::timestamptz)
            AND ($13::timestamptz IS NULL OR o.order_date <= $13::timestamptz))
        OR (o.order_date IS NULL
            AND ($12::timestamptz IS NULL OR o.created_at >= $12::timestamptz)
            AND ($13::timestamptz IS NULL OR o.created_at <= $13::timestamptz))
    )
    -- ` + "`" + `fecha` + "`" + ` acota UN día natural, medio abierto por arriba. Es otro filtro que el rango:
    -- la pantalla del armador ofrece los dos y se combinan en AND.
    AND (
        $14::timestamptz IS NULL
        OR (o.order_date IS NOT NULL
            AND o.order_date >= $14::timestamptz
            AND o.order_date <  $15::timestamptz)
        OR (o.order_date IS NULL
            AND o.created_at >= $14::timestamptz
            AND o.created_at <  $15::timestamptz)
    )
ORDER BY o.order_date DESC NULLS LAST, o.created_at DESC
LIMIT $16
`

type ListarPedidosDisponiblesParams struct {
	Sucursal  pgtype.UUID        `json:"sucursal"`
	BranchID  pgtype.UUID        `json:"branch_id"`
	Q         *string            `json:"q"`
	Estado    *string            `json:"estado"`
	Archivado *bool              `json:"archivado"`
	Domicilio *bool              `json:"domicilio"`
	Cotizado  *bool              `json:"cotizado"`
	Municipio *string            `json:"municipio"`
	Vendedor  *string            `json:"vendedor"`
	Reparto   *string            `json:"reparto"`
	Factura   *string            `json:"factura"`
	Desde     pgtype.Timestamptz `json:"desde"`
	Hasta     pgtype.Timestamptz `json:"hasta"`
	DiaDesde  pgtype.Timestamptz `json:"dia_desde"`
	DiaHasta  pgtype.Timestamptz `json:"dia_hasta"`
	Limite    int32              `json:"limite"`
}

type ListarPedidosDisponiblesRow struct {
	ID                 uuid.UUID          `json:"id"`
	OrderDate          pgtype.Timestamptz `json:"order_date"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	OperationNumber    *string            `json:"operation_number"`
	CustomerName       string             `json:"customer_name"`
	Address            string             `json:"address"`
	EndAddress         *string            `json:"end_address"`
	EndLat             *float64           `json:"end_lat"`
	EndLng             *float64           `json:"end_lng"`
	Weight             float64            `json:"weight"`
	DeliveryPrice      *float64           `json:"delivery_price"`
	DeliveryDistanceKm *float64           `json:"delivery_distance_km"`
	Estado             *PedidoEstado      `json:"estado"`
	Archivado          bool               `json:"archivado"`
	RequiereDomicilio  *bool              `json:"requiere_domicilio"`
	PedidoCosto        *float64           `json:"pedido_costo"`
	Municipio          *string            `json:"municipio"`
	Vendedor           *string            `json:"vendedor"`
	BranchID           pgtype.UUID        `json:"branch_id"`
	FacturaEstado      *FacturaEstado     `json:"factura_estado"`
	SucursalCodigo     *string            `json:"sucursal_codigo"`
}

// Pedidos: el catálogo, los disponibles para repartir, las facetas y el espejo de PEDIDO.
//
// CONVENCIÓN DE PARÁMETROS (vale para todos los ficheros de esta carpeta)
//
//	El alcance por sucursal es SEGURIDAD y va SIEMPRE en el SQL, nunca en Go. Se expresa
//	con un solo parámetro que admite «todas las sucursales» como NULL:
//
//	    (sqlc.narg('sucursal')::uuid IS NULL OR o.branch_id = sqlc.narg('sucursal')::uuid)
//
//	`sqlc.narg('sucursal')` ES el `$1` posicional: sqlc lo numera igual, pero además le
//	pone nombre en el struct de Go. Con doce filtros opcionales, un struct de `Column1..
//	Column12` es exactamente la forma de colar el municipio en la casilla de la sucursal
//	sin que el compilador diga nada. El `::uuid` explícito es lo que obliga a sqlc a
//	generarlo como anulable.
//
//	Los demás filtros opcionales siguen el mismo patrón: NULL = no filtra.
//
// EL TEXTO DE LOS RENGLONES YA NO SE COPIA. Donde delivery buscaba en `productosTexto`
// —una copia a mano de los nombres, porque dentro de un JSON no se busca— aquí va un
// EXISTS contra `order_items`. Un dato copiado en dos sitios acaba discrepando.
// ---------------------------------------------------------------------------
// La lista de pedidos por repartir  (GET /api/orders/available)
// ---------------------------------------------------------------------------
// ¿Qué pedidos puedo meter HOY en una ruta, de los que yo puedo ver?
//
// Las cinco condiciones de arriba del WHERE no son filtros de pantalla y no se negocian:
//   - `source = 'pedido'`      — lo que no vino de PEDIDO no se reparte.
//   - `route_id IS NULL`       — si ya va en una ruta, está ocupado.
//   - `end_lat/end_lng`        — sin coordenadas no hay parada que visitar.
//   - `factura_estado IN ('igual','cambiado')` — LO REPARTIBLE. `cambiado` no es un pedido
//     roto: se facturó distinto de como se pidió y lo que sube al camión son las líneas de
//     la factura. Fuera quedan `sin_factura` (no hay nada que llevar) y el NULL, que
//     significa NO SE SABE: con un NULL colado se armó una ruta sin facturar el 2/09.
//
// `km_max` y `costo_min` NO están aquí a propósito: el contrato los aplica después de la
// consulta, y `total`/`truncated` se calculan ANTES que ellos. Bajarlos al SQL cambiaría
// esos dos números y la pantalla diría «358» sobre una tabla de 120.
func (q *Queries) ListarPedidosDisponibles(ctx context.Context, arg ListarPedidosDisponiblesParams) ([]ListarPedidosDisponiblesRow, error) {
	rows, err := q.db.Query(ctx, listarPedidosDisponibles,
		arg.Sucursal,
		arg.BranchID,
		arg.Q,
		arg.Estado,
		arg.Archivado,
		arg.Domicilio,
		arg.Cotizado,
		arg.Municipio,
		arg.Vendedor,
		arg.Reparto,
		arg.Factura,
		arg.Desde,
		arg.Hasta,
		arg.DiaDesde,
		arg.DiaHasta,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarPedidosDisponiblesRow
	for rows.Next() {
		var i ListarPedidosDisponiblesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderDate,
			&i.CreatedAt,
			&i.OperationNumber,
			&i.CustomerName,
			&i.Address,
			&i.EndAddress,
			&i.EndLat,
			&i.EndLng,
			&i.Weight,
			&i.DeliveryPrice,
			&i.DeliveryDistanceKm,
			&i.Estado,
			&i.Archivado,
			&i.RequiereDomicilio,
			&i.PedidoCosto,
			&i.Municipio,
			&i.Vendedor,
			&i.BranchID,
			&i.FacturaEstado,
			&i.SucursalCodigo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPedidosParaInforme = `-- name: ListarPedidosParaInforme :many
SELECT
    o.id, o.customer_name, o.address, o.end_address, o.weight,
    coalesce(o.price, o.pedido_costo, 0) AS ingreso,
    o.segment_km, o.created_at,
    coalesce(r.route_code, r.name) AS ruta_nombre,
    -- El id del camión sale para poder AGRUPAR por él en ` + "`" + `byVehicle` + "`" + `. Agrupar por nombre
    -- juntaría dos camiones distintos que se llamen igual —«Camión 1» lo hay en varias
    -- sucursales, y la matrícula puede estar vacía—, y el informe daría un vehículo con el
    -- doble de ingresos sin que nada falle.
    v.id    AS vehiculo_id,
    v.name  AS vehiculo_nombre,
    v.plate AS vehiculo_matricula
FROM orders o
LEFT JOIN routes   r ON r.id = o.route_id
LEFT JOIN vehicles v ON v.id = r.vehicle_id
WHERE
    ($1::uuid IS NULL OR o.branch_id = $1::uuid)
    AND ($2::timestamptz IS NULL OR o.created_at >= $2::timestamptz)
    AND ($3::timestamptz IS NULL OR o.created_at <= $3::timestamptz)
    AND ($4::uuid IS NULL OR r.vehicle_id = $4::uuid)
ORDER BY o.created_at DESC
`

type ListarPedidosParaInformeParams struct {
	Sucursal   pgtype.UUID        `json:"sucursal"`
	Desde      pgtype.Timestamptz `json:"desde"`
	Hasta      pgtype.Timestamptz `json:"hasta"`
	VehiculoID pgtype.UUID        `json:"vehiculo_id"`
}

type ListarPedidosParaInformeRow struct {
	ID                uuid.UUID          `json:"id"`
	CustomerName      string             `json:"customer_name"`
	Address           string             `json:"address"`
	EndAddress        *string            `json:"end_address"`
	Weight            float64            `json:"weight"`
	Ingreso           float64            `json:"ingreso"`
	SegmentKm         *float64           `json:"segment_km"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	RutaNombre        *string            `json:"ruta_nombre"`
	VehiculoID        pgtype.UUID        `json:"vehiculo_id"`
	VehiculoNombre    *string            `json:"vehiculo_nombre"`
	VehiculoMatricula *string            `json:"vehiculo_matricula"`
}

// El informe. `ingreso` es `price` si lo hay y si no `pedido_costo`: `price` es el reparto
// de carga de una ruta y `pedido_costo` lo que cobró Entrega; no son lo mismo y cobrar uno
// por el otro es el error que este COALESCE hace visible en un solo sitio.
func (q *Queries) ListarPedidosParaInforme(ctx context.Context, arg ListarPedidosParaInformeParams) ([]ListarPedidosParaInformeRow, error) {
	rows, err := q.db.Query(ctx, listarPedidosParaInforme,
		arg.Sucursal,
		arg.Desde,
		arg.Hasta,
		arg.VehiculoID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarPedidosParaInformeRow
	for rows.Next() {
		var i ListarPedidosParaInformeRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerName,
			&i.Address,
			&i.EndAddress,
			&i.Weight,
			&i.Ingreso,
			&i.SegmentKm,
			&i.CreatedAt,
			&i.RutaNombre,
			&i.VehiculoID,
			&i.VehiculoNombre,
			&i.VehiculoMatricula,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPedidosPorFuente = `-- name: ListarPedidosPorFuente :many
SELECT o.id, o.weight, o.external_id
FROM orders o
WHERE o.source = $1::procedencia
ORDER BY o.created_at ASC
`

type ListarPedidosPorFuenteRow struct {
	ID         uuid.UUID `json:"id"`
	Weight     float64   `json:"weight"`
	ExternalID *string   `json:"external_id"`
}

// Los pedidos de una procedencia, para el repaso de pesos. Sin alcance: es de servicio.
func (q *Queries) ListarPedidosPorFuente(ctx context.Context, source Procedencia) ([]ListarPedidosPorFuenteRow, error) {
	rows, err := q.db.Query(ctx, listarPedidosPorFuente, source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarPedidosPorFuenteRow
	for rows.Next() {
		var i ListarPedidosPorFuenteRow
		if err := rows.Scan(&i.ID, &i.Weight, &i.ExternalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarRenglonesDePedido = `-- name: ListarRenglonesDePedido :many
SELECT oi.id, oi.order_id, oi.linea, oi.description, oi.quantity, oi.packs,
       oi.product_id, oi.updated_at
FROM order_items oi
JOIN orders o ON o.id = oi.order_id
WHERE oi.order_id = $1
  AND ($2::uuid IS NULL OR o.branch_id = $2::uuid)
ORDER BY oi.linea ASC
`

type ListarRenglonesDePedidoParams struct {
	PedidoID uuid.UUID   `json:"pedido_id"`
	Sucursal pgtype.UUID `json:"sucursal"`
}

type ListarRenglonesDePedidoRow struct {
	ID          uuid.UUID          `json:"id"`
	OrderID     uuid.UUID          `json:"order_id"`
	Linea       int32              `json:"linea"`
	Description string             `json:"description"`
	Quantity    float64            `json:"quantity"`
	Packs       *float64           `json:"packs"`
	ProductID   pgtype.UUID        `json:"product_id"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Los renglones de UN pedido, en el orden del papel del vendedor. `linea` no es decorativa:
// la hoja del despacho tiene que salir igual que lo que el vendedor escribió.
//
// El JOIN contra `orders` está SÓLO para poder acotar por sucursal: `order_items` no tiene
// `branch_id` y sin él bastaría con acertar un uuid de pedido para leer qué mercancía
// lleva un cliente de otra sucursal. El id del pedido llega de fuera; no se da por bueno.
func (q *Queries) ListarRenglonesDePedido(ctx context.Context, arg ListarRenglonesDePedidoParams) ([]ListarRenglonesDePedidoRow, error) {
	rows, err := q.db.Query(ctx, listarRenglonesDePedido, arg.PedidoID, arg.Sucursal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarRenglonesDePedidoRow
	for rows.Next() {
		var i ListarRenglonesDePedidoRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Linea,
			&i.Description,
			&i.Quantity,
			&i.Packs,
			&i.ProductID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarRenglonesDePedidos = `-- name: ListarRenglonesDePedidos :many
SELECT oi.id, oi.order_id, oi.linea, oi.description, oi.quantity, oi.packs,
       oi.product_id, oi.updated_at
FROM order_items oi
JOIN orders o ON o.id = oi.order_id
WHERE oi.order_id = ANY($1::uuid[])
  AND ($2::uuid IS NULL OR o.branch_id = $2::uuid)
ORDER BY oi.order_id, oi.linea ASC
`

type ListarRenglonesDePedidosParams struct {
	PedidoIds []uuid.UUID `json:"pedido_ids"`
	Sucursal  pgtype.UUID `json:"sucursal"`
}

type ListarRenglonesDePedidosRow struct {
	ID          uuid.UUID          `json:"id"`
	OrderID     uuid.UUID          `json:"order_id"`
	Linea       int32              `json:"linea"`
	Description string             `json:"description"`
	Quantity    float64            `json:"quantity"`
	Packs       *float64           `json:"packs"`
	ProductID   pgtype.UUID        `json:"product_id"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Los renglones de VARIOS pedidos de una vez. Una sola consulta para toda la página, no
// una por fila: con 200 pedidos en pantalla, lo segundo son 200 idas y vueltas.
// El alcance va aquí también aunque los ids ya vengan de una consulta acotada: si un id se
// cuela desde el cliente, sin este filtro se leerían los renglones de otra sucursal.
func (q *Queries) ListarRenglonesDePedidos(ctx context.Context, arg ListarRenglonesDePedidosParams) ([]ListarRenglonesDePedidosRow, error) {
	rows, err := q.db.Query(ctx, listarRenglonesDePedidos, arg.PedidoIds, arg.Sucursal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarRenglonesDePedidosRow
	for rows.Next() {
		var i ListarRenglonesDePedidosRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Linea,
			&i.Description,
			&i.Quantity,
			&i.Packs,
			&i.ProductID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marcaDeAguaDelEspejo = `-- name: MarcaDeAguaDelEspejo :one
SELECT max(o.pedido_updated_at)::timestamptz AS marca
FROM orders o
WHERE o.source = 'pedido'
  AND ($1::text IS NULL
       OR o.sucursal_codigo = $1::text)
`

// La marca de agua del espejo: `since` de la próxima bajada.
//
// Se DERIVA de los datos y no de un contador aparte a propósito: un contador se adelanta
// si una tanda falla a medias, y entonces el espejo se salta esos pedidos para siempre
// sin dar un solo error.
func (q *Queries) MarcaDeAguaDelEspejo(ctx context.Context, sucursalCodigo *string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, marcaDeAguaDelEspejo, sucursalCodigo)
	var marca pgtype.Timestamptz
	err := row.Scan(&marca)
	return marca, err
}

const obtenerPedido = `-- name: ObtenerPedido :one

SELECT
    o.id, o.operation_number, o.customer_name, o.customer_phone, o.address,
    o.end_address, o.end_lat, o.end_lng, o.lat, o.lng, o.weight, o.status,
    o.trip_leg, o.notes, o.route_id, o.ultima_ruta_id, o.vehicle_id, o.price,
    o.segment_km, o.delivery_price, o.delivery_distance_km, o.branch_id,
    o.source, o.external_id, o.order_date, o.pedido_updated_at, o.estado,
    o.archivado, o.fecha_comprometida, o.requiere_domicilio, o.pedido_costo,
    o.municipio, o.vendedor, o.sucursal_codigo, o.factura_estado,
    o.factura_numero, o.factura_at, o.factura_domicilio, o.factura_corregido_at,
    o.stop_order, o.delivered_at, o.resultado, o.resultado_at, o.resultado_nota,
    o.created_at, o.updated_at,
    r.name  AS ruta_nombre,
    v.name  AS vehiculo_nombre,
    v.plate AS vehiculo_matricula,
    vt.nombre AS vehiculo_tipo
FROM orders o
LEFT JOIN routes        r  ON r.id  = o.route_id
LEFT JOIN vehicles      v  ON v.id  = o.vehicle_id
LEFT JOIN vehicle_types vt ON vt.id = v.vehicle_type_id
WHERE o.id = $1
  AND ($2::uuid IS NULL OR o.branch_id = $2::uuid)
`

type ObtenerPedidoParams struct {
	ID       uuid.UUID   `json:"id"`
	Sucursal pgtype.UUID `json:"sucursal"`
}

type ObtenerPedidoRow struct {
	ID                 uuid.UUID          `json:"id"`
	OperationNumber    *string            `json:"operation_number"`
	CustomerName       string             `json:"customer_name"`
	CustomerPhone      *string            `json:"customer_phone"`
	Address            string             `json:"address"`
	EndAddress         *string            `json:"end_address"`
	EndLat             *float64           `json:"end_lat"`
	EndLng             *float64           `json:"end_lng"`
	Lat                *float64           `json:"lat"`
	Lng                *float64           `json:"lng"`
	Weight             float64            `json:"weight"`
	Status             OrderStatus        `json:"status"`
	TripLeg            TripLeg            `json:"trip_leg"`
	Notes              *string            `json:"notes"`
	RouteID            pgtype.UUID        `json:"route_id"`
	UltimaRutaID       pgtype.UUID        `json:"ultima_ruta_id"`
	VehicleID          pgtype.UUID        `json:"vehicle_id"`
	Price              *float64           `json:"price"`
	SegmentKm          *float64           `json:"segment_km"`
	DeliveryPrice      *float64           `json:"delivery_price"`
	DeliveryDistanceKm *float64           `json:"delivery_distance_km"`
	BranchID           pgtype.UUID        `json:"branch_id"`
	Source             *Procedencia       `json:"source"`
	ExternalID         *string            `json:"external_id"`
	OrderDate          pgtype.Timestamptz `json:"order_date"`
	PedidoUpdatedAt    pgtype.Timestamptz `json:"pedido_updated_at"`
	Estado             *PedidoEstado      `json:"estado"`
	Archivado          bool               `json:"archivado"`
	FechaComprometida  pgtype.Timestamptz `json:"fecha_comprometida"`
	RequiereDomicilio  *bool              `json:"requiere_domicilio"`
	PedidoCosto        *float64           `json:"pedido_costo"`
	Municipio          *string            `json:"municipio"`
	Vendedor           *string            `json:"vendedor"`
	SucursalCodigo     *string            `json:"sucursal_codigo"`
	FacturaEstado      *FacturaEstado     `json:"factura_estado"`
	FacturaNumero      *string            `json:"factura_numero"`
	FacturaAt          pgtype.Timestamptz `json:"factura_at"`
	FacturaDomicilio   *float64           `json:"factura_domicilio"`
	FacturaCorregidoAt pgtype.Timestamptz `json:"factura_corregido_at"`
	StopOrder          *int32             `json:"stop_order"`
	DeliveredAt        pgtype.Timestamptz `json:"delivered_at"`
	Resultado          *StopResult        `json:"resultado"`
	ResultadoAt        pgtype.Timestamptz `json:"resultado_at"`
	ResultadoNota      *string            `json:"resultado_nota"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	RutaNombre         *string            `json:"ruta_nombre"`
	VehiculoNombre     *string            `json:"vehiculo_nombre"`
	VehiculoMatricula  *string            `json:"vehiculo_matricula"`
	VehiculoTipo       *string            `json:"vehiculo_tipo"`
}

// ---------------------------------------------------------------------------
// Un pedido suelto
// ---------------------------------------------------------------------------
func (q *Queries) ObtenerPedido(ctx context.Context, arg ObtenerPedidoParams) (ObtenerPedidoRow, error) {
	row := q.db.QueryRow(ctx, obtenerPedido, arg.ID, arg.Sucursal)
	var i ObtenerPedidoRow
	err := row.Scan(
		&i.ID,
		&i.OperationNumber,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.Address,
		&i.EndAddress,
		&i.EndLat,
		&i.EndLng,
		&i.Lat,
		&i.Lng,
		&i.Weight,
		&i.Status,
		&i.TripLeg,
		&i.Notes,
		&i.RouteID,
		&i.UltimaRutaID,
		&i.VehicleID,
		&i.Price,
		&i.SegmentKm,
		&i.DeliveryPrice,
		&i.DeliveryDistanceKm,
		&i.BranchID,
		&i.Source,
		&i.ExternalID,
		&i.OrderDate,
		&i.PedidoUpdatedAt,
		&i.Estado,
		&i.Archivado,
		&i.FechaComprometida,
		&i.RequiereDomicilio,
		&i.PedidoCosto,
		&i.Municipio,
		&i.Vendedor,
		&i.SucursalCodigo,
		&i.FacturaEstado,
		&i.FacturaNumero,
		&i.FacturaAt,
		&i.FacturaDomicilio,
		&i.FacturaCorregidoAt,
		&i.StopOrder,
		&i.DeliveredAt,
		&i.Resultado,
		&i.ResultadoAt,
		&i.ResultadoNota,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RutaNombre,
		&i.VehiculoNombre,
		&i.VehiculoMatricula,
		&i.VehiculoTipo,
	)
	return i, err
}

const panelPorSucursal = `-- name: PanelPorSucursal :many
SELECT
    o.branch_id,
    b.name    AS sucursal_nombre,
    count(*)  AS pedidos,
    coalesce(sum(o.weight), 0)::double precision AS peso_kg
FROM orders o
LEFT JOIN branches b ON b.id = o.branch_id
WHERE o.route_id IS NULL
  AND o.end_lat IS NOT NULL
  AND o.factura_estado IN ('igual','cambiado')
  AND ($1::uuid IS NULL OR o.branch_id = $1::uuid)
GROUP BY o.branch_id, b.name
ORDER BY pedidos DESC
`

type PanelPorSucursalRow struct {
	BranchID       pgtype.UUID `json:"branch_id"`
	SucursalNombre *string     `json:"sucursal_nombre"`
	Pedidos        int64       `json:"pedidos"`
	PesoKg         float64     `json:"peso_kg"`
}

// El reparto de lo repartible por sucursal. Lo ve quien no tiene alcance —el Super Admin—;
// a quien sí lo tiene le sale una sola fila, que es justo lo correcto.
func (q *Queries) PanelPorSucursal(ctx context.Context, sucursal pgtype.UUID) ([]PanelPorSucursalRow, error) {
	rows, err := q.db.Query(ctx, panelPorSucursal, sucursal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PanelPorSucursalRow
	for rows.Next() {
		var i PanelPorSucursalRow
		if err := rows.Scan(
			&i.BranchID,
			&i.SucursalNombre,
			&i.Pedidos,
			&i.PesoKg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const panelResumen = `-- name: PanelResumen :one

SELECT
    count(*)                                                        AS total_pedidos,
    count(*) FILTER (WHERE o.route_id IS NULL
                       AND o.end_lat IS NOT NULL
                       AND o.factura_estado IN ('igual','cambiado')) AS sin_ruta,
    count(*) FILTER (WHERE o.delivered_at >= $1::timestamptz) AS entregados_hoy,
    coalesce(sum(o.weight) FILTER (WHERE o.route_id IS NULL
                       AND o.end_lat IS NOT NULL
                       AND o.factura_estado IN ('igual','cambiado')), 0)::double precision AS peso_pendiente,
    coalesce(sum(o.pedido_costo), 0)::double precision              AS total_domicilios
FROM orders o
WHERE ($2::uuid IS NULL OR o.branch_id = $2::uuid)
`

type PanelResumenParams struct {
	Hoy      pgtype.Timestamptz `json:"hoy"`
	Sucursal pgtype.UUID        `json:"sucursal"`
}

type PanelResumenRow struct {
	TotalPedidos    int64   `json:"total_pedidos"`
	SinRuta         int64   `json:"sin_ruta"`
	EntregadosHoy   int64   `json:"entregados_hoy"`
	PesoPendiente   float64 `json:"peso_pendiente"`
	TotalDomicilios float64 `json:"total_domicilios"`
}

// ---------------------------------------------------------------------------
// Panel  (GET /api/dashboard)  e informes  (GET /api/reports)
// ---------------------------------------------------------------------------
// Los siete números del panel en UNA consulta.
//
// REPARTIBLE es el mismo listón del armador de rutas —sin ruta, con coordenadas y con
// factura que se puede llevar—: si el panel contara otra cosa, diría «40 por repartir» y
// el armador ofrecería 12, y la respuesta correcta sería «ninguno de los dos».
func (q *Queries) PanelResumen(ctx context.Context, arg PanelResumenParams) (PanelResumenRow, error) {
	row := q.db.QueryRow(ctx, panelResumen, arg.Hoy, arg.Sucursal)
	var i PanelResumenRow
	err := row.Scan(
		&i.TotalPedidos,
		&i.SinRuta,
		&i.EntregadosHoy,
		&i.PesoPendiente,
		&i.TotalDomicilios,
	)
	return i, err
}

const pedidosQueSalieronDelAlcance = `-- name: PedidosQueSalieronDelAlcance :many
SELECT f.order_id, f.branch_id, f.motivo, f.salio_at
FROM orders_fuera_de_alcance f
WHERE ($1::timestamptz IS NULL OR f.salio_at >  $1::timestamptz)
  AND ($2::timestamptz IS NULL OR f.salio_at <= $2::timestamptz)
  -- El alcance primero, como siempre: aunque quien llama pida otra sucursal, sólo puede
  -- enterarse de lo que se fue de la suya.
  AND ($3::uuid  IS NULL OR f.branch_id = $3::uuid)
  AND ($4::uuid IS NULL OR f.branch_id = $4::uuid)
  AND (
      $3::uuid  IS NOT NULL
      OR $4::uuid IS NOT NULL
      OR f.motivo = 'borrado'
  )
ORDER BY f.salio_at ASC, f.order_id ASC
LIMIT $5
`

type PedidosQueSalieronDelAlcanceParams struct {
	Desde    pgtype.Timestamptz `json:"desde"`
	Hasta    pgtype.Timestamptz `json:"hasta"`
	Sucursal pgtype.UUID        `json:"sucursal"`
	BranchID pgtype.UUID        `json:"branch_id"`
	Tope     int32              `json:"tope"`
}

type PedidosQueSalieronDelAlcanceRow struct {
	OrderID  uuid.UUID          `json:"order_id"`
	BranchID pgtype.UUID        `json:"branch_id"`
	Motivo   SalidaDePedido     `json:"motivo"`
	SalioAt  pgtype.Timestamptz `json:"salio_at"`
}

// LO QUE SE FUE DE LA SUCURSAL, para `quitados`.
//
// `quitados` no es sólo lo borrado, y por eso esta consulta no mira `orders`: mira las
// lápidas de 00003_bajada_pedidos.sql. Un pedido borrado ya no tiene fila que consultar, y
// uno que se mudó de sucursal tiene la suya intacta pero con OTRA sucursal, así que no
// sale en ninguna consulta acotada a la vieja. En los dos casos el aparato se quedaría con
// él para siempre: la lista local sólo crece.
//
// EL ARCHIVADO NO ESTÁ AQUÍ y no se le olvidó a nadie: su fila sigue existiendo, con el
// `updated_at` movido, así que sale por `DiferenciasDePedidos` y quien contesta la bajada
// lo manda a `quitados` al ver `archivado`. Ponerlo también aquí sería mandarlo dos veces.
//
// Y SIN SUCURSAL —el Super Admin, que ve las ocho— sólo cuentan los BORRADOS: un pedido
// que se mudó de Santiago a Holguín no se le ha ido de la vista, y mandárselo en
// `quitados` le borraría del aparato un pedido que existe y que está en su lista.
func (q *Queries) PedidosQueSalieronDelAlcance(ctx context.Context, arg PedidosQueSalieronDelAlcanceParams) ([]PedidosQueSalieronDelAlcanceRow, error) {
	rows, err := q.db.Query(ctx, pedidosQueSalieronDelAlcance,
		arg.Desde,
		arg.Hasta,
		arg.Sucursal,
		arg.BranchID,
		arg.Tope,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PedidosQueSalieronDelAlcanceRow
	for rows.Next() {
		var i PedidosQueSalieronDelAlcanceRow
		if err := rows.Scan(
			&i.OrderID,
			&i.BranchID,
			&i.Motivo,
			&i.SalioAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pesosDelCatalogoPorFuente = `-- name: PesosDelCatalogoPorFuente :many
SELECT
    o.id,
    o.weight AS peso_guardado,
    coalesce(sum(coalesce(p.weight, 0) * oi.quantity), 0)::double precision AS peso_catalogo
FROM orders o
LEFT JOIN order_items oi ON oi.order_id = o.id
LEFT JOIN products    p  ON p.id = oi.product_id
WHERE o.source = $1::procedencia
GROUP BY o.id, o.weight
ORDER BY o.created_at ASC
`

type PesosDelCatalogoPorFuenteRow struct {
	ID           uuid.UUID `json:"id"`
	PesoGuardado float64   `json:"peso_guardado"`
	PesoCatalogo float64   `json:"peso_catalogo"`
}

// El peso que le TOCA a cada pedido según el catálogo, junto al que tiene guardado.
//
// POR QUÉ SE SUMA EN LA BASE Y NO EN GO: el repaso es sobre el espejo ENTERO —decenas de
// miles de pedidos y sus renglones—, y traérselo todo para multiplicar y sumar es cargar
// el espejo en la memoria del proceso para devolver dos números por fila.
//
// El peso sale de `products.weight`, que es el mismo dato con el que PEDIDO cotiza. El
// `pesoLineaKg` que venía dentro del JSON de `items` YA NO EXISTE: era una copia, y una
// copia acaba discrepando del catálogo que la originó.
//
// El LEFT JOIN a `order_items` es a propósito: un pedido SIN renglones tiene que salir
// igual, con peso calculado 0. Si se cayera de la lista, `totalOrders` diría menos
// pedidos de los que hay y nadie sabría cuáles faltan.
func (q *Queries) PesosDelCatalogoPorFuente(ctx context.Context, source Procedencia) ([]PesosDelCatalogoPorFuenteRow, error) {
	rows, err := q.db.Query(ctx, pesosDelCatalogoPorFuente, source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PesosDelCatalogoPorFuenteRow
	for rows.Next() {
		var i PesosDelCatalogoPorFuenteRow
		if err := rows.Scan(&i.ID, &i.PesoGuardado, &i.PesoCatalogo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renglonesSinPesoPorFuente = `-- name: RenglonesSinPesoPorFuente :many
SELECT
    (coalesce(nullif(btrim(oi.description), ''), '(sin nombre)'))::text AS nombre,
    count(*) AS veces
FROM order_items oi
JOIN orders o        ON o.id = oi.order_id
LEFT JOIN products p ON p.id = oi.product_id
WHERE o.source = $1::procedencia
  AND coalesce(p.weight, 0) <= 0
GROUP BY 1
ORDER BY veces DESC, nombre ASC
`

type RenglonesSinPesoPorFuenteRow struct {
	Nombre string `json:"nombre"`
	Veces  int64  `json:"veces"`
}

// Los renglones que el catálogo NO sabe pesar, contados por nombre. Es la lista que hay
// que llevarle a quien mantiene el catálogo de Ventra: sin ella, `ordersSinPeso` dice que
// hay un problema pero no dice de qué producto.
//
// `(sin nombre)` literal para el renglón con la descripción en blanco: agruparlos bajo la
// cadena vacía deja una fila sin etiqueta en la pantalla que nadie sabe leer.
func (q *Queries) RenglonesSinPesoPorFuente(ctx context.Context, source Procedencia) ([]RenglonesSinPesoPorFuenteRow, error) {
	rows, err := q.db.Query(ctx, renglonesSinPesoPorFuente, source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenglonesSinPesoPorFuenteRow
	for rows.Next() {
		var i RenglonesSinPesoPorFuenteRow
		if err := rows.Scan(&i.Nombre, &i.Veces); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resumenPreDespacho = `-- name: ResumenPreDespacho :many

SELECT
    btrim(oi.description) AS producto,
    sum(CASE WHEN oi.packs > 0 THEN oi.packs ELSE oi.quantity END) AS formatos,
    sum(oi.quantity)                                               AS unidades,
    round(sum(coalesce(p.weight, 0) * oi.quantity)::numeric, 2)     AS peso_kg
FROM order_items oi
JOIN orders o        ON o.id = oi.order_id
LEFT JOIN products p ON p.id = oi.product_id
WHERE btrim(oi.description) <> ''
  AND o.id = ANY($1::uuid[])
  AND ($2::uuid IS NULL OR o.branch_id = $2::uuid)
GROUP BY btrim(oi.description)
ORDER BY formatos DESC, producto ASC
`

type ResumenPreDespachoParams struct {
	PedidoIds []uuid.UUID `json:"pedido_ids"`
	Sucursal  pgtype.UUID `json:"sucursal"`
}

type ResumenPreDespachoRow struct {
	Producto string         `json:"producto"`
	Formatos int64          `json:"formatos"`
	Unidades int64          `json:"unidades"`
	PesoKg   pgtype.Numeric `json:"peso_kg"`
}

// ---------------------------------------------------------------------------
// Pre-despacho: qué mercancía hay que sacar del almacén
// ---------------------------------------------------------------------------
// La cuenta de lo que hay que preparar, agrupada por nombre de renglón.
//
// `formatos` son los bultos y son la unidad con la que se carga y se cuenta un camión;
// cuando el renglón no los trae se cae a las unidades, porque es lo que hay y cero sería
// mentira. El peso sale ahora del catálogo (`products.weight`), que es el mismo dato con
// el que PEDIDO cotiza: el `pesoLineaKg` que venía dentro del JSON de `items` ya no existe.
func (q *Queries) ResumenPreDespacho(ctx context.Context, arg ResumenPreDespachoParams) ([]ResumenPreDespachoRow, error) {
	rows, err := q.db.Query(ctx, resumenPreDespacho, arg.PedidoIds, arg.Sucursal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResumenPreDespachoRow
	for rows.Next() {
		var i ResumenPreDespachoRow
		if err := rows.Scan(
			&i.Producto,
			&i.Formatos,
			&i.Unidades,
			&i.PesoKg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
