// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const actualizarProducto = `-- name: ActualizarProducto :one

UPDATE products SET
    name              = coalesce($1::text, name),
    weight            = coalesce($2::double precision, weight),
    packaging         = CASE WHEN $3::boolean
                             THEN $4::text ELSE packaging END,
    units_per_package = CASE WHEN $5::boolean
                             THEN $6::double precision
                             ELSE units_per_package END,
    category          = CASE WHEN $7::boolean
                             THEN $8::text ELSE category END
WHERE id = $9
RETURNING id, name, weight, packaging, units_per_package, category, sku,
          sucursal_codigo, price, stock, unit, traido_at, updated_at
`

type ActualizarProductoParams struct {
	Name            *string   `json:"name"`
	Weight          *float64  `json:"weight"`
	TocarPackaging  bool      `json:"tocar_packaging"`
	Packaging       *string   `json:"packaging"`
	TocarUnits      bool      `json:"tocar_units"`
	UnitsPerPackage *float64  `json:"units_per_package"`
	TocarCategory   bool      `json:"tocar_category"`
	Category        *string   `json:"category"`
	ID              uuid.UUID `json:"id"`
}

type ActualizarProductoRow struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Weight          float64            `json:"weight"`
	Packaging       *string            `json:"packaging"`
	UnitsPerPackage *float64           `json:"units_per_package"`
	Category        *string            `json:"category"`
	Sku             *string            `json:"sku"`
	SucursalCodigo  *string            `json:"sucursal_codigo"`
	Price           *float64           `json:"price"`
	Stock           *float64           `json:"stock"`
	Unit            *string            `json:"unit"`
	TraidoAt        pgtype.Timestamptz `json:"traido_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// ---------------------------------------------------------------------------
// Correcciones del catálogo  (sólo Super Admin, sin alcance: es de toda la empresa)
// ---------------------------------------------------------------------------
// Lo que se puede corregir a mano es sólo lo que Ventra no da bien: el peso, el envase y
// la categoría. Ni el precio ni las existencias, que son de Ventra y se vuelven a pisar en
// la siguiente pasada; dejarlos editar es prometer un cambio que dura doce horas.
func (q *Queries) ActualizarProducto(ctx context.Context, arg ActualizarProductoParams) (ActualizarProductoRow, error) {
	row := q.db.QueryRow(ctx, actualizarProducto,
		arg.Name,
		arg.Weight,
		arg.TocarPackaging,
		arg.Packaging,
		arg.TocarUnits,
		arg.UnitsPerPackage,
		arg.TocarCategory,
		arg.Category,
		arg.ID,
	)
	var i ActualizarProductoRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Weight,
		&i.Packaging,
		&i.UnitsPerPackage,
		&i.Category,
		&i.Sku,
		&i.SucursalCodigo,
		&i.Price,
		&i.Stock,
		&i.Unit,
		&i.TraidoAt,
		&i.UpdatedAt,
	)
	return i, err
}

const borrarProducto = `-- name: BorrarProducto :execrows
DELETE FROM products WHERE id = $1
`

func (q *Queries) BorrarProducto(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, borrarProducto, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const buscarProductoPorSku = `-- name: BuscarProductoPorSku :one
SELECT p.id, p.name, p.weight, p.sku, p.sucursal_codigo, p.price, p.stock, p.unit
FROM products p
WHERE p.sucursal_codigo = $1
  AND p.sku = $2
`

type BuscarProductoPorSkuParams struct {
	SucursalCodigo *string `json:"sucursal_codigo"`
	Sku            *string `json:"sku"`
}

type BuscarProductoPorSkuRow struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	Weight         float64   `json:"weight"`
	Sku            *string   `json:"sku"`
	SucursalCodigo *string   `json:"sucursal_codigo"`
	Price          *float64  `json:"price"`
	Stock          *float64  `json:"stock"`
	Unit           *string   `json:"unit"`
}

// Emparejar un renglón de pedido con el catálogo de SU sucursal. El `sku` sólo es único
// dentro de una sucursal —la clave de la tabla es (`sucursal_codigo`, `sku`)—, así que
// buscarlo sin ella devuelve el precio y las existencias de donde no toca.
func (q *Queries) BuscarProductoPorSku(ctx context.Context, arg BuscarProductoPorSkuParams) (BuscarProductoPorSkuRow, error) {
	row := q.db.QueryRow(ctx, buscarProductoPorSku, arg.SucursalCodigo, arg.Sku)
	var i BuscarProductoPorSkuRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Weight,
		&i.Sku,
		&i.SucursalCodigo,
		&i.Price,
		&i.Stock,
		&i.Unit,
	)
	return i, err
}

const guardarProductoDelCatalogo = `-- name: GuardarProductoDelCatalogo :one

INSERT INTO products (
    name, weight, packaging, units_per_package, category, sku,
    sucursal_codigo, price, stock, unit, traido_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, now()
)
ON CONFLICT (sucursal_codigo, sku) DO UPDATE SET
    name              = excluded.name,
    weight            = excluded.weight,
    packaging         = excluded.packaging,
    units_per_package = excluded.units_per_package,
    category          = excluded.category,
    price             = excluded.price,
    stock             = excluded.stock,
    unit              = excluded.unit,
    traido_at         = excluded.traido_at
RETURNING id, name, sku, sucursal_codigo, traido_at
`

type GuardarProductoDelCatalogoParams struct {
	Name            string   `json:"name"`
	Weight          float64  `json:"weight"`
	Packaging       *string  `json:"packaging"`
	UnitsPerPackage *float64 `json:"units_per_package"`
	Category        *string  `json:"category"`
	Sku             *string  `json:"sku"`
	SucursalCodigo  *string  `json:"sucursal_codigo"`
	Price           *float64 `json:"price"`
	Stock           *float64 `json:"stock"`
	Unit            *string  `json:"unit"`
}

type GuardarProductoDelCatalogoRow struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	Sku            *string            `json:"sku"`
	SucursalCodigo *string            `json:"sucursal_codigo"`
	TraidoAt       pgtype.Timestamptz `json:"traido_at"`
}

// ---------------------------------------------------------------------------
// Bajada del catálogo  (POST /api/products/sync)
// ---------------------------------------------------------------------------
// Upsert por (`sucursal_codigo`, `sku`), que es la única clave de verdad: es por el código
// de Ventra como se reconoce una fila entre pasadas. Aquí SÍ hay `ON CONFLICT` porque el
// esquema declara esa pareja como UNIQUE.
//
// Lo que NO se hace: borrar lo que deja de venir. Media lista por un corte de VPN no debe
// vaciar el catálogo de una sucursal — lo viejo se nota por `traido_at`, que dice si lo
// que se está mirando es de hace diez minutos o de hace tres días.
func (q *Queries) GuardarProductoDelCatalogo(ctx context.Context, arg GuardarProductoDelCatalogoParams) (GuardarProductoDelCatalogoRow, error) {
	row := q.db.QueryRow(ctx, guardarProductoDelCatalogo,
		arg.Name,
		arg.Weight,
		arg.Packaging,
		arg.UnitsPerPackage,
		arg.Category,
		arg.Sku,
		arg.SucursalCodigo,
		arg.Price,
		arg.Stock,
		arg.Unit,
	)
	var i GuardarProductoDelCatalogoRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.SucursalCodigo,
		&i.TraidoAt,
	)
	return i, err
}

const listarProductos = `-- name: ListarProductos :many


SELECT
    p.id, p.name, p.weight, p.packaging, p.units_per_package, p.category,
    p.sku, p.sucursal_codigo, p.price, p.stock, p.unit, p.traido_at,
    p.created_at, p.updated_at
FROM products p
WHERE
    ($1::text IS NULL OR p.sucursal_codigo = $1::text)
    AND (
        $2::text IS NULL
        OR p.name     ILIKE '%' || $2::text || '%'
        OR p.category ILIKE '%' || $2::text || '%'
        OR p.sku      ILIKE '%' || $2::text || '%'
    )
    AND lower(btrim(coalesce(p.category, ''))) NOT IN ('serv', 'servicio', 'servicios')
    AND lower(coalesce(p.name, '')) NOT LIKE '%entrega a domicilio%'
    AND lower(coalesce(p.name, '')) NOT LIKE '%servicio de entrega%'
ORDER BY p.name ASC
LIMIT $4 OFFSET $3
`

type ListarProductosParams struct {
	Sucursal       *string `json:"sucursal"`
	Q              *string `json:"q"`
	Desplazamiento int32   `json:"desplazamiento"`
	Limite         int32   `json:"limite"`
}

// Catálogo. Se llena solo: PEDIDO sondea Ventra y aquí se copia lo que él ya tiene.
// No hay alta manual — dos catálogos escritos por separado discrepan sin que nadie lo vea.
//
// EL ALCANCE VA POR CÓDIGO DE SUCURSAL, igual que en clientes: `products` no tiene
// `branch_id`, tiene `sucursal_codigo`. Y tiene que llevarlo: en Ventra el precio y las
// existencias VARÍAN por sucursal, así que un catálogo único ofrece en Camagüey un
// producto que sólo hay en La Habana, y al precio de La Habana.
//
// Quien llama traduce su sucursal a `branches.external_id` y lo pasa en `sucursal`.
// A diferencia de clientes, aquí NO se dejan pasar las filas sin código: un producto sin
// sucursal no tiene ni precio ni existencias de ningún sitio.
// ---------------------------------------------------------------------------
// El catálogo de una sucursal  (GET /api/products)
// ---------------------------------------------------------------------------
// Los productos que se pueden cargar en un camión, de la sucursal que toque.
//
// SE EXCLUYEN LAS LÍNEAS DE SERVICIO. En el catálogo de Ventra conviven los productos con
// líneas como «ENTREGA A DOMICILIO» —categoría `SERV`, peso cero—: no es algo que se
// carga, es el propio cobro del reparto facturado como una línea más. Salía en el buscador
// con «0 kg» al lado y alguien la iba a elegir tarde o temprano; un pedido con esa línea
// dentro pesa lo mismo que sin ella y encima cobra el reparto DOS VECES, una en la línea y
// otra en el domicilio. La misma regla vive en PEDIDO y las dos tienen que estar de
// acuerdo en qué es mercancía.
//
// Se compara la frase entera: con «entrega» a secas, cualquier producto que la mencionara
// desaparecería del catálogo y nadie sabría por qué.
// El OFFSET es para la bajada del aparato: el catálogo se sirve por tandas y la
// siguiente tiene que empezar donde acabó la anterior. Sin él, `truncado` sería una
// promesa que no se puede cumplir — el aparato vuelve a pedir y recibe lo mismo.
func (q *Queries) ListarProductos(ctx context.Context, arg ListarProductosParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listarProductos,
		arg.Sucursal,
		arg.Q,
		arg.Desplazamiento,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Weight,
			&i.Packaging,
			&i.UnitsPerPackage,
			&i.Category,
			&i.Sku,
			&i.SucursalCodigo,
			&i.Price,
			&i.Stock,
			&i.Unit,
			&i.TraidoAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerProducto = `-- name: ObtenerProducto :one
SELECT
    p.id, p.name, p.weight, p.packaging, p.units_per_package, p.category,
    p.sku, p.sucursal_codigo, p.price, p.stock, p.unit, p.traido_at,
    p.created_at, p.updated_at
FROM products p
WHERE p.id = $1
`

func (q *Queries) ObtenerProducto(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, obtenerProducto, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Weight,
		&i.Packaging,
		&i.UnitsPerPackage,
		&i.Category,
		&i.Sku,
		&i.SucursalCodigo,
		&i.Price,
		&i.Stock,
		&i.Unit,
		&i.TraidoAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const obtenerProductoDelAlcance = `-- name: ObtenerProductoDelAlcance :one

SELECT
    p.id, p.name, p.weight, p.packaging, p.units_per_package, p.category,
    p.sku, p.sucursal_codigo, p.price, p.stock, p.unit, p.traido_at,
    p.created_at, p.updated_at
FROM products p
WHERE p.id = $1
  AND ($2::text IS NULL OR p.sucursal_codigo = $2::text)
`

type ObtenerProductoDelAlcanceParams struct {
	ID       uuid.UUID `json:"id"`
	Sucursal *string   `json:"sucursal"`
}

// ---------------------------------------------------------------------------
// Un producto suelto, ACOTADO  (GET /api/products/[id])
// ---------------------------------------------------------------------------
// El mismo producto que `ObtenerProducto`, pero filtrado por el código de la sucursal.
//
// POR QUÉ HAY DOS. `ObtenerProducto` va sin alcance a propósito: es la que usan las
// correcciones del Super Admin, que son de toda la empresa. Ésta es la de la PANTALLA, y
// ahí enseñar el producto de otra sucursal no es sólo un fallo de permisos: el PRECIO y
// las EXISTENCIAS son por sucursal, así que una ficha de La Habana abierta desde Camagüey
// lleva un precio que en Camagüey no se cobra y unas existencias que allí no hay. Eso se
// copia en un pedido y no lo desmiente nadie hasta que llega la factura.
//
// NULL en `sucursal` = todas (Super Admin sin sucursal elegida).
func (q *Queries) ObtenerProductoDelAlcance(ctx context.Context, arg ObtenerProductoDelAlcanceParams) (Product, error) {
	row := q.db.QueryRow(ctx, obtenerProductoDelAlcance, arg.ID, arg.Sucursal)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Weight,
		&i.Packaging,
		&i.UnitsPerPackage,
		&i.Category,
		&i.Sku,
		&i.SucursalCodigo,
		&i.Price,
		&i.Stock,
		&i.Unit,
		&i.TraidoAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const usoDeProductos = `-- name: UsoDeProductos :many
SELECT oi.product_id, sum(oi.quantity)::double precision AS unidades
FROM order_items oi
WHERE oi.product_id IS NOT NULL
  AND oi.order_id IN (
      SELECT o.id FROM orders o
      WHERE ($1::uuid IS NULL OR o.branch_id = $1::uuid)
      ORDER BY o.created_at DESC
      LIMIT $2
  )
GROUP BY oi.product_id
`

type UsoDeProductosParams struct {
	Sucursal         pgtype.UUID `json:"sucursal"`
	PedidosRecientes int32       `json:"pedidos_recientes"`
}

type UsoDeProductosRow struct {
	ProductID pgtype.UUID `json:"product_id"`
	Unidades  float64     `json:"unidades"`
}

// Cuánto se ha pedido de cada producto últimamente, para ordenar el buscador por lo que la
// gente usa de verdad y no por orden alfabético.
//
// Se cuenta sobre los últimos N pedidos DEL ALCANCE, no sobre todo el histórico: lo que se
// movía hace ocho meses no dice nada de lo que hay que tener a mano hoy. El tope lo pone
// el llamante para que la cuenta no crezca sola con la base.
func (q *Queries) UsoDeProductos(ctx context.Context, arg UsoDeProductosParams) ([]UsoDeProductosRow, error) {
	rows, err := q.db.Query(ctx, usoDeProductos, arg.Sucursal, arg.PedidosRecientes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsoDeProductosRow
	for rows.Next() {
		var i UsoDeProductosRow
		if err := rows.Scan(&i.ProductID, &i.Unidades); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
