// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Hacer sitio antes de soltar una tarjeta EN MEDIO de una columna: todo lo que esté de esa
	// posición para abajo se corre uno. En un solo `UPDATE` —y por eso la única es DEFERRABLE—
	// porque a mitad del corrimiento hay dos filas con la misma posición.
	AbrirHuecoEnColumna(ctx context.Context, arg AbrirHuecoEnColumnaParams) (int64, error)
	// `cup_rate_updated_at` se mueve SÓLO cuando cambia la tasa, no en cada guardado: es lo
	// que dice si el número que se está usando es de hoy o de hace tres semanas, y tocarlo por
	// guardar la moneda lo convertiría en una copia de `updated_at`, que ya existe.
	ActualizarAjustes(ctx context.Context, arg ActualizarAjustesParams) (Setting, error)
	// Renombrar y elegir camión. `tocar_vehiculo` existe porque «no me lo toques» y «quítamelo»
	// son dos órdenes distintas y las dos llegan con el campo vacío: sin la bandera, dejar el
	// nombre en blanco desasignaría el camión de paso.
	ActualizarColumna(ctx context.Context, arg ActualizarColumnaParams) (BoardColumn, error)
	// ---------------------------------------------------------------------------
	// Cambios de estado de la ruta  (PATCH /api/routes/[id])
	// ---------------------------------------------------------------------------
	// Nombre y estado, con las horas de salida y regreso.
	//
	// `started_at` sólo se pone la PRIMERA vez que arranca: volver a marcar `in_progress`
	// después de una corrección no debe reescribir la hora de salida, que es con la que se
	// mide cuánto se demoró. `finished_at` se limpia al arrancar de nuevo por lo mismo.
	// Ninguna de las dos se deduce de `created_at` —la ruta se arma la noche anterior— ni de
	// `updated_at`, que se mueve al tocar cualquier cosa.
	ActualizarEstadoDeRuta(ctx context.Context, arg ActualizarEstadoDeRutaParams) (ActualizarEstadoDeRutaRow, error)
	// Corregir un punto de partida ya guardado (PATCH /api/origins/[id]).
	//
	// `branch_id` NO SE PUEDE CAMBIAR AQUÍ, y no es un olvido: mover un origen de sucursal
	// por un PATCH es exactamente la forma de plantar un punto de partida en la sucursal de
	// otro —el mismo agujero que ya se tapó en el alta, donde la sucursal la pone el alcance y
	// no el cuerpo—. Para llevarlo a otra sucursal se borra y se crea allí, que además deja
	// constancia de quién lo hizo.
	//
	// `coalesce` y no `CASE WHEN tocar_*`: aquí ninguno de los cuatro campos admite NULL en el
	// esquema, así que «mandarlo vacío» no existe y el tri-estado no hace falta.
	ActualizarOrigen(ctx context.Context, arg ActualizarOrigenParams) (SavedOrigin, error)
	// ---------------------------------------------------------------------------
	// Escrituras del catálogo
	// ---------------------------------------------------------------------------
	// PATCH de un pedido a mano. `coalesce` deja pasar sólo lo que viene: lo que no se manda
	// no se pisa con NULL. `delivered_at` se pone solo al marcar `delivered` — no se le pide
	// al cliente que lo mande, que es como acaban dos pedidos con la misma hora de entrega.
	ActualizarPedido(ctx context.Context, arg ActualizarPedidoParams) (ActualizarPedidoRow, error)
	// Recalcular el peso desde el catálogo (POST /api/orders/recompute-weights). Va sin
	// alcance a propósito: es una faena de servicio sobre todo el espejo, con clave de API.
	ActualizarPesoDePedido(ctx context.Context, arg ActualizarPesoDePedidoParams) error
	// ---------------------------------------------------------------------------
	// Correcciones del catálogo  (sólo Super Admin, sin alcance: es de toda la empresa)
	// ---------------------------------------------------------------------------
	// Lo que se puede corregir a mano es sólo lo que Ventra no da bien: el peso, el envase y
	// la categoría. Ni el precio ni las existencias, que son de Ventra y se vuelven a pisar en
	// la siguiente pasada; dejarlos editar es prometer un cambio que dura doce horas.
	ActualizarProducto(ctx context.Context, arg ActualizarProductoParams) (ActualizarProductoRow, error)
	// Tocar lat o lng da el punto de partida por configurado: si alguien se molestó en
	// ponerle coordenadas, ya está fijado.
	ActualizarSucursal(ctx context.Context, arg ActualizarSucursalParams) (Branch, error)
	ActualizarTipoDeVehiculo(ctx context.Context, arg ActualizarTipoDeVehiculoParams) (VehicleType, error)
	ActualizarVehiculo(ctx context.Context, arg ActualizarVehiculoParams) (Vehicle, error)
	// ---------------------------------------------------------------------------
	// Asignación de varios camiones a un pedido
	// ---------------------------------------------------------------------------
	// El INSERT va con SELECT y no con VALUES para poder acotar por sucursal: `order_vehicles`
	// no tiene `branch_id`, así que la única forma de comprobar el alcance es preguntarle al
	// pedido. Con VALUES, el id del pedido entra tal cual desde el cliente y un camión de
	// Holguín acaba colgado de un pedido de La Habana. Cero filas es el 404.
	AsignarVehiculoAPedido(ctx context.Context, arg AsignarVehiculoAPedidoParams) (AsignarVehiculoAPedidoRow, error)
	// Cuántas tarjetas puestas ya no se pueden repartir. Es el aviso de arriba del tablero:
	// «3 de los que tienes puestos ya no salen». Se cuenta en la base porque la pantalla no
	// tiene todas las tarjetas cargadas y un aviso que sólo aparece si has bajado hasta la
	// columna de abajo no es un aviso.
	//
	// Los tres se cuentan por separado a propósito: «lo archivaron en PEDIDO», «se lo llevó
	// otra ruta» y «no está facturado» se arreglan de tres maneras distintas, y un número
	// único obligaría a abrir las doce columnas para saber cuál de las tres es.
	AvisosDelTablero(ctx context.Context, arg AvisosDelTableroParams) (AvisosDelTableroRow, error)
	BorrarAsignacionesDeVehiculo(ctx context.Context, vehiculoID uuid.UUID) (int64, error)
	// Los que ya no vienen de PEDIDO: borrados allá, o dejaron de tener coordenadas.
	//
	// SÓLO los de `source = 'pedido'`. El alta MANUAL del reparto no tiene origen ni id
	// externo, y llevársela por delante sería borrar un cliente que nadie puede recuperar
	// porque no está en ningún otro sitio.
	//
	// Quien llame tiene que haber recorrido TODAS las páginas de PEDIDO antes: con media
	// lista —un corte de la VPN a mitad del recorrido— esto vacía el espejo entero y el
	// logístico se queda sin a quién repartir, con un 200 y sin un solo error.
	BorrarClientesDelEspejoQueYaNoVienen(ctx context.Context, arg BorrarClientesDelEspejoQueYaNoVienenParams) (int64, error)
	// Con `ON DELETE RESTRICT` en las colocaciones, esto falla si la columna tiene algo dentro.
	// Es lo que se quiere: borrar una columna con pedidos puestos no puede ser silencioso, y
	// quien llama ya sabe —por `ContarPedidosEnColumna`— qué tiene que decirle a la persona.
	BorrarColumna(ctx context.Context, arg BorrarColumnaParams) (int64, error)
	BorrarOrigen(ctx context.Context, arg BorrarOrigenParams) (int64, error)
	// :execrows y no :exec: cero filas es «no existe O no es de tu sucursal», que es el 404.
	// Con :exec no hay forma de distinguirlo de un borrado hecho.
	BorrarPedido(ctx context.Context, arg BorrarPedidoParams) (int64, error)
	BorrarProducto(ctx context.Context, id uuid.UUID) (int64, error)
	// Los renglones se reescriben enteros en cada pasada del espejo: PEDIDO puede haber
	// quitado una línea, y un UPDATE línea a línea dejaría la vieja colgada. Se borran y se
	// vuelven a poner dentro de la MISMA transacción que el upsert de arriba.
	BorrarRenglonesDePedido(ctx context.Context, pedidoID uuid.UUID) error
	BorrarRuta(ctx context.Context, arg BorrarRutaParams) (int64, error)
	BorrarSucursal(ctx context.Context, arg BorrarSucursalParams) (int64, error)
	// Sólo se puede borrar de verdad un tipo que no use nadie. Se comprueba aquí, en la misma
	// sentencia, y no con un conteo antes: entre el conteo y el borrado cabe un alta.
	BorrarTipoDeVehiculoSinUso(ctx context.Context, id uuid.UUID) (int64, error)
	BorrarVehiculo(ctx context.Context, arg BorrarVehiculoParams) (int64, error)
	// Emparejar un renglón de pedido con el catálogo de SU sucursal. El `sku` sólo es único
	// dentro de una sucursal —la clave de la tabla es (`sucursal_codigo`, `sku`)—, así que
	// buscarlo sin ella devuelve el precio y las existencias de donde no toca.
	BuscarProductoPorSku(ctx context.Context, arg BuscarProductoPorSkuParams) (BuscarProductoPorSkuRow, error)
	// La sucursal por su código de PEDIDO/Ventra (CAM, HAB, STG...). Es por lo que PEDIDO
	// cotiza: manda su código y aquí se busca la nuestra.
	BuscarSucursalPorCodigo(ctx context.Context, externalID *string) (BuscarSucursalPorCodigoRow, error)
	// Por nombre, para el espejo y para el alta de vehículos: el cuerpo del POST manda
	// `type: "truck"`, un texto, y hay que traducirlo al id del catálogo. `nombre` es UNIQUE.
	BuscarTipoDeVehiculoPorNombre(ctx context.Context, nombre string) (BuscarTipoDeVehiculoPorNombreRow, error)
	// Ocupar y liberar el camión. El vehículo se marca `in_use` al DESPACHAR la ruta (pasarla
	// a `in_progress`), no al armarla: entre que se arma la noche anterior y sale por la
	// mañana, el camión sigue disponible para otra cosa.
	CambiarEstadoDeVehiculo(ctx context.Context, arg CambiarEstadoDeVehiculoParams) (int64, error)
	// Cambiar el camión. Va aparte del cambio de estado porque en el contrato tiene prioridad
	// y retorna antes: liberar el camión viejo y ocupar el nuevo es lo único que hace.
	CambiarVehiculoDeRuta(ctx context.Context, arg CambiarVehiculoDeRutaParams) (CambiarVehiculoDeRutaRow, error)
	// Cerrar el hueco que dejó una tarjeta al salir. Se hace DESPUÉS de sacarla, y si no se
	// hiciera tampoco se rompería nada —el orden se lee, no se cuenta—, pero las posiciones se
	// irían separando hasta que un día alguien las lea como «la parada número 47» de una
	// columna de nueve.
	CerrarHuecoEnColumna(ctx context.Context, arg CerrarHuecoEnColumnaParams) (int64, error)
	// Los códigos a los que esta persona puede llegar. Es lo que filtra la respuesta de
	// Accesos en `/api/almacenes`: Accesos devuelve las ocho sucursales y aquí se descartan
	// las que no le tocan. Sólo las que TIENEN código: sin él no hay nada que cotejar.
	CodigosDeSucursalesVisibles(ctx context.Context, sucursal pgtype.UUID) ([]CodigosDeSucursalesVisiblesRow, error)
	// ---------------------------------------------------------------------------
	// La tasa de cambio de cada sucursal  (`internal/api/refresco_de_tasas.go`)
	// ---------------------------------------------------------------------------
	// A quién hay que preguntarle la tasa: las sucursales que TIENEN código, que es por lo
	// que Accesos las conoce. Sin código no hay nada que preguntar.
	//
	// SIN ALCANCE, y no es un descuido: esto lo llama una tarea de fondo, que no es una
	// persona y no mira por nadie. Acotarla dejaría sin tasa a las siete sucursales que no
	// fueran la del último que entró.
	CodigosParaRefrescarLaTasa(ctx context.Context) ([]CodigosParaRefrescarLaTasaRow, error)
	// ---------------------------------------------------------------------------
	// Arrastrar  (PUT /api/board/placements/[pedidoId])
	// ---------------------------------------------------------------------------
	// Colocar un pedido en una columna, o moverlo de sitio. Es la MISMA orden: soltar una
	// tarjeta en una columna es decir «este pedido va aquí», venga de donde venga.
	//
	// Cinco cosas van juntas en una sola sentencia y ninguna se puede comprobar antes en Go
	// sobre una lectura que ya puede estar vieja:
	//
	//  1. El pedido y la columna tienen que ser de la MISMA sucursal. Es la comprobación que
	//     ninguna clave ajena puede hacer, porque son dos tablas distintas.
	//  2. `o.route_id IS NULL`: un pedido que ya va en un camión no se coloca. Cero filas es
	//     ese rechazo, y es el mismo instante en el que se comprueba — con diez logísticos y un
	//     Super Admin armando rutas a la vez, entre pintar la lista y soltar la tarjeta pasan
	//     cosas de verdad.
	//  3. El alcance, que aquí es seguridad: sin él, mandar el id de una columna ajena mete tu
	//     pedido en el tablero de otra sucursal.
	//  4. `ON CONFLICT (order_id)`: mover es actualizar la fila que ya hay. Sin esto habría que
	//     borrar y volver a insertar, y entre las dos el pedido no está en ninguna parte.
	//  5. `colocado_at` se refresca al mover: es cuándo quedó donde está ahora.
	//
	// La condición de `factura_estado` NO está: un pedido colocado que deja de ser repartible
	// se queda puesto y marcado (ver `ListarPedidosColocados`), así que volver a colocarlo
	// tampoco se prohíbe. Lo que no puede salir es la RUTA, y eso lo corta el armador.
	ColocarPedido(ctx context.Context, arg ColocarPedidoParams) (BoardPlacement, error)
	// Al liberar un camión a mano se cierra la ruta que llevaba: un camión disponible con una
	// ruta abierta detrás es una ruta que nadie va a cerrar nunca y que sigue contando como
	// activa en el panel.
	CompletarRutasDeVehiculo(ctx context.Context, arg CompletarRutasDeVehiculoParams) (int64, error)
	// El total, con el MISMO where. Es el `total` de la respuesta: se cuenta antes del filtro
	// de distancia exacto, igual que en el contrato, y por eso puede ser mayor que `count`.
	ContarClientes(ctx context.Context, arg ContarClientesParams) (int64, error)
	// Cuántos no tienen a quién llamar. Es un aviso de calidad del espejo, no un filtro más:
	// un cliente sin teléfono es una entrega que, si falla, no se puede avisar.
	ContarClientesSinTelefono(ctx context.Context, sucursalDelAlcance *string) (int64, error)
	// ¿Tiene ya algún punto de partida? Se pregunta al crear o al corregir una sucursal con
	// coordenadas: si no tiene ninguno se le crea el de por defecto. Una sucursal con
	// coordenadas y sin origen no puede armar una ruta y no lo dice en ninguna parte.
	ContarOrigenesDeSucursal(ctx context.Context, sucursalID pgtype.UUID) (int64, error)
	// El total del catálogo, para la paginación. Mismo WHERE que `ListarPedidos`.
	ContarPedidos(ctx context.Context, arg ContarPedidosParams) (int64, error)
	// El `total` de la pantalla de disponibles: el mismo WHERE, sin tope ni orden.
	// Tiene que ser EL MISMO o el contador dice una cosa y la tabla otra.
	ContarPedidosDisponibles(ctx context.Context, arg ContarPedidosDisponiblesParams) (int64, error)
	// Cuántas tarjetas tiene dentro. Se pregunta ANTES de borrarla, para poder decir «tiene 8
	// pedidos puestos» en vez de devolver el error de clave ajena de Postgres, que no lo
	// entiende nadie.
	ContarPedidosEnColumna(ctx context.Context, arg ContarPedidosEnColumnaParams) (int64, error)
	// El contador de la mitad izquierda: el MISMO `WHERE`, sin tope ni orden. Tiene que ser el
	// mismo o dice «358» encima de una lista de 120.
	ContarPedidosSinColocar(ctx context.Context, arg ContarPedidosSinColocarParams) (int64, error)
	// ---------------------------------------------------------------------------
	// Para el panel y para la flota
	// ---------------------------------------------------------------------------
	// Rutas vivas. `cancelled` se excluye igual que `completed` aunque hoy nadie lo escriba:
	// el enum lo tiene declarado para no obligar a un ALTER TYPE el día que se use, y el
	// tablero ya lo descarta.
	ContarRutasActivas(ctx context.Context, sucursal pgtype.UUID) (int64, error)
	// Cuántas rutas se llevan hoy, para el `NNN` de `RT-YYYYMMDD-NNN`.
	//
	// OJO: no es atómico. Dos armados a la vez leen el mismo número y salen con el mismo
	// código. Delivery tenía la misma carrera; se hereda tal cual para no cambiar el formato
	// del código, que es lo que la gente se dice por teléfono. Si empieza a chocar, la salida
	// es una secuencia por día, no un reintento.
	ContarRutasDelDia(ctx context.Context, prefijo string) (int64, error)
	// ---------------------------------------------------------------------------
	// Panel
	// ---------------------------------------------------------------------------
	ContarVehiculos(ctx context.Context, sucursal pgtype.UUID) (int64, error)
	// Camiones que están fuera ahora mismo: los que llevan una ruta sin cerrar. Se mira la
	// ruta y no `vehicles.status` porque el estado es un campo que alguien puede haber dejado
	// a mano en `available` con la ruta todavía abierta.
	ContarVehiculosEnRuta(ctx context.Context, sucursal pgtype.UUID) (int64, error)
	// La posición se calcula aquí y no la manda la pantalla: una columna nueva va al final,
	// siempre, y dejar que el cliente proponga el número es dejar que dos aparatos sin
	// conexión propongan el mismo.
	//
	// El `FROM branches` no es decorativo: valida que la sucursal EXISTA. Sin él, un
	// `branch_id` viejo —los tokens duran siete días y las sucursales se recrearon— crearía
	// columnas en un tablero al que no llega nadie.
	CrearColumna(ctx context.Context, arg CrearColumnaParams) (BoardColumn, error)
	CrearOrigen(ctx context.Context, arg CrearOrigenParams) (SavedOrigin, error)
	CrearRenglonDePedido(ctx context.Context, arg CrearRenglonDePedidoParams) (CrearRenglonDePedidoRow, error)
	// La ruta nace `planned` y `optimized` en false: los totales y el orden de visita se
	// calculan después, con las paradas ya enganchadas, y se fijan con `FijarTotalesDeRuta`.
	//
	// `creado_por` es el id de la persona EN AUTH y es CONSTANCIA, no un filtro: aquí nada
	// pertenece a nadie. Filtrar por el creador fue lo que dejó los 3.528 pedidos importados a
	// nombre del Super Admin y escondió los de Holguín a sus propios compañeros de Holguín.
	CrearRuta(ctx context.Context, arg CrearRutaParams) (CrearRutaRow, error)
	// `origin_configured` nace en true al darla de alta con coordenadas: el alta ya fija el
	// punto de partida. Mientras sea false, el cálculo de domicilios NO corre para esa
	// sucursal, y eso es deliberado — medir desde un punto que no es el almacén da un precio
	// que parece bueno y no lo es.
	CrearSucursal(ctx context.Context, arg CrearSucursalParams) (Branch, error)
	// El costo por km del tipo es un VALOR POR DEFECTO, no el bueno: cada vehículo puede tener
	// el suyo porque quien lo da es el camionero y dos camiones del mismo tipo no cuestan
	// igual. Se deja vacío a propósito en los cuatro que vienen de fábrica — ponerle un número
	// inventado es peor que no tenerlo, porque se cobra igual y nadie lo revisa.
	CrearTipoDeVehiculo(ctx context.Context, arg CrearTipoDeVehiculoParams) (VehicleType, error)
	// ---------------------------------------------------------------------------
	// Altas y cambios
	// ---------------------------------------------------------------------------
	// El vehículo nace en la sucursal del alcance. Quien no tiene alcance —el Super Admin—
	// puede dejarlo sin sucursal, que significa «de todas».
	//
	// `costo_km_usd` puede quedar vacío: lo pone el camionero, y dos camiones del mismo tipo
	// no cuestan igual. Vacío quiere decir «usa el del tipo», no «cero».
	CrearVehiculo(ctx context.Context, arg CrearVehiculoParams) (Vehicle, error)
	// Retirar una moneda es desactivarla, no borrarla: los importes ya guardados se
	// convirtieron con su tasa y sin la fila no hay forma de volver a explicarlos.
	DesactivarMoneda(ctx context.Context, code string) (int64, error)
	// Sólo un vehículo de referencia por sucursal, y lo impide el índice único parcial
	// `vehicles_una_referencia_por_sucursal`. Por eso hay que DESMARCAR a los demás antes de
	// marcar el nuevo, y las dos cosas dentro de la MISMA transacción: si no, el INSERT choca
	// contra el índice.
	//
	// HUECO CONOCIDO: los vehículos sin sucursal (`branch_id` NULL) se escapan del índice,
	// porque en un índice único los NULL son distintos entre sí. Puede haber dos de referencia
	// «de todas». Se cierra con `NULLS NOT DISTINCT` el día que estorbe.
	DesmarcarReferenciaDeDomicilio(ctx context.Context, arg DesmarcarReferenciaDeDomicilioParams) (int64, error)
	// ---------------------------------------------------------------------------
	// Borrado
	// ---------------------------------------------------------------------------
	//
	// Antes de borrar hay que desasociar: rutas (`DesvincularVehiculoDeRutas`, en routes.sql),
	// pedidos y asignaciones. El histórico de lo que se repartió no se borra porque un camión
	// se dé de baja.
	DesvincularVehiculoDePedidos(ctx context.Context, arg DesvincularVehiculoDePedidosParams) (int64, error)
	// Al borrar un camión, sus rutas se quedan sin él pero no se borran: el histórico de lo
	// que se repartió no depende de que el camión siga en la flota.
	DesvincularVehiculoDeRutas(ctx context.Context, arg DesvincularVehiculoDeRutasParams) (int64, error)
	// Cuántas líneas hay por día, para ver de un vistazo qué días están bajados y cuáles no.
	// Un día que falta no sale como cero: sale como que no está, y eso es lo correcto — un
	// cero inventado se lee como «ese día no se vendió nada».
	DiasConFacturacion(ctx context.Context, arg DiasConFacturacionParams) ([]DiasConFacturacionRow, error)
	// ---------------------------------------------------------------------------
	// La bajada del aparato  (GET /api/sync/cambios, colección `orders`)
	// ---------------------------------------------------------------------------
	// LO QUE CAMBIÓ DESDE UNA MARCA, en una sucursal. Es la consulta que faltaba y sin la
	// cual el trabajo sin conexión no existe: el logístico se baja los pedidos por la mañana
	// y los prepara todo el día sin red.
	//
	// `cambiado_at` NO ES `o.updated_at`, y ésa es la razón de ser de esta consulta.
	//
	//   Es el más nuevo de los dos: el del pedido y el de sus renglones. Si cambia un renglón
	//   —PEDIDO reescribe las líneas con lo que dijo la factura— el pedido NO se toca, así que
	//   su `updated_at` se queda quieto y el pedido no saldría en las diferencias. El aparato
	//   se quedaría con la lista de mercancía vieja y el camión cargaría lo que ya no es.
	//   Por eso el renglón arrastra a su pedido.
	//
	//   Y es también LA MARCA QUE SE DEVUELVE: el aparato la guarda y con ella pide la
	//   siguiente vez. Devolver `o.updated_at` y filtrar por el otro sería darle una marca
	//   atrasada con la que volvería a bajarse lo mismo una y otra vez.
	//
	// EL `desde` ES ESTRICTO (`>`) y el `hasta` INCLUSIVO (`<=`): así dos bajadas seguidas
	// —`(a,b]` y `(b,c]`— no se pisan ni dejan un hueco en `b`.
	//
	// LOS ARCHIVADOS ENTRAN CON INTERRUPTOR, `con_archivados`:
	//   * En la carga inicial va en false. Un pedido archivado hace ocho meses no tiene por
	//     qué bajarse: el aparato empieza vacío y no hay nada que quitarle. Con true, el tope
	//     se lo comerían los archivados del histórico y lo del día no cabría.
	//   * En las diferencias va en true, porque archivar es justamente lo que hay que
	//     contarle al aparato para que lo BORRE. Quien contesta la bajada mira `archivado` y
	//     lo manda a `quitados`.
	//
	// Las dos sucursales del WHERE son las de la casa: `sucursal` es el alcance, que lo pone
	// `internal/alcance` y no se puede pasar desde fuera, y `branch_id` es la que pide quien
	// llama. Van en AND: la segunda estrecha, nunca amplía.
	// POR LA MARCA Y HACIA ADELANTE, que es lo que hace que el tope no pierda nada: lo que no
	// cabe en esta tanda se pide en la siguiente con la marca de la última fila servida. Con
	// cualquier otro orden, «los 2.000 primeros» son 2.000 cualesquiera y el resto no vuelve.
	// El `id` desempata para que dos tandas iguales salgan iguales.
	DiferenciasDePedidos(ctx context.Context, arg DiferenciasDePedidosParams) ([]DiferenciasDePedidosRow, error)
	// Engancha un pedido a la ruta como parada número `stop_order`.
	//
	// `route_id` y `ultima_ruta_id` se ponen los DOS y valen lo mismo hoy: el primero dice
	// «está ocupado» y el segundo «en qué camión fue». Son dos preguntas distintas y con un
	// solo campo no se pueden responder las dos.
	//
	// `segment_km` es la distancia RADIAL desde el origen, no la del tramo del recorrido: se
	// hereda así de delivery porque es el número con el que se repartió la carga hasta hoy.
	// `price` es ese reparto de carga y NO el costo del domicilio, que es `pedido_costo`.
	//
	// El alcance va aquí también: sin él, mandar el id de un pedido de otra sucursal en
	// `orderIds` lo subiría a tu camión.
	EngancharPedidoARuta(ctx context.Context, arg EngancharPedidoARutaParams) (int64, error)
	// ---------------------------------------------------------------------------
	// Facetas de clientes
	// ---------------------------------------------------------------------------
	//
	// Se calculan sobre TODO el alcance y SIN los filtros de búsqueda, a propósito: los
	// desplegables tienen que seguir ofreciendo a dónde ir después de filtrar. Si se
	// recalcularan con la búsqueda puesta, cada filtro dejaría los demás con una sola opción
	// —la ya elegida— y no habría forma de cambiar de idea sin borrarlo todo.
	FacetasClientesMunicipios(ctx context.Context, sucursalDelAlcance *string) ([]FacetasClientesMunicipiosRow, error)
	FacetasClientesSucursales(ctx context.Context, sucursalDelAlcance *string) ([]FacetasClientesSucursalesRow, error)
	FacetasClientesVendedores(ctx context.Context, sucursalDelAlcance *string) ([]FacetasClientesVendedoresRow, error)
	FacetasClientesZonas(ctx context.Context, sucursalDelAlcance *string) ([]FacetasClientesZonasRow, error)
	// ---------------------------------------------------------------------------
	// Facetas del catálogo  (GET /api/orders/facetas)
	// ---------------------------------------------------------------------------
	// Los municipios que EXISTEN de verdad en lo que esta persona puede ver, para llenar el
	// desplegable. Si se sacaran de una lista fija, ofrecería municipios sin un solo pedido.
	FacetasMunicipios(ctx context.Context, sucursal pgtype.UUID) ([]FacetasMunicipiosRow, error)
	// Las sucursales con pedidos. El nombre se compone aquí —«Nombre (COD)»— porque es lo que
	// la gente reconoce: el código a secas no dice nada y el nombre solo se repite.
	FacetasSucursales(ctx context.Context, sucursal pgtype.UUID) ([]FacetasSucursalesRow, error)
	FacetasVendedores(ctx context.Context, sucursal pgtype.UUID) ([]FacetasVendedoresRow, error)
	// Por dónde va el barrido del histórico, en DÍAS HACIA ATRÁS.
	//
	// Hace falta guardarlo porque de los datos NO se puede deducir: hay pedidos viejos
	// sueltos, así que «el más antiguo que tengo» no significa «tengo todo hasta ahí».
	FijarBarridoDelEspejo(ctx context.Context, syncBarridoDia int32) error
	// Los totales, ya con las paradas puestas y el recorrido calculado.
	// `total_distance` es el CIRCUITO CERRADO: los tramos más el regreso al origen. El camión
	// vuelve, y no contar la vuelta subestima el viaje justo a la mitad de las rutas largas.
	FijarTotalesDeRuta(ctx context.Context, arg FijarTotalesDeRutaParams) (FijarTotalesDeRutaRow, error)
	// Idempotencia del espejo: `source` + `external_id` es lo que reconoce a un cliente entre
	// pasadas. Sin alcance — el espejo entra con clave de servicio y trae las ocho sucursales.
	//
	// UNA SOLA CONSULTA CON `ON CONFLICT`, como en pedidos: `customers_origen_idx` es ÚNICO
	// parcial, y con buscar-y-escribir dos pasadas a la vez crean el mismo cliente dos veces
	// —las dos leen «no existe» antes de que ninguna escriba—. El `WHERE` repite el del índice
	// parcial porque si no Postgres no sabe qué índice inferir.
	//
	// `synced_at` es «cuándo lo trajo el origen» y NO es `updated_at`, que lo mueve el trigger
	// al tocar la fila. Confundirlas rompe el espejo: la segunda cambia aunque el dato de
	// Ventra sea de hace tres días porque la VPN lleva caída desde el lunes.
	GuardarClienteDelEspejo(ctx context.Context, arg GuardarClienteDelEspejoParams) (GuardarClienteDelEspejoRow, error)
	// Una moneda se corrige sola, sin reescribir la lista entera. Eso es lo que la tabla
	// compra frente al array de JSON que había antes: se puede saber cuándo cambió cada tasa
	// —`updated_at`, que lo mantiene el trigger— y corregir una sin tocar las demás.
	GuardarMoneda(ctx context.Context, arg GuardarMonedaParams) (Currency, error)
	// ---------------------------------------------------------------------------
	// El espejo de PEDIDO  (POST /api/quote/batch)
	// ---------------------------------------------------------------------------
	// Alta o actualización idempotente por (`source`, `external_id`): volver a pasar el mismo
	// lote no duplica. Va sin alcance porque el espejo entra con clave de servicio y trae las
	// ocho sucursales de una vez; la sucursal de cada pedido la decide el propio lote.
	//
	// POR QUÉ UNA SOLA CONSULTA CON `ON CONFLICT` Y NO BUSCAR-Y-ESCRIBIR: `orders_origen_idx`
	// es un índice ÚNICO parcial (ver la migración). Con buscar-y-escribir, dos pasadas del
	// espejo a la vez leen «no existe» antes de que ninguna escriba y crean el mismo pedido
	// DOS VECES — y entonces sale dos veces en la lista del armador, con el mismo folio, y
	// alguien lo carga dos veces en el camión. Con el upsert la carrera la resuelve Postgres.
	//
	// El `WHERE` del `ON CONFLICT` repite el del índice parcial: sin él Postgres no sabe qué
	// índice inferir y rechaza la consulta al ejecutarla.
	//
	// LO QUE NO SE PISA NUNCA al actualizar: `route_id`, `ultima_ruta_id`, `stop_order`,
	// `resultado`, `resultado_nota` y `delivered_at`. Eso es del reparto y PEDIDO no sabe nada
	// de ello: dejarlo entrar borraría de un plumazo el resultado de una parada ya cerrada,
	// que es justo el dato que dice qué mercancía bajó del camión.
	//
	// `xmax = 0` es el truco de Postgres para saber si la fila se INSERTÓ o se ACTUALIZÓ: en
	// una fila recién insertada el id de la transacción que la borró todavía es cero. Hace
	// falta para poder decir en el registro cuántos pedidos son nuevos sin una consulta más.
	GuardarPedidoDelEspejo(ctx context.Context, arg GuardarPedidoDelEspejoParams) (GuardarPedidoDelEspejoRow, error)
	// ---------------------------------------------------------------------------
	// Bajada del catálogo  (POST /api/products/sync)
	// ---------------------------------------------------------------------------
	// Upsert por (`sucursal_codigo`, `sku`), que es la única clave de verdad: es por el código
	// de Ventra como se reconoce una fila entre pasadas. Aquí SÍ hay `ON CONFLICT` porque el
	// esquema declara esa pareja como UNIQUE.
	//
	// Lo que NO se hace: borrar lo que deja de venir. Media lista por un corte de VPN no debe
	// vaciar el catálogo de una sucursal — lo viejo se nota por `traido_at`, que dice si lo
	// que se está mirando es de hace diez minutos o de hace tres días.
	GuardarProductoDelCatalogo(ctx context.Context, arg GuardarProductoDelCatalogoParams) (GuardarProductoDelCatalogoRow, error)
	// Guardar la tasa que vino de Accesos, por CÓDIGO de sucursal.
	//
	// DOS COSAS QUE NO SE VEN VENIR, las dos en el WHERE:
	//
	//  1. **Sólo escribe si algo cambió** (`IS DISTINCT FROM`). El disparador
	//     `trg_branches_updated` mueve `updated_at` en CADA update, y `updated_at` es lo que
	//     decide qué entra en la bajada por diferencias. Sin esta guarda, el refresco de cada
	//     hora haría que las ocho sucursales bajaran otra vez a todos los aparatos aunque la
	//     tasa fuera la misma — y, peor, `updatedAt` diría que la sucursal cambió cuando no
	//     cambió nada.
	//  2. **NUNCA borra una tasa que ya había.** Sólo se llama con una tasa de verdad: el
	//     «esta sucursal no tiene» de Accesos no escribe NULL aquí. Ver el porqué entero en
	//     `refresco_de_tasas.go`; en dos líneas: si un tropiezo de Accesos borrara la tasa
	//     guardada, el aparato que está en la calle se quedaría sin poder ver CUP con una
	//     tasa que sigue siendo buena, y la fecha que va al lado ya cuenta lo vieja que es.
	GuardarTasaDeSucursal(ctx context.Context, arg GuardarTasaDeSucursalParams) (int64, error)
	// Alta o actualización por `ventra_id`, que es el id de la LÍNEA en Ventra y por el que se
	// reconoce entre pasadas. Aquí sí hay `ON CONFLICT`: el esquema lo declara UNIQUE.
	//
	// Va sin alcance: la bajada entra con clave de servicio y recorre las ocho sucursales.
	GuardarVentaFacturada(ctx context.Context, arg GuardarVentaFacturadaParams) (GuardarVentaFacturadaRow, error)
	// Clientes: espejo de Ventra vía PEDIDO. Sólo los GEOLOCALIZADOS — sin coordenadas no se
	// cotiza y no hay parada que visitar.
	//
	// EL ALCANCE AQUÍ VA POR CÓDIGO, NO POR `branch_id`.
	//
	// `customers` no tiene `branch_id`: tiene `sucursal_codigo`, que es el código de Ventra
	// (CAM, HAB, STG...). Quien llama traduce su sucursal a código —`branches.external_id`—
	// y lo pasa en `sucursal_del_alcance`. El filtro deja pasar además los clientes SIN
	// código: son los que no vinieron de ninguna sucursal concreta, y esconderlos haría
	// desaparecer clientes que sí se atienden, sin decir nada.
	//
	// Si la sucursal del alcance NO tiene `external_id`, el llamante debe pasar NULL aquí:
	// pasar el uuid de la sucursal como si fuera un código no da error, da CERO CLIENTES.
	// ---------------------------------------------------------------------------
	// La lista  (GET /api/customers)
	// ---------------------------------------------------------------------------
	// La página de clientes con todos sus filtros.
	//
	// El filtro por distancia va en DOS pasos y sólo el primero está aquí: la CAJA
	// (`lat`/`lng` entre unos grados) es lo único que un índice puede resolver. La distancia
	// exacta se calcula después, sólo sobre las 50 filas de la página. Meter el haversine en
	// el WHERE obliga a recorrer los siete mil clientes fila a fila en cada búsqueda.
	// Los grados vienen ya calculados de Go: `km/111` en latitud y `km/(111*cos(lat))` en
	// longitud, que es donde el meridiano se estrecha.
	ListarClientes(ctx context.Context, arg ListarClientesParams) ([]ListarClientesRow, error)
	// El tablero de preparación: las columnas de la sucursal, lo que hay puesto en cada una y
	// los pedidos que faltan por colocar, ordenados por cercanía al almacén.
	//
	// Especificado en ../../../docs/tablero.md. Las tablas, en 00002_tablero.sql.
	//
	// EL ALCANCE VA EN EL SQL, igual que en `routes.sql`, y por lo mismo: si el filtro se
	// hiciera en Go después de leer, la columna de otra sucursal ya habría salido de la base, y
	// un `DELETE ... WHERE id = $1` a secas borra el tablero de quien sea.
	// `sqlc.narg('sucursal')` es el parámetro «todas las sucursales»: NULL = no acota.
	//
	// Y ADEMÁS DE ESO, UN `branch_id` OBLIGATORIO en las lecturas del tablero. No es
	// redundante y no sobra: **no existe «el tablero de todas»**. Las columnas son de una
	// sucursal, y la cercanía se mide desde el almacén de UNA sucursal — con diez mezcladas, el
	// «más cercano primero» sale midiendo Holguín desde Santiago. El Super Admin, que no tiene
	// alcance, tiene que elegir cuál está mirando. Es el mismo par de parámetros de
	// `ListarPedidosDisponibles`: el alcance manda y el `branch_id` estrecha, nunca amplía.
	// ---------------------------------------------------------------------------
	// Las columnas  (GET /api/board/columns)
	// ---------------------------------------------------------------------------
	// El tablero entero por arriba: cada columna con lo que lleva dentro.
	//
	// Los totales vienen de la base y no de sumar las tarjetas en la pantalla, porque la
	// pantalla pagina y el camión no: con 60 pedidos puestos, sumar lo pintado da el peso de
	// los 20 primeros y el aviso de que no cabe no aparece nunca.
	//
	// `excede_camion` se calcula contra la capacidad del vehículo PREVISTO, leída del vehículo
	// y no copiada en la columna. Sin camión previsto es NULL, que no es `false`: significa que
	// todavía no se sabe, y pintar «cabe» cuando nadie ha dicho en qué va es peor que no
	// pintar nada.
	ListarColumnasDelTablero(ctx context.Context, arg ListarColumnasDelTableroParams) ([]ListarColumnasDelTableroRow, error)
	// ---------------------------------------------------------------------------
	// Monedas
	// ---------------------------------------------------------------------------
	// `rate` son unidades de esta moneda por 1 USD: CUP = 320, no al revés. Escrito al revés,
	// todos los importes salen divididos por cien mil y parecen céntimos.
	ListarMonedas(ctx context.Context, soloActivas *bool) ([]Currency, error)
	// ---------------------------------------------------------------------------
	// Puntos de partida guardados  (/api/origins)
	// ---------------------------------------------------------------------------
	// Los orígenes desde los que se puede armar una ruta.
	//
	// Con alcance se ven los de la sucursal; sin alcance, o todos o los de la que se pida.
	// Los orígenes SIN sucursal no se cuelan en el alcance de nadie: un punto de partida
	// suelto en la lista de Holguín es una ruta que empieza a 800 km de donde debía.
	ListarOrigenes(ctx context.Context, sucursal pgtype.UUID) ([]ListarOrigenesRow, error)
	// Las paradas, en el orden en que el camión las visita.
	//
	// Va por `route_id`: es la hoja del camión de HOY, lo que lleva cargado ahora mismo.
	ListarParadasDeRuta(ctx context.Context, arg ListarParadasDeRutaParams) ([]ListarParadasDeRutaRow, error)
	// Las paradas de VARIAS rutas de una vez, para el tablero.
	//
	// Existe para no repetir `ListarParadasDeRuta` una vez por ruta: el tablero sale sin
	// filtro de fecha y con un año de trabajo son cientos de rutas, o sea cientos de idas y
	// vueltas a la base para pintar UNA pantalla. Con un array de ids son tres consultas
	// fijas: las rutas, sus paradas y sus renglones.
	//
	// Va por `route_id` —lo que el camión lleva cargado— igual que la de una sola.
	ListarParadasDeRutas(ctx context.Context, arg ListarParadasDeRutasParams) ([]ListarParadasDeRutasRow, error)
	// Las paradas que VIAJARON en esta ruta, se hayan bajado del camión o no.
	//
	// Va por `ultima_ruta_id`, que no se libera nunca, y por eso son dos campos y no uno: un
	// devuelto suelta su `route_id` al cerrar la ruta para poder repartirse mañana, y con un
	// solo campo eso lo borraría de la hoja de lo que bajó del camión. Es el universo del
	// post-despacho y el de corregir el resultado de una parada ya cerrada.
	ListarParadasQueViajaronEnRuta(ctx context.Context, arg ListarParadasQueViajaronEnRutaParams) ([]ListarParadasQueViajaronEnRutaRow, error)
	// ---------------------------------------------------------------------------
	// El catálogo de pedidos  (GET /api/orders)
	// ---------------------------------------------------------------------------
	// La lista paginada, con su ruta y su sucursal. Mismos filtros que los disponibles —tienen
	// que significar lo MISMO en las dos pantallas o los números no cuadran y nadie sabe cuál
	// creerse—, pero SIN las cinco condiciones fijas: aquí se ve todo el histórico.
	ListarPedidos(ctx context.Context, arg ListarPedidosParams) ([]ListarPedidosRow, error)
	// ---------------------------------------------------------------------------
	// Las tarjetas puestas  (GET /api/board)
	// ---------------------------------------------------------------------------
	// Todo lo colocado en el tablero de una sucursal, en una sola consulta.
	//
	// Una consulta y no una por columna: con doce distritos, lo segundo son doce idas y
	// vueltas para pintar una pantalla que el logístico abre y cierra treinta veces al día, y
	// que además tiene que caber en la conexión de allá.
	//
	// OJO CON LO QUE **NO** LLEVA ESTE `WHERE`: no están las condiciones de «repartible»
	// (`factura_estado`, `route_id IS NULL`). Aquí sale TODO lo que esté puesto, se pueda
	// repartir o no, y por eso se devuelven `factura_estado`, `archivado`, `route_id` y
	// `resultado`: la tarjeta se marca, no se esconde.
	//
	// Quitar sola una tarjeta que dejó de servir es hacer desaparecer el trabajo de alguien sin
	// decírselo; el logístico volvería a la columna, vería once paradas donde puso doce y no
	// tendría manera de saber cuál falta ni por qué.
	ListarPedidosColocados(ctx context.Context, arg ListarPedidosColocadosParams) ([]ListarPedidosColocadosRow, error)
	// Pedidos: el catálogo, los disponibles para repartir, las facetas y el espejo de PEDIDO.
	//
	// CONVENCIÓN DE PARÁMETROS (vale para todos los ficheros de esta carpeta)
	//
	//   El alcance por sucursal es SEGURIDAD y va SIEMPRE en el SQL, nunca en Go. Se expresa
	//   con un solo parámetro que admite «todas las sucursales» como NULL:
	//
	//       (sqlc.narg('sucursal')::uuid IS NULL OR o.branch_id = sqlc.narg('sucursal')::uuid)
	//
	//   `sqlc.narg('sucursal')` ES el `$1` posicional: sqlc lo numera igual, pero además le
	//   pone nombre en el struct de Go. Con doce filtros opcionales, un struct de `Column1..
	//   Column12` es exactamente la forma de colar el municipio en la casilla de la sucursal
	//   sin que el compilador diga nada. El `::uuid` explícito es lo que obliga a sqlc a
	//   generarlo como anulable.
	//
	//   Los demás filtros opcionales siguen el mismo patrón: NULL = no filtra.
	//
	// EL TEXTO DE LOS RENGLONES YA NO SE COPIA. Donde delivery buscaba en `productosTexto`
	// —una copia a mano de los nombres, porque dentro de un JSON no se busca— aquí va un
	// EXISTS contra `order_items`. Un dato copiado en dos sitios acaba discrepando.
	// ---------------------------------------------------------------------------
	// La lista de pedidos por repartir  (GET /api/orders/available)
	// ---------------------------------------------------------------------------
	// ¿Qué pedidos puedo meter HOY en una ruta, de los que yo puedo ver?
	//
	// Las cinco condiciones de arriba del WHERE no son filtros de pantalla y no se negocian:
	//   * `source = 'pedido'`      — lo que no vino de PEDIDO no se reparte.
	//   * `route_id IS NULL`       — si ya va en una ruta, está ocupado.
	//   * `end_lat/end_lng`        — sin coordenadas no hay parada que visitar.
	//   * `factura_estado IN ('igual','cambiado')` — LO REPARTIBLE. `cambiado` no es un pedido
	//     roto: se facturó distinto de como se pidió y lo que sube al camión son las líneas de
	//     la factura. Fuera quedan `sin_factura` (no hay nada que llevar) y el NULL, que
	//     significa NO SE SABE: con un NULL colado se armó una ruta sin facturar el 2/09.
	//
	// `km_max` y `costo_min` NO están aquí a propósito: el contrato los aplica después de la
	// consulta, y `total`/`truncated` se calculan ANTES que ellos. Bajarlos al SQL cambiaría
	// esos dos números y la pantalla diría «358» sobre una tabla de 120.
	ListarPedidosDisponibles(ctx context.Context, arg ListarPedidosDisponiblesParams) ([]ListarPedidosDisponiblesRow, error)
	// El informe. `ingreso` es `price` si lo hay y si no `pedido_costo`: `price` es el reparto
	// de carga de una ruta y `pedido_costo` lo que cobró Entrega; no son lo mismo y cobrar uno
	// por el otro es el error que este COALESCE hace visible en un solo sitio.
	ListarPedidosParaInforme(ctx context.Context, arg ListarPedidosParaInformeParams) ([]ListarPedidosParaInformeRow, error)
	// Los pedidos de una procedencia, para el repaso de pesos. Sin alcance: es de servicio.
	ListarPedidosPorFuente(ctx context.Context, source Procedencia) ([]ListarPedidosPorFuenteRow, error)
	// ---------------------------------------------------------------------------
	// LOS PEDIDOS SIN COLOCAR, ORDENADOS POR CERCANÍA AL ALMACÉN
	// ---------------------------------------------------------------------------
	// La mitad izquierda del tablero, y la razón por la que existe la función `km_haversine`.
	//
	// EL ORDEN ES EL ENCARGO: el más cerca del almacén primero. Es como se decide qué se
	// reparte hoy cuando no cabe todo — lo cerca sale igual, lo lejos espera al día que haya
	// suficiente para ese lado—, y por fecha, que es como sale en `/api/orders/available`, esa
	// decisión no se puede tomar.
	//
	// EL ORIGEN LLEGA POR PARÁMETRO Y NO SALE DE AQUÍ. El almacén vive en Accesos, no en esta
	// base, y se copia a propósito en ninguna parte: un almacén copiado se separa del de verdad
	// en cuanto alguien mueve unas coordenadas allá, y con esas coordenadas se mide el
	// domicilio que se le cobra al cliente. Quien llama resuelve el almacén principal de la
	// sucursal (primero el `principal` con coordenadas; si no, el primero que las tenga) y lo
	// pasa aquí. Sin almacén con coordenadas no hay tablero: se dice que no se puede, no se
	// ordena por un punto inventado.
	//
	// Las condiciones de «repartible» son LAS MISMAS CINCO de `ListarPedidosDisponibles`, ni
	// una más ni una menos. Si el tablero ofreciera algo que el armador luego rechaza, el
	// logístico prepararía una columna entera para que la ruta le diga que no al final del día.
	// El desempate por fecha no es adorno: dos clientes en el mismo edificio dan exactamente
	// los mismos kilómetros, y sin un segundo criterio el orden cambia entre dos llamadas y las
	// tarjetas bailan solas delante de quien las está arrastrando.
	ListarPedidosSinColocar(ctx context.Context, arg ListarPedidosSinColocarParams) ([]ListarPedidosSinColocarRow, error)
	// Catálogo. Se llena solo: PEDIDO sondea Ventra y aquí se copia lo que él ya tiene.
	// No hay alta manual — dos catálogos escritos por separado discrepan sin que nadie lo vea.
	//
	// EL ALCANCE VA POR CÓDIGO DE SUCURSAL, igual que en clientes: `products` no tiene
	// `branch_id`, tiene `sucursal_codigo`. Y tiene que llevarlo: en Ventra el precio y las
	// existencias VARÍAN por sucursal, así que un catálogo único ofrece en Camagüey un
	// producto que sólo hay en La Habana, y al precio de La Habana.
	//
	// Quien llama traduce su sucursal a `branches.external_id` y lo pasa en `sucursal`.
	// A diferencia de clientes, aquí NO se dejan pasar las filas sin código: un producto sin
	// sucursal no tiene ni precio ni existencias de ningún sitio.
	// ---------------------------------------------------------------------------
	// El catálogo de una sucursal  (GET /api/products)
	// ---------------------------------------------------------------------------
	// Los productos que se pueden cargar en un camión, de la sucursal que toque.
	//
	// SE EXCLUYEN LAS LÍNEAS DE SERVICIO. En el catálogo de Ventra conviven los productos con
	// líneas como «ENTREGA A DOMICILIO» —categoría `SERV`, peso cero—: no es algo que se
	// carga, es el propio cobro del reparto facturado como una línea más. Salía en el buscador
	// con «0 kg» al lado y alguien la iba a elegir tarde o temprano; un pedido con esa línea
	// dentro pesa lo mismo que sin ella y encima cobra el reparto DOS VECES, una en la línea y
	// otra en el domicilio. La misma regla vive en PEDIDO y las dos tienen que estar de
	// acuerdo en qué es mercancía.
	//
	// Se compara la frase entera: con «entrega» a secas, cualquier producto que la mencionara
	// desaparecería del catálogo y nadie sabría por qué.
	// El OFFSET es para la bajada del aparato: el catálogo se sirve por tandas y la
	// siguiente tiene que empezar donde acabó la anterior. Sin él, `truncado` sería una
	// promesa que no se puede cumplir — el aparato vuelve a pedir y recibe lo mismo.
	ListarProductos(ctx context.Context, arg ListarProductosParams) ([]Product, error)
	// Los renglones de UN pedido, en el orden del papel del vendedor. `linea` no es decorativa:
	// la hoja del despacho tiene que salir igual que lo que el vendedor escribió.
	//
	// El JOIN contra `orders` está SÓLO para poder acotar por sucursal: `order_items` no tiene
	// `branch_id` y sin él bastaría con acertar un uuid de pedido para leer qué mercancía
	// lleva un cliente de otra sucursal. El id del pedido llega de fuera; no se da por bueno.
	ListarRenglonesDePedido(ctx context.Context, arg ListarRenglonesDePedidoParams) ([]ListarRenglonesDePedidoRow, error)
	// Los renglones de VARIOS pedidos de una vez. Una sola consulta para toda la página, no
	// una por fila: con 200 pedidos en pantalla, lo segundo son 200 idas y vueltas.
	// El alcance va aquí también aunque los ids ya vengan de una consulta acotada: si un id se
	// cuela desde el cliente, sin este filtro se leerían los renglones de otra sucursal.
	ListarRenglonesDePedidos(ctx context.Context, arg ListarRenglonesDePedidosParams) ([]ListarRenglonesDePedidosRow, error)
	// Los renglones de TODAS las paradas de la ruta, de una vez.
	//
	// Es la hoja de carga y la del post-despacho: lo que sube al camión y, al volver, lo que
	// debería seguir arriba. Una sola consulta y no una por parada — con 40 paradas, lo
	// segundo son 40 idas y vueltas por una pantalla que se abre veinte veces al día.
	//
	// Por `ultima_ruta_id` para que el post-despacho siga viendo los renglones de lo que se
	// devolvió: al cerrar, esos pedidos ya soltaron su `route_id`.
	ListarRenglonesDeRuta(ctx context.Context, arg ListarRenglonesDeRutaParams) ([]ListarRenglonesDeRutaRow, error)
	// Los renglones de las paradas de VARIAS rutas, de una vez.
	//
	// Por `route_id` y no por `ultima_ruta_id` a propósito: éstos son los renglones de lo que
	// va EN el camión, que es lo que acompaña a cada parada de la lista. Los de lo que ya se
	// bajó (un devuelto que soltó su `route_id`) son otra pregunta y los trae
	// `ListarRenglonesDeRuta`, que es la del post-despacho.
	ListarRenglonesDeRutas(ctx context.Context, arg ListarRenglonesDeRutasParams) ([]ListarRenglonesDeRutasRow, error)
	// Rutas: el tablero, el detalle con sus paradas y sus renglones, el armado y el cierre.
	//
	// El alcance por sucursal va en el SQL de TODAS, incluidas las escrituras: si el filtro se
	// hiciera en Go después de leer, una ruta de otra sucursal ya habría salido de la base, y
	// un `UPDATE ... WHERE id = $1` a secas cierra la ruta de quien sea.
	// `sqlc.narg('sucursal')` es el parámetro «todas las sucursales»: NULL = no acota.
	// ---------------------------------------------------------------------------
	// El tablero de rutas  (GET /api/routes)
	// ---------------------------------------------------------------------------
	ListarRutas(ctx context.Context, arg ListarRutasParams) ([]ListarRutasRow, error)
	// Sucursales y puntos de partida guardados.
	//
	// OJO, AQUÍ EL ALCANCE ES DISTINTO Y NO ES UN DESCUIDO.
	//
	// En la LISTA de sucursales no se pregunta «qué estoy mirando ahora» sino «a cuáles puedo
	// llegar», que sólo depende de la persona y no de la que tenga elegida arriba. Si se
	// acotara por la elegida, elegir una devolvería una sola, el selector se volvería una
	// etiqueta fija y no habría forma de cambiar a otra: la elección se comería la lista con
	// la que se elige. Por eso el parámetro se llama `sucursal_de_la_persona` y no `sucursal`.
	//
	// Y OTRA COSA QUE TAMPOCO ES UN DESCUIDO: si el id que llega no existe, el llamante pasa
	// NULL y se ven todas. Filtrar por un id inexistente NO da error: da CERO. Cero pedidos,
	// cero clientes, cero rutas y hasta cero sucursales —con lo que desaparece el selector con
	// el que se podría arreglar—, todo con 200 y sin una traza. El token del login único dura
	// siete días y lleva dentro la sucursal que la persona tenía al entrar, y las sucursales
	// se recrearon en algún momento: pasa de verdad, y se vio en producción.
	// ---------------------------------------------------------------------------
	// Sucursales
	// ---------------------------------------------------------------------------
	// Las cuatro columnas de la tasa viajan AQUÍ porque de aquí sale la bajada del aparato
	// (`GET /api/sync/cambios`, colección `branches`). La tasa es un dato DE LA SUCURSAL, y
	// esta aplicación tiene que poder pintar los importes en CUP sin conexión — o sea que la
	// tasa tiene que estar guardada en el aparato como todo lo demás del día.
	ListarSucursales(ctx context.Context, sucursalDeLaPersona pgtype.UUID) ([]ListarSucursalesRow, error)
	// El catálogo de tipos de vehículo — LA TABLA QUE FALTABA.
	//
	// En delivery esto se guardaba en `Settings.tiposVehiculo`, un campo que NUNCA EXISTIÓ en
	// el esquema: la pantalla de vehículos dejaba crear tipos nuevos, los mandaba a guardar y
	// se perdían sin un solo error. Por eso `Vehicle.type` era un conjunto abierto que nadie
	// podía cerrar — su catálogo no estaba en ninguna parte.
	//
	// GLOBAL, sin alcance por sucursal: un «camión» es un camión en las ocho, y la tabla no
	// tiene columna de sucursal que filtrar. Lo que sí es por sucursal es qué VEHÍCULO
	// concreto es el de referencia, y eso vive en `vehicles`.
	// Los tipos que se pueden elegir. Por defecto sólo los activos: `activo` existe para poder
	// RETIRAR un tipo sin romper los vehículos que ya lo usan — borrarlo dejaría la clave
	// ajena colgando y no hay a dónde mover un camión que ya es de ese tipo.
	ListarTiposDeVehiculo(ctx context.Context, soloActivos *bool) ([]ListarTiposDeVehiculoRow, error)
	// La flota.
	//
	// `branch_id` NULL en un vehículo significa «de todas las sucursales», así que el filtro
	// del alcance tiene que dejarlos pasar: un camión compartido que no salga en la lista de
	// nadie es un camión que no se puede usar. Eso es distinto de pedidos y rutas, donde un
	// `branch_id` NULL sería un dato incompleto, no una decisión.
	//
	// NO SE FILTRA POR QUIÉN DIO DE ALTA EL VEHÍCULO. En delivery se intentó, y hay un
	// comentario en su propio código diciendo que devolvía 404 sobre vehículos que existen
	// de verdad, porque los había dado de alta otra cuenta de la misma sucursal.
	// ---------------------------------------------------------------------------
	// La lista  (GET /api/vehicles)
	// ---------------------------------------------------------------------------
	ListarVehiculos(ctx context.Context, sucursal pgtype.UUID) ([]ListarVehiculosRow, error)
	ListarVehiculosDePedido(ctx context.Context, arg ListarVehiculosDePedidoParams) ([]ListarVehiculosDePedidoRow, error)
	// Almacenes y facturación de Ventra — el lado de la base.
	//
	// LOS ALMACENES NO VIVEN AQUÍ. Son de Accesos y se piden por HTTP: `/api/almacenes` los
	// trae firmados y `PUT` se los devuelve tal cual. No se copian a esta base a propósito —
	// un almacén copiado se separa del de verdad en cuanto alguien mueve unas coordenadas
	// allá, y con esas coordenadas se mide el domicilio que se le cobra al cliente.
	//
	// Lo que sí es de aquí son dos cosas:
	//   1. QUÉ códigos de sucursal puede ver quien pregunta, para filtrar lo que devuelve
	//      Accesos. Esa consulta vive en `branches.sql` (`CodigosDeSucursalesVisibles`), que
	//      es donde está la tabla.
	//   2. La facturación bajada de Ventra (`ventas_facturadas`), que es el almacén de datos
	//      propiamente dicho.
	//
	// AQUÍ NO SE ESCRIBE EL COTEJO. El cotejo pedido-contra-factura lo hace PEDIDO —el pedido
	// es suyo y es allí donde se corrige cuando la factura dice otra cosa—. Aquí sólo llega el
	// resultado, por el espejo, en `orders.factura_estado`.
	// ---------------------------------------------------------------------------
	// Ventas facturadas
	// ---------------------------------------------------------------------------
	// Las líneas facturadas de una sucursal en un rango de fechas.
	//
	// EL ALCANCE VA POR CÓDIGO: `ventas_facturadas` no tiene `branch_id`, tiene
	// `sucursal_codigo`, y aquí es NOT NULL — una venta sin sucursal no existe. El llamante
	// traduce su sucursal con `branches.external_id`; NULL significa todas.
	ListarVentasFacturadas(ctx context.Context, arg ListarVentasFacturadasParams) ([]ListarVentasFacturadasRow, error)
	// La marca de agua del espejo: `since` de la próxima bajada.
	//
	// Se DERIVA de los datos y no de un contador aparte a propósito: un contador se adelanta
	// si una tanda falla a medias, y entonces el espejo se salta esos pedidos para siempre
	// sin dar un solo error.
	MarcaDeAguaDelEspejo(ctx context.Context, sucursalCodigo *string) (pgtype.Timestamptz, error)
	// Cuándo se trajo el catálogo de Ventra. Sólo se marca si se escribió ALGO: si todas las
	// sucursales fallaron, la hora no se toca, para poder reintentar antes de las doce horas
	// en vez de quedarse medio día con el catálogo a medias.
	MarcarCatalogoTraido(ctx context.Context) error
	// ---------------------------------------------------------------------------
	// Cierre de ruta  (POST /api/routes/[id]/results)
	// ---------------------------------------------------------------------------
	// Cómo acabó UNA parada. Es la consulta más delicada del reparto: de aquí sale lo que se
	// le cuenta a PEDIDO y la cuenta del post-despacho.
	//
	// Cuatro cosas van juntas a propósito y en una sola sentencia:
	//
	//  1. `WHERE ultima_ruta_id = ...` y NO `route_id`: así se puede corregir el resultado de
	//     un devuelto que ya soltó su `route_id` al cerrar. Y sirve de validación — cero filas
	//     significa «ese pedido no va en esta ruta», que es el rechazo del contrato, sin tener
	//     que comprobarlo antes en Go sobre una lectura que ya puede estar vieja.
	//  2. `route_id = NULL` SÓLO si no se entregó: el pedido baja del camión y vuelve a la
	//     lista de disponibles para la ruta de mañana. `ultima_ruta_id` y `stop_order` no se
	//     tocan NUNCA: son la hoja de lo que bajó del camión.
	//  3. `delivered_at` se limpia cuando no se entregó. Un devuelto que conserve la hora de
	//     entrega de un intento anterior se pinta «entregado» en la lista, que es exactamente
	//     la contradicción que se vio con un pedido de La Habana el 2 de septiembre.
	//  4. `resultado_nota` se guarda siempre: un devuelto sin motivo es un número que nadie
	//     sabe explicar tres semanas después.
	//
	// Ni `devuelto` ni `cancelado` tocan inventario: el reintegro lo hace Ventra.
	MarcarResultadoDeParada(ctx context.Context, arg MarcarResultadoDeParadaParams) (int64, error)
	// Mover lo de una columna a otra de golpe, para poder borrar la primera sin perder el
	// trabajo. Las tarjetas se ponen DETRÁS de lo que ya haya en la de destino, en su mismo
	// orden relativo: quien juntó dos zonas no quiere que se le mezclen las paradas.
	//
	// Las dos columnas tienen que ser de la misma sucursal. No es un capricho: `orders` guarda
	// su sucursal y una tarjeta en el tablero de otra es un pedido que dos logísticos ven a la
	// vez y ninguno sabe de quién es.
	MoverPedidosDeColumna(ctx context.Context, arg MoverPedidosDeColumnaParams) (int64, error)
	// Ajustes y monedas. GLOBALES: no llevan alcance por sucursal y no es un olvido — son de
	// toda la empresa, y no hay ninguna columna de sucursal en estas dos tablas que filtrar.
	// La tasa POR SUCURSAL es otra cosa y vive en Accesos, no aquí.
	// ---------------------------------------------------------------------------
	// Ajustes: una sola fila
	// ---------------------------------------------------------------------------
	// Los ajustes. Siempre hay fila y siempre es la misma: la clave primaria es un booleano
	// con `CHECK (id)`, así que la base impide que haya dos. En delivery esto era un
	// `findFirst` y un `create` si no había —dentro de un GET—, y dos filas de ajustes es
	// media aplicación mirando una y media mirando la otra.
	ObtenerAjustes(ctx context.Context) (Setting, error)
	// ---------------------------------------------------------------------------
	// Un cliente suelto y el espejo
	// ---------------------------------------------------------------------------
	ObtenerCliente(ctx context.Context, arg ObtenerClienteParams) (Customer, error)
	// Cero filas es «no existe O no es de tu sucursal»: desde fuera son lo mismo, y tienen que
	// serlo, porque decir «existe pero no es tuya» ya es contar algo.
	ObtenerColumna(ctx context.Context, arg ObtenerColumnaParams) (BoardColumn, error)
	// Una factura entera. `oper_number` ES la factura: varias líneas comparten número, y el
	// que las agrupa es ése y no `ventra_id`, que identifica la LÍNEA.
	ObtenerFacturaPorOperacion(ctx context.Context, arg ObtenerFacturaPorOperacionParams) ([]ObtenerFacturaPorOperacionRow, error)
	ObtenerMoneda(ctx context.Context, code string) (Currency, error)
	// ---------------------------------------------------------------------------
	// Un pedido suelto
	// ---------------------------------------------------------------------------
	ObtenerPedido(ctx context.Context, arg ObtenerPedidoParams) (ObtenerPedidoRow, error)
	ObtenerProducto(ctx context.Context, id uuid.UUID) (Product, error)
	// ---------------------------------------------------------------------------
	// Un producto suelto, ACOTADO  (GET /api/products/[id])
	// ---------------------------------------------------------------------------
	// El mismo producto que `ObtenerProducto`, pero filtrado por el código de la sucursal.
	//
	// POR QUÉ HAY DOS. `ObtenerProducto` va sin alcance a propósito: es la que usan las
	// correcciones del Super Admin, que son de toda la empresa. Ésta es la de la PANTALLA, y
	// ahí enseñar el producto de otra sucursal no es sólo un fallo de permisos: el PRECIO y
	// las EXISTENCIAS son por sucursal, así que una ficha de La Habana abierta desde Camagüey
	// lleva un precio que en Camagüey no se cobra y unas existencias que allí no hay. Eso se
	// copia en un pedido y no lo desmiente nadie hasta que llega la factura.
	//
	// NULL en `sucursal` = todas (Super Admin sin sucursal elegida).
	ObtenerProductoDelAlcance(ctx context.Context, arg ObtenerProductoDelAlcanceParams) (Product, error)
	// ---------------------------------------------------------------------------
	// El detalle de una ruta  (GET /api/routes/[id])
	// ---------------------------------------------------------------------------
	// La cabecera. Cero filas es «no existe O no es de tu sucursal»: desde fuera son lo mismo,
	// y tienen que serlo, porque decir «existe pero no es tuya» ya es contar algo.
	ObtenerRuta(ctx context.Context, arg ObtenerRutaParams) (ObtenerRutaRow, error)
	ObtenerSucursal(ctx context.Context, arg ObtenerSucursalParams) (Branch, error)
	ObtenerTipoDeVehiculo(ctx context.Context, id uuid.UUID) (VehicleType, error)
	ObtenerVehiculo(ctx context.Context, arg ObtenerVehiculoParams) (ObtenerVehiculoRow, error)
	// El camión de una ruta que se está armando, para comprobar la capacidad.
	//
	// Va SIN alcance a propósito, calcado del contrato: si el vehículo no aparece, delivery no
	// valida la capacidad en vez de negarse. Acotarlo por sucursal aquí haría que un camión
	// compartido dejara de validar peso justo cuando más importa.
	ObtenerVehiculoParaCapacidad(ctx context.Context, id uuid.UUID) (ObtenerVehiculoParaCapacidadRow, error)
	// El reparto de lo repartible por sucursal. Lo ve quien no tiene alcance —el Super Admin—;
	// a quien sí lo tiene le sale una sola fila, que es justo lo correcto.
	PanelPorSucursal(ctx context.Context, sucursal pgtype.UUID) ([]PanelPorSucursalRow, error)
	// ---------------------------------------------------------------------------
	// Panel  (GET /api/dashboard)  e informes  (GET /api/reports)
	// ---------------------------------------------------------------------------
	// Los siete números del panel en UNA consulta.
	//
	// REPARTIBLE es el mismo listón del armador de rutas —sin ruta, con coordenadas y con
	// factura que se puede llevar—: si el panel contara otra cosa, diría «40 por repartir» y
	// el armador ofrecería 12, y la respuesta correcta sería «ninguno de los dos».
	PanelResumen(ctx context.Context, arg PanelResumenParams) (PanelResumenRow, error)
	// ---------------------------------------------------------------------------
	// De una columna sale una ruta  (POST /api/board/columns/[id]/route)
	// ---------------------------------------------------------------------------
	// Los pedidos de la columna que TODAVÍA se pueden meter en una ruta, en el orden en que el
	// logístico los dejó puestos.
	//
	// Es la hermana de `PedidosParaArmarRuta` y hace el mismo trabajo, pero el universo no son
	// unos ids marcados a mano: es la columna entera. Y como allí, es LA VALIDACIÓN y no una
	// lectura previa a ella — si vuelven menos de los que hay puestos, alguien se los llevó
	// entre que se pintó el tablero y se pulsó el botón, y de ahí sale el «N de los M ya están
	// en otra ruta».
	//
	// `factura_estado` deja pasar `igual` y `cambiado` por lo mismo que en `routes.sql`: el
	// corte a sólo `igual` lo hace el handler DESPUÉS, para poder nombrar cuál falla y por qué.
	// Un WHERE que los descarte aquí deja el mismo rechazo sin nada que decir, y el logístico
	// se queda mirando una columna de doce que produce una ruta de nueve sin explicación.
	//
	// `posicion` sale para que el armador pueda RESPETAR el orden del logístico: él conoce las
	// calles de su distrito y el vecino más próximo no. Quién de los dos manda lo decide el
	// handler; lo que no puede es no tener el dato.
	PedidosDeColumnaParaArmarRuta(ctx context.Context, arg PedidosDeColumnaParaArmarRutaParams) ([]PedidosDeColumnaParaArmarRutaRow, error)
	// ---------------------------------------------------------------------------
	// Armado de ruta  (POST /api/routes)
	// ---------------------------------------------------------------------------
	// Los pedidos elegidos que TODAVÍA se pueden meter en una ruta.
	//
	// Esta consulta es la validación, no una lectura previa a ella: se pide por ids y devuelve
	// sólo los que siguen cumpliendo. Si vuelven menos de los que se pidieron, alguien se los
	// llevó entre que se pintó la lista y se pulsó el botón — con diez logísticos armando
	// rutas a la vez eso pasa de verdad — y de ahí sale el 409 con «N de los M ya están en
	// otra ruta». Comprobarlo en Go sobre una lectura anterior es mirar una foto vieja.
	//
	// `factura_estado` se deja pasar `igual` y `cambiado` porque es el mismo listón de la
	// lista de disponibles; el corte a sólo `igual` lo hace el handler DESPUÉS, para poder
	// nombrar en el error cuál falla y por qué («cambió en la factura» / «sin cotejar»).
	// Un WHERE que los descarte aquí deja el mismo 409 sin nada que decir.
	PedidosParaArmarRuta(ctx context.Context, arg PedidosParaArmarRutaParams) ([]PedidosParaArmarRutaRow, error)
	// LO QUE SE FUE DE LA SUCURSAL, para `quitados`.
	//
	// `quitados` no es sólo lo borrado, y por eso esta consulta no mira `orders`: mira las
	// lápidas de 00003_bajada_pedidos.sql. Un pedido borrado ya no tiene fila que consultar, y
	// uno que se mudó de sucursal tiene la suya intacta pero con OTRA sucursal, así que no
	// sale en ninguna consulta acotada a la vieja. En los dos casos el aparato se quedaría con
	// él para siempre: la lista local sólo crece.
	//
	// EL ARCHIVADO NO ESTÁ AQUÍ y no se le olvidó a nadie: su fila sigue existiendo, con el
	// `updated_at` movido, así que sale por `DiferenciasDePedidos` y quien contesta la bajada
	// lo manda a `quitados` al ver `archivado`. Ponerlo también aquí sería mandarlo dos veces.
	//
	// Y SIN SUCURSAL —el Super Admin, que ve las ocho— sólo cuentan los BORRADOS: un pedido
	// que se mudó de Santiago a Holguín no se le ha ido de la vista, y mandárselo en
	// `quitados` le borraría del aparato un pedido que existe y que está en su lista.
	PedidosQueSalieronDelAlcance(ctx context.Context, arg PedidosQueSalieronDelAlcanceParams) ([]PedidosQueSalieronDelAlcanceRow, error)
	// El peso que le TOCA a cada pedido según el catálogo, junto al que tiene guardado.
	//
	// POR QUÉ SE SUMA EN LA BASE Y NO EN GO: el repaso es sobre el espejo ENTERO —decenas de
	// miles de pedidos y sus renglones—, y traérselo todo para multiplicar y sumar es cargar
	// el espejo en la memoria del proceso para devolver dos números por fila.
	//
	// El peso sale de `products.weight`, que es el mismo dato con el que PEDIDO cotiza. El
	// `pesoLineaKg` que venía dentro del JSON de `items` YA NO EXISTE: era una copia, y una
	// copia acaba discrepando del catálogo que la originó.
	//
	// El LEFT JOIN a `order_items` es a propósito: un pedido SIN renglones tiene que salir
	// igual, con peso calculado 0. Si se cayera de la lista, `totalOrders` diría menos
	// pedidos de los que hay y nadie sabría cuáles faltan.
	PesosDelCatalogoPorFuente(ctx context.Context, source Procedencia) ([]PesosDelCatalogoPorFuenteRow, error)
	// Las tarjetas de los pedidos que acaban de subirse a una ruta salen del tablero.
	//
	// Se llama DENTRO de la misma transacción que engancha las paradas. La columna se vacía
	// porque el pedido ya no está por preparar: está cargado. Dejarlo puesto sería enseñar dos
	// veces el mismo trabajo —una en el tablero y otra en la ruta— y la segunda vez que alguien
	// «prepara» esa columna se encuentra con que ya salió.
	//
	// No se borra la COLUMNA: el distrito sigue existiendo mañana. Lo que se vacía es lo que
	// lleva dentro hoy.
	QuitarDelTableroLosDeRuta(ctx context.Context, arg QuitarDelTableroLosDeRutaParams) (int64, error)
	// Sacar una tarjeta del tablero: vuelve a «sin colocar», donde la lista la pondrá otra vez
	// en su sitio por cercanía. Devuelve la columna y la posición que tenía para poder cerrar
	// el hueco sin volver a preguntar.
	QuitarPedidoDelTablero(ctx context.Context, arg QuitarPedidoDelTableroParams) (QuitarPedidoDelTableroRow, error)
	// Los renglones que el catálogo NO sabe pesar, contados por nombre. Es la lista que hay
	// que llevarle a quien mantiene el catálogo de Ventra: sin ella, `ordersSinPeso` dice que
	// hay un problema pero no dice de qué producto.
	//
	// `(sin nombre)` literal para el renglón con la descripción en blanco: agruparlos bajo la
	// cadena vacía deja una fila sin etiqueta en la pantalla que nadie sabe leer.
	RenglonesSinPesoPorFuente(ctx context.Context, source Procedencia) ([]RenglonesSinPesoPorFuenteRow, error)
	// Reordenar el tablero entero de una vez: llega la lista de ids en el orden nuevo y la
	// posición de cada uno es su sitio en esa lista.
	//
	// En UNA sola sentencia, no una por columna. Con una por columna, el aparato que se queda
	// sin señal a la mitad deja el tablero con dos «tercera» y ninguna «quinta»; aquí, o entran
	// todas o no entra ninguna. Es también la razón de que la única de `posicion` sea
	// DEFERRABLE: a mitad de este `UPDATE` hay posiciones repetidas, y la comprobación tiene
	// que esperar a que el baile termine.
	//
	// Las que no vengan en la lista no se tocan: `array_position` sólo se evalúa sobre las que
	// casan el `WHERE`.
	ReordenarColumnas(ctx context.Context, arg ReordenarColumnasParams) (int64, error)
	// ¿Existe esta sucursal? Es la comprobación de `resolveScope`, y el único sitio donde se
	// resuelve el alcance. Devuelve también el `external_id` porque clientes y catálogo se
	// acotan por CÓDIGO, no por uuid, y sin esa traducción el filtro no se puede armar.
	ResolverSucursal(ctx context.Context, id uuid.UUID) (ResolverSucursalRow, error)
	// Lo cotejado de una sucursal, para comparar contra la de Next mientras las dos están en
	// pie. Los NULL se cuentan aparte de los `sin_factura`: no son lo mismo y confundirlos es
	// exactamente lo que hay que poder ver.
	ResumenDeCotejo(ctx context.Context, arg ResumenDeCotejoParams) (ResumenDeCotejoRow, error)
	// ---------------------------------------------------------------------------
	// Pre-despacho: qué mercancía hay que sacar del almacén
	// ---------------------------------------------------------------------------
	// La cuenta de lo que hay que preparar, agrupada por nombre de renglón.
	//
	// `formatos` son los bultos y son la unidad con la que se carga y se cuenta un camión;
	// cuando el renglón no los trae se cae a las unidades, porque es lo que hay y cero sería
	// mentira. El peso sale ahora del catálogo (`products.weight`), que es el mismo dato con
	// el que PEDIDO cotiza: el `pesoLineaKg` que venía dentro del JSON de `items` ya no existe.
	ResumenPreDespacho(ctx context.Context, arg ResumenPreDespachoParams) ([]ResumenPreDespachoRow, error)
	// Retirar un tipo NO es borrarlo. Se desactiva: deja de ofrecerse en el desplegable y los
	// camiones que ya lo tienen siguen funcionando. Un DELETE choca contra la clave ajena de
	// `vehicles.vehicle_type_id`, y hacerlo a la fuerza dejaría camiones sin tipo, que es un
	// camión sin costo por km y por tanto sin fórmula del domicilio.
	RetirarTipoDeVehiculo(ctx context.Context, id uuid.UUID) (int64, error)
	// La ruta viva más reciente de un camión, para la tarjeta de la flota.
	RutaActivaDeVehiculo(ctx context.Context, arg RutaActivaDeVehiculoParams) (RutaActivaDeVehiculoRow, error)
	// ---------------------------------------------------------------------------
	// Borrar una ruta  (DELETE /api/routes/[id])
	// ---------------------------------------------------------------------------
	// Los pedidos NO se borran: se sueltan y vuelven a la lista de disponibles.
	// `ultima_ruta_id` se conserva — el pasado de un pedido no se reescribe porque alguien
	// deshaga la ruta de hoy.
	SoltarPedidosDeRuta(ctx context.Context, arg SoltarPedidosDeRutaParams) (int64, error)
	// Hasta cuándo se tiene facturación de una sucursal.
	//
	// Es lo que distingue «este pedido no está facturado» de «de ese día todavía no hemos
	// bajado nada». Las dos cosas dejan `factura_estado` en NULL y desde fuera son idénticas;
	// la diferencia es que la primera es un problema del pedido y la segunda es que la VPN a
	// Ventra lleva caída desde el lunes. Con esa confusión se armó una ruta con un pedido sin
	// facturar el 2 de septiembre.
	UltimaFacturacionDeSucursal(ctx context.Context, sucursalCodigo string) (UltimaFacturacionDeSucursalRow, error)
	// Cuánto se ha pedido de cada producto últimamente, para ordenar el buscador por lo que la
	// gente usa de verdad y no por orden alfabético.
	//
	// Se cuenta sobre los últimos N pedidos DEL ALCANCE, no sobre todo el histórico: lo que se
	// movía hace ocho meses no dice nada de lo que hay que tener a mano hoy. El tope lo pone
	// el llamante para que la cuenta no crezca sola con la base.
	UsoDeProductos(ctx context.Context, arg UsoDeProductosParams) ([]UsoDeProductosRow, error)
	// Vaciar la columna: las tarjetas vuelven a «sin colocar», que es de donde salieron.
	// No se borra ningún pedido — el tablero nunca borra pedidos, sólo dice dónde están.
	VaciarColumna(ctx context.Context, arg VaciarColumnaParams) (int64, error)
	// El de referencia de una sucursal: con su capacidad y su costo por km define el CKK de la
	// fórmula del domicilio. Si el vehículo no trae costo propio se cae al del tipo.
	VehiculoDeReferenciaDeSucursal(ctx context.Context, sucursal pgtype.UUID) (VehiculoDeReferenciaDeSucursalRow, error)
}

var _ Querier = (*Queries)(nil)
