// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"
)

const actualizarAjustes = `-- name: ActualizarAjustes :one
UPDATE settings SET
    currency = coalesce($1::text, currency),
    cup_rate = coalesce($2::double precision, cup_rate),
    cup_rate_updated_at = CASE
        WHEN $2::double precision IS NOT NULL
         AND $2::double precision <> cup_rate THEN now()
        ELSE cup_rate_updated_at
    END
WHERE id
RETURNING id, sync_barrido_dia, catalogo_traido_at, currency,
          cup_rate, cup_rate_updated_at, created_at, updated_at
`

type ActualizarAjustesParams struct {
	Currency *string  `json:"currency"`
	CupRate  *float64 `json:"cup_rate"`
}

// `cup_rate_updated_at` se mueve SÓLO cuando cambia la tasa, no en cada guardado: es lo
// que dice si el número que se está usando es de hoy o de hace tres semanas, y tocarlo por
// guardar la moneda lo convertiría en una copia de `updated_at`, que ya existe.
func (q *Queries) ActualizarAjustes(ctx context.Context, arg ActualizarAjustesParams) (Setting, error) {
	row := q.db.QueryRow(ctx, actualizarAjustes, arg.Currency, arg.CupRate)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.SyncBarridoDia,
		&i.CatalogoTraidoAt,
		&i.Currency,
		&i.CupRate,
		&i.CupRateUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const desactivarMoneda = `-- name: DesactivarMoneda :execrows
UPDATE currencies SET activa = false WHERE code = $1
`

// Retirar una moneda es desactivarla, no borrarla: los importes ya guardados se
// convirtieron con su tasa y sin la fila no hay forma de volver a explicarlos.
func (q *Queries) DesactivarMoneda(ctx context.Context, code string) (int64, error) {
	result, err := q.db.Exec(ctx, desactivarMoneda, code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fijarBarridoDelEspejo = `-- name: FijarBarridoDelEspejo :exec
UPDATE settings SET sync_barrido_dia = $1 WHERE id
`

// Por dónde va el barrido del histórico, en DÍAS HACIA ATRÁS.
//
// Hace falta guardarlo porque de los datos NO se puede deducir: hay pedidos viejos
// sueltos, así que «el más antiguo que tengo» no significa «tengo todo hasta ahí».
func (q *Queries) FijarBarridoDelEspejo(ctx context.Context, syncBarridoDia int32) error {
	_, err := q.db.Exec(ctx, fijarBarridoDelEspejo, syncBarridoDia)
	return err
}

const guardarMoneda = `-- name: GuardarMoneda :one
INSERT INTO currencies (code, rate, activa)
VALUES ($1, $2, $3)
ON CONFLICT (code) DO UPDATE SET
    rate   = excluded.rate,
    activa = excluded.activa
RETURNING code, rate, activa, created_at, updated_at
`

type GuardarMonedaParams struct {
	Code   string  `json:"code"`
	Rate   float64 `json:"rate"`
	Activa bool    `json:"activa"`
}

// Una moneda se corrige sola, sin reescribir la lista entera. Eso es lo que la tabla
// compra frente al array de JSON que había antes: se puede saber cuándo cambió cada tasa
// —`updated_at`, que lo mantiene el trigger— y corregir una sin tocar las demás.
func (q *Queries) GuardarMoneda(ctx context.Context, arg GuardarMonedaParams) (Currency, error) {
	row := q.db.QueryRow(ctx, guardarMoneda, arg.Code, arg.Rate, arg.Activa)
	var i Currency
	err := row.Scan(
		&i.Code,
		&i.Rate,
		&i.Activa,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listarMonedas = `-- name: ListarMonedas :many

SELECT c.code, c.rate, c.activa, c.created_at, c.updated_at
FROM currencies c
WHERE ($1::boolean IS NULL
       OR NOT $1::boolean
       OR c.activa)
ORDER BY c.code ASC
`

// ---------------------------------------------------------------------------
// Monedas
// ---------------------------------------------------------------------------
// `rate` son unidades de esta moneda por 1 USD: CUP = 320, no al revés. Escrito al revés,
// todos los importes salen divididos por cien mil y parecen céntimos.
func (q *Queries) ListarMonedas(ctx context.Context, soloActivas *bool) ([]Currency, error) {
	rows, err := q.db.Query(ctx, listarMonedas, soloActivas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Currency
	for rows.Next() {
		var i Currency
		if err := rows.Scan(
			&i.Code,
			&i.Rate,
			&i.Activa,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marcarCatalogoTraido = `-- name: MarcarCatalogoTraido :exec
UPDATE settings SET catalogo_traido_at = now() WHERE id
`

// Cuándo se trajo el catálogo de Ventra. Sólo se marca si se escribió ALGO: si todas las
// sucursales fallaron, la hora no se toca, para poder reintentar antes de las doce horas
// en vez de quedarse medio día con el catálogo a medias.
func (q *Queries) MarcarCatalogoTraido(ctx context.Context) error {
	_, err := q.db.Exec(ctx, marcarCatalogoTraido)
	return err
}

const obtenerAjustes = `-- name: ObtenerAjustes :one


SELECT
    s.id, s.sync_barrido_dia, s.catalogo_traido_at, s.currency,
    s.cup_rate, s.cup_rate_updated_at, s.created_at, s.updated_at
FROM settings s
WHERE s.id
`

// Ajustes y monedas. GLOBALES: no llevan alcance por sucursal y no es un olvido — son de
// toda la empresa, y no hay ninguna columna de sucursal en estas dos tablas que filtrar.
// La tasa POR SUCURSAL es otra cosa y vive en Accesos, no aquí.
// ---------------------------------------------------------------------------
// Ajustes: una sola fila
// ---------------------------------------------------------------------------
// Los ajustes. Siempre hay fila y siempre es la misma: la clave primaria es un booleano
// con `CHECK (id)`, así que la base impide que haya dos. En delivery esto era un
// `findFirst` y un `create` si no había —dentro de un GET—, y dos filas de ajustes es
// media aplicación mirando una y media mirando la otra.
func (q *Queries) ObtenerAjustes(ctx context.Context) (Setting, error) {
	row := q.db.QueryRow(ctx, obtenerAjustes)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.SyncBarridoDia,
		&i.CatalogoTraidoAt,
		&i.Currency,
		&i.CupRate,
		&i.CupRateUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const obtenerMoneda = `-- name: ObtenerMoneda :one
SELECT c.code, c.rate, c.activa, c.created_at, c.updated_at
FROM currencies c
WHERE c.code = $1
`

func (q *Queries) ObtenerMoneda(ctx context.Context, code string) (Currency, error) {
	row := q.db.QueryRow(ctx, obtenerMoneda, code)
	var i Currency
	err := row.Scan(
		&i.Code,
		&i.Rate,
		&i.Activa,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
