// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vehicles.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const actualizarVehiculo = `-- name: ActualizarVehiculo :one
UPDATE vehicles SET
    name                = coalesce($1::text, name),
    vehicle_type_id     = coalesce($2::uuid, vehicle_type_id),
    plate               = CASE WHEN $3::boolean
                               THEN $4::text ELSE plate END,
    capacity            = coalesce($5::double precision, capacity),
    costo_km_usd        = CASE WHEN $6::boolean
                               THEN $7::double precision
                               ELSE costo_km_usd END,
    usar_para_domicilio = coalesce($8::boolean, usar_para_domicilio),
    status              = coalesce($9::vehicle_status, status),
    notes               = CASE WHEN $10::boolean
                               THEN $11::text ELSE notes END
WHERE id = $12
  AND ($13::uuid IS NULL
       OR branch_id = $13::uuid
       OR branch_id IS NULL)
RETURNING id, name, vehicle_type_id, plate, capacity, costo_km_usd,
          usar_para_domicilio, status, notes, branch_id, created_at, updated_at
`

type ActualizarVehiculoParams struct {
	Name              *string        `json:"name"`
	VehicleTypeID     pgtype.UUID    `json:"vehicle_type_id"`
	TocarPlate        bool           `json:"tocar_plate"`
	Plate             *string        `json:"plate"`
	Capacity          *float64       `json:"capacity"`
	TocarCosto        bool           `json:"tocar_costo"`
	CostoKmUsd        *float64       `json:"costo_km_usd"`
	UsarParaDomicilio *bool          `json:"usar_para_domicilio"`
	Status            *VehicleStatus `json:"status"`
	TocarNotes        bool           `json:"tocar_notes"`
	Notes             *string        `json:"notes"`
	ID                uuid.UUID      `json:"id"`
	Sucursal          pgtype.UUID    `json:"sucursal"`
}

func (q *Queries) ActualizarVehiculo(ctx context.Context, arg ActualizarVehiculoParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, actualizarVehiculo,
		arg.Name,
		arg.VehicleTypeID,
		arg.TocarPlate,
		arg.Plate,
		arg.Capacity,
		arg.TocarCosto,
		arg.CostoKmUsd,
		arg.UsarParaDomicilio,
		arg.Status,
		arg.TocarNotes,
		arg.Notes,
		arg.ID,
		arg.Sucursal,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VehicleTypeID,
		&i.Plate,
		&i.Capacity,
		&i.CostoKmUsd,
		&i.UsarParaDomicilio,
		&i.Status,
		&i.Notes,
		&i.BranchID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const asignarVehiculoAPedido = `-- name: AsignarVehiculoAPedido :one

INSERT INTO order_vehicles (order_id, vehicle_id, is_primary)
SELECT o.id, $1, $2
FROM orders o
WHERE o.id = $3
  AND ($4::uuid IS NULL OR o.branch_id = $4::uuid)
ON CONFLICT (order_id, vehicle_id) DO UPDATE SET is_primary = excluded.is_primary
RETURNING id, order_id, vehicle_id, is_primary
`

type AsignarVehiculoAPedidoParams struct {
	VehicleID uuid.UUID   `json:"vehicle_id"`
	IsPrimary bool        `json:"is_primary"`
	OrderID   uuid.UUID   `json:"order_id"`
	Sucursal  pgtype.UUID `json:"sucursal"`
}

type AsignarVehiculoAPedidoRow struct {
	ID        uuid.UUID `json:"id"`
	OrderID   uuid.UUID `json:"order_id"`
	VehicleID uuid.UUID `json:"vehicle_id"`
	IsPrimary bool      `json:"is_primary"`
}

// ---------------------------------------------------------------------------
// Asignación de varios camiones a un pedido
// ---------------------------------------------------------------------------
// El INSERT va con SELECT y no con VALUES para poder acotar por sucursal: `order_vehicles`
// no tiene `branch_id`, así que la única forma de comprobar el alcance es preguntarle al
// pedido. Con VALUES, el id del pedido entra tal cual desde el cliente y un camión de
// Holguín acaba colgado de un pedido de La Habana. Cero filas es el 404.
func (q *Queries) AsignarVehiculoAPedido(ctx context.Context, arg AsignarVehiculoAPedidoParams) (AsignarVehiculoAPedidoRow, error) {
	row := q.db.QueryRow(ctx, asignarVehiculoAPedido,
		arg.VehicleID,
		arg.IsPrimary,
		arg.OrderID,
		arg.Sucursal,
	)
	var i AsignarVehiculoAPedidoRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.VehicleID,
		&i.IsPrimary,
	)
	return i, err
}

const borrarAsignacionesDeVehiculo = `-- name: BorrarAsignacionesDeVehiculo :execrows
DELETE FROM order_vehicles WHERE vehicle_id = $1
`

func (q *Queries) BorrarAsignacionesDeVehiculo(ctx context.Context, vehiculoID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, borrarAsignacionesDeVehiculo, vehiculoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const borrarVehiculo = `-- name: BorrarVehiculo :execrows
DELETE FROM vehicles
WHERE id = $1
  AND ($2::uuid IS NULL
       OR branch_id = $2::uuid
       OR branch_id IS NULL)
`

type BorrarVehiculoParams struct {
	ID       uuid.UUID   `json:"id"`
	Sucursal pgtype.UUID `json:"sucursal"`
}

func (q *Queries) BorrarVehiculo(ctx context.Context, arg BorrarVehiculoParams) (int64, error) {
	result, err := q.db.Exec(ctx, borrarVehiculo, arg.ID, arg.Sucursal)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cambiarEstadoDeVehiculo = `-- name: CambiarEstadoDeVehiculo :execrows
UPDATE vehicles SET status = $1::vehicle_status
WHERE id = $2
  AND ($3::uuid IS NULL
       OR branch_id = $3::uuid
       OR branch_id IS NULL)
`

type CambiarEstadoDeVehiculoParams struct {
	Status   VehicleStatus `json:"status"`
	ID       uuid.UUID     `json:"id"`
	Sucursal pgtype.UUID   `json:"sucursal"`
}

// Ocupar y liberar el camión. El vehículo se marca `in_use` al DESPACHAR la ruta (pasarla
// a `in_progress`), no al armarla: entre que se arma la noche anterior y sale por la
// mañana, el camión sigue disponible para otra cosa.
func (q *Queries) CambiarEstadoDeVehiculo(ctx context.Context, arg CambiarEstadoDeVehiculoParams) (int64, error) {
	result, err := q.db.Exec(ctx, cambiarEstadoDeVehiculo, arg.Status, arg.ID, arg.Sucursal)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const contarVehiculos = `-- name: ContarVehiculos :one

SELECT count(*) FROM vehicles v
WHERE ($1::uuid IS NULL
       OR v.branch_id = $1::uuid
       OR v.branch_id IS NULL)
`

// ---------------------------------------------------------------------------
// Panel
// ---------------------------------------------------------------------------
func (q *Queries) ContarVehiculos(ctx context.Context, sucursal pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, contarVehiculos, sucursal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const contarVehiculosEnRuta = `-- name: ContarVehiculosEnRuta :one
SELECT count(DISTINCT r.vehicle_id) FROM routes r
WHERE r.vehicle_id IS NOT NULL
  AND r.status NOT IN ('completed', 'cancelled')
  AND ($1::uuid IS NULL OR r.branch_id = $1::uuid)
`

// Camiones que están fuera ahora mismo: los que llevan una ruta sin cerrar. Se mira la
// ruta y no `vehicles.status` porque el estado es un campo que alguien puede haber dejado
// a mano en `available` con la ruta todavía abierta.
func (q *Queries) ContarVehiculosEnRuta(ctx context.Context, sucursal pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, contarVehiculosEnRuta, sucursal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const crearVehiculo = `-- name: CrearVehiculo :one

INSERT INTO vehicles (
    name, vehicle_type_id, plate, capacity, costo_km_usd,
    usar_para_domicilio, status, notes, branch_id
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9
)
RETURNING id, name, vehicle_type_id, plate, capacity, costo_km_usd,
          usar_para_domicilio, status, notes, branch_id, created_at, updated_at
`

type CrearVehiculoParams struct {
	Name              string        `json:"name"`
	VehicleTypeID     uuid.UUID     `json:"vehicle_type_id"`
	Plate             *string       `json:"plate"`
	Capacity          float64       `json:"capacity"`
	CostoKmUsd        *float64      `json:"costo_km_usd"`
	UsarParaDomicilio bool          `json:"usar_para_domicilio"`
	Status            VehicleStatus `json:"status"`
	Notes             *string       `json:"notes"`
	BranchID          pgtype.UUID   `json:"branch_id"`
}

// ---------------------------------------------------------------------------
// Altas y cambios
// ---------------------------------------------------------------------------
// El vehículo nace en la sucursal del alcance. Quien no tiene alcance —el Super Admin—
// puede dejarlo sin sucursal, que significa «de todas».
//
// `costo_km_usd` puede quedar vacío: lo pone el camionero, y dos camiones del mismo tipo
// no cuestan igual. Vacío quiere decir «usa el del tipo», no «cero».
func (q *Queries) CrearVehiculo(ctx context.Context, arg CrearVehiculoParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, crearVehiculo,
		arg.Name,
		arg.VehicleTypeID,
		arg.Plate,
		arg.Capacity,
		arg.CostoKmUsd,
		arg.UsarParaDomicilio,
		arg.Status,
		arg.Notes,
		arg.BranchID,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VehicleTypeID,
		&i.Plate,
		&i.Capacity,
		&i.CostoKmUsd,
		&i.UsarParaDomicilio,
		&i.Status,
		&i.Notes,
		&i.BranchID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const desmarcarReferenciaDeDomicilio = `-- name: DesmarcarReferenciaDeDomicilio :execrows
UPDATE vehicles SET usar_para_domicilio = false
WHERE usar_para_domicilio
  AND id <> $1
  AND branch_id IS NOT DISTINCT FROM $2::uuid
`

type DesmarcarReferenciaDeDomicilioParams struct {
	ExceptoID uuid.UUID   `json:"excepto_id"`
	Sucursal  pgtype.UUID `json:"sucursal"`
}

// Sólo un vehículo de referencia por sucursal, y lo impide el índice único parcial
// `vehicles_una_referencia_por_sucursal`. Por eso hay que DESMARCAR a los demás antes de
// marcar el nuevo, y las dos cosas dentro de la MISMA transacción: si no, el INSERT choca
// contra el índice.
//
// HUECO CONOCIDO: los vehículos sin sucursal (`branch_id` NULL) se escapan del índice,
// porque en un índice único los NULL son distintos entre sí. Puede haber dos de referencia
// «de todas». Se cierra con `NULLS NOT DISTINCT` el día que estorbe.
func (q *Queries) DesmarcarReferenciaDeDomicilio(ctx context.Context, arg DesmarcarReferenciaDeDomicilioParams) (int64, error) {
	result, err := q.db.Exec(ctx, desmarcarReferenciaDeDomicilio, arg.ExceptoID, arg.Sucursal)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const desvincularVehiculoDePedidos = `-- name: DesvincularVehiculoDePedidos :execrows

UPDATE orders SET vehicle_id = NULL
WHERE vehicle_id = $1
  AND ($2::uuid IS NULL OR branch_id = $2::uuid)
`

type DesvincularVehiculoDePedidosParams struct {
	VehiculoID pgtype.UUID `json:"vehiculo_id"`
	Sucursal   pgtype.UUID `json:"sucursal"`
}

// ---------------------------------------------------------------------------
// Borrado
// ---------------------------------------------------------------------------
//
// Antes de borrar hay que desasociar: rutas (`DesvincularVehiculoDeRutas`, en routes.sql),
// pedidos y asignaciones. El histórico de lo que se repartió no se borra porque un camión
// se dé de baja.
func (q *Queries) DesvincularVehiculoDePedidos(ctx context.Context, arg DesvincularVehiculoDePedidosParams) (int64, error) {
	result, err := q.db.Exec(ctx, desvincularVehiculoDePedidos, arg.VehiculoID, arg.Sucursal)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listarVehiculos = `-- name: ListarVehiculos :many


SELECT
    v.id, v.name, v.vehicle_type_id, v.plate, v.capacity, v.costo_km_usd,
    v.usar_para_domicilio, v.status, v.notes, v.branch_id,
    v.created_at, v.updated_at,
    vt.nombre       AS tipo_nombre,
    vt.costo_km_usd AS tipo_costo_km_usd,
    b.name          AS sucursal_nombre,
    -- Los tres conteos de la tarjeta. Van como subconsultas y no como JOIN + GROUP BY
    -- porque tres JOIN a la vez multiplican las filas entre sí y los tres números salen
    -- inflados: el clásico de contar rutas y pedidos en la misma consulta.
    (SELECT count(*) FROM routes r         WHERE r.vehicle_id  = v.id) AS rutas,
    -- LOS PEDIDOS QUE LLEVA ESTE CAMIÓN SALEN DE SUS RUTAS, no de ` + "`" + `orders.vehicle_id` + "`" + `.
    --
    -- Aquí se contaba ` + "`" + `orders.vehicle_id` + "`" + `, y esa columna la escribe SÓLO el tablero
    -- (` + "`" + `tablero.sql` + "`" + `, ` + "`" + `tocar_vehiculo` + "`" + `): armar una ruta nunca la toca, porque el camión de
    -- un pedido es el de la ruta en la que viaja. Resultado, visto el 22/09/2026 en el
    -- teléfono de Jose: la tarjeta decía «Rutas 7» y debajo «0 órdenes asignadas», con
    -- 125,3 kg cargados. Dos números de la misma tarjeta contándose cosas distintas, y el
    -- cero es el que se lee.
    (SELECT count(*) FROM orders o
        JOIN routes r ON r.id = o.route_id
        WHERE r.vehicle_id = v.id) AS pedidos,
    (SELECT count(*) FROM order_vehicles ov WHERE ov.vehicle_id = v.id) AS asignaciones
FROM vehicles v
JOIN vehicle_types vt ON vt.id = v.vehicle_type_id
LEFT JOIN branches b  ON b.id  = v.branch_id
WHERE ($1::uuid IS NULL
       OR v.branch_id = $1::uuid
       OR v.branch_id IS NULL)
ORDER BY v.created_at DESC
`

type ListarVehiculosRow struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	VehicleTypeID     uuid.UUID          `json:"vehicle_type_id"`
	Plate             *string            `json:"plate"`
	Capacity          float64            `json:"capacity"`
	CostoKmUsd        *float64           `json:"costo_km_usd"`
	UsarParaDomicilio bool               `json:"usar_para_domicilio"`
	Status            VehicleStatus      `json:"status"`
	Notes             *string            `json:"notes"`
	BranchID          pgtype.UUID        `json:"branch_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	TipoNombre        string             `json:"tipo_nombre"`
	TipoCostoKmUsd    *float64           `json:"tipo_costo_km_usd"`
	SucursalNombre    *string            `json:"sucursal_nombre"`
	Rutas             int64              `json:"rutas"`
	Pedidos           int64              `json:"pedidos"`
	Asignaciones      int64              `json:"asignaciones"`
}

// La flota.
//
// `branch_id` NULL en un vehículo significa «de todas las sucursales», así que el filtro
// del alcance tiene que dejarlos pasar: un camión compartido que no salga en la lista de
// nadie es un camión que no se puede usar. Eso es distinto de pedidos y rutas, donde un
// `branch_id` NULL sería un dato incompleto, no una decisión.
//
// NO SE FILTRA POR QUIÉN DIO DE ALTA EL VEHÍCULO. En delivery se intentó, y hay un
// comentario en su propio código diciendo que devolvía 404 sobre vehículos que existen
// de verdad, porque los había dado de alta otra cuenta de la misma sucursal.
// ---------------------------------------------------------------------------
// La lista  (GET /api/vehicles)
// ---------------------------------------------------------------------------
func (q *Queries) ListarVehiculos(ctx context.Context, sucursal pgtype.UUID) ([]ListarVehiculosRow, error) {
	rows, err := q.db.Query(ctx, listarVehiculos, sucursal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarVehiculosRow
	for rows.Next() {
		var i ListarVehiculosRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.VehicleTypeID,
			&i.Plate,
			&i.Capacity,
			&i.CostoKmUsd,
			&i.UsarParaDomicilio,
			&i.Status,
			&i.Notes,
			&i.BranchID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TipoNombre,
			&i.TipoCostoKmUsd,
			&i.SucursalNombre,
			&i.Rutas,
			&i.Pedidos,
			&i.Asignaciones,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarVehiculosDePedido = `-- name: ListarVehiculosDePedido :many
SELECT ov.id, ov.vehicle_id, ov.is_primary, v.name, v.plate, v.capacity
FROM order_vehicles ov
JOIN vehicles v ON v.id = ov.vehicle_id
JOIN orders   o ON o.id = ov.order_id
WHERE ov.order_id = $1
  AND ($2::uuid IS NULL OR o.branch_id = $2::uuid)
ORDER BY ov.is_primary DESC, v.name ASC
`

type ListarVehiculosDePedidoParams struct {
	PedidoID uuid.UUID   `json:"pedido_id"`
	Sucursal pgtype.UUID `json:"sucursal"`
}

type ListarVehiculosDePedidoRow struct {
	ID        uuid.UUID `json:"id"`
	VehicleID uuid.UUID `json:"vehicle_id"`
	IsPrimary bool      `json:"is_primary"`
	Name      string    `json:"name"`
	Plate     *string   `json:"plate"`
	Capacity  float64   `json:"capacity"`
}

func (q *Queries) ListarVehiculosDePedido(ctx context.Context, arg ListarVehiculosDePedidoParams) ([]ListarVehiculosDePedidoRow, error) {
	rows, err := q.db.Query(ctx, listarVehiculosDePedido, arg.PedidoID, arg.Sucursal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarVehiculosDePedidoRow
	for rows.Next() {
		var i ListarVehiculosDePedidoRow
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.IsPrimary,
			&i.Name,
			&i.Plate,
			&i.Capacity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerVehiculo = `-- name: ObtenerVehiculo :one
SELECT
    v.id, v.name, v.vehicle_type_id, v.plate, v.capacity, v.costo_km_usd,
    v.usar_para_domicilio, v.status, v.notes, v.branch_id,
    v.created_at, v.updated_at,
    vt.nombre       AS tipo_nombre,
    vt.costo_km_usd AS tipo_costo_km_usd,
    (SELECT count(*) FROM routes r          WHERE r.vehicle_id  = v.id) AS rutas,
    -- Igual que en ` + "`" + `ListarVehiculos` + "`" + `: por sus rutas. Ver el comentario de allí.
    (SELECT count(*) FROM orders o
        JOIN routes r ON r.id = o.route_id
        WHERE r.vehicle_id = v.id) AS pedidos,
    (SELECT count(*) FROM order_vehicles ov WHERE ov.vehicle_id = v.id) AS asignaciones
FROM vehicles v
JOIN vehicle_types vt ON vt.id = v.vehicle_type_id
WHERE v.id = $1
  AND ($2::uuid IS NULL
       OR v.branch_id = $2::uuid
       OR v.branch_id IS NULL)
`

type ObtenerVehiculoParams struct {
	ID       uuid.UUID   `json:"id"`
	Sucursal pgtype.UUID `json:"sucursal"`
}

type ObtenerVehiculoRow struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	VehicleTypeID     uuid.UUID          `json:"vehicle_type_id"`
	Plate             *string            `json:"plate"`
	Capacity          float64            `json:"capacity"`
	CostoKmUsd        *float64           `json:"costo_km_usd"`
	UsarParaDomicilio bool               `json:"usar_para_domicilio"`
	Status            VehicleStatus      `json:"status"`
	Notes             *string            `json:"notes"`
	BranchID          pgtype.UUID        `json:"branch_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	TipoNombre        string             `json:"tipo_nombre"`
	TipoCostoKmUsd    *float64           `json:"tipo_costo_km_usd"`
	Rutas             int64              `json:"rutas"`
	Pedidos           int64              `json:"pedidos"`
	Asignaciones      int64              `json:"asignaciones"`
}

func (q *Queries) ObtenerVehiculo(ctx context.Context, arg ObtenerVehiculoParams) (ObtenerVehiculoRow, error) {
	row := q.db.QueryRow(ctx, obtenerVehiculo, arg.ID, arg.Sucursal)
	var i ObtenerVehiculoRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VehicleTypeID,
		&i.Plate,
		&i.Capacity,
		&i.CostoKmUsd,
		&i.UsarParaDomicilio,
		&i.Status,
		&i.Notes,
		&i.BranchID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TipoNombre,
		&i.TipoCostoKmUsd,
		&i.Rutas,
		&i.Pedidos,
		&i.Asignaciones,
	)
	return i, err
}

const obtenerVehiculoParaCapacidad = `-- name: ObtenerVehiculoParaCapacidad :one
SELECT v.id, v.name, v.capacity, v.status, v.branch_id
FROM vehicles v
WHERE v.id = $1
`

type ObtenerVehiculoParaCapacidadRow struct {
	ID       uuid.UUID     `json:"id"`
	Name     string        `json:"name"`
	Capacity float64       `json:"capacity"`
	Status   VehicleStatus `json:"status"`
	BranchID pgtype.UUID   `json:"branch_id"`
}

// El camión de una ruta que se está armando, para comprobar la capacidad.
//
// Va SIN alcance a propósito, calcado del contrato: si el vehículo no aparece, delivery no
// valida la capacidad en vez de negarse. Acotarlo por sucursal aquí haría que un camión
// compartido dejara de validar peso justo cuando más importa.
func (q *Queries) ObtenerVehiculoParaCapacidad(ctx context.Context, id uuid.UUID) (ObtenerVehiculoParaCapacidadRow, error) {
	row := q.db.QueryRow(ctx, obtenerVehiculoParaCapacidad, id)
	var i ObtenerVehiculoParaCapacidadRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Capacity,
		&i.Status,
		&i.BranchID,
	)
	return i, err
}

const vehiculoDeReferenciaDeSucursal = `-- name: VehiculoDeReferenciaDeSucursal :one
SELECT
    v.id, v.name, v.capacity,
    coalesce(v.costo_km_usd, vt.costo_km_usd) AS costo_km_usd,
    v.branch_id
FROM vehicles v
JOIN vehicle_types vt ON vt.id = v.vehicle_type_id
WHERE v.usar_para_domicilio
  AND v.branch_id IS NOT DISTINCT FROM $1::uuid
`

type VehiculoDeReferenciaDeSucursalRow struct {
	ID         uuid.UUID   `json:"id"`
	Name       string      `json:"name"`
	Capacity   float64     `json:"capacity"`
	CostoKmUsd *float64    `json:"costo_km_usd"`
	BranchID   pgtype.UUID `json:"branch_id"`
}

// El de referencia de una sucursal: con su capacidad y su costo por km define el CKK de la
// fórmula del domicilio. Si el vehículo no trae costo propio se cae al del tipo.
func (q *Queries) VehiculoDeReferenciaDeSucursal(ctx context.Context, sucursal pgtype.UUID) (VehiculoDeReferenciaDeSucursalRow, error) {
	row := q.db.QueryRow(ctx, vehiculoDeReferenciaDeSucursal, sucursal)
	var i VehiculoDeReferenciaDeSucursalRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Capacity,
		&i.CostoKmUsd,
		&i.BranchID,
	)
	return i, err
}
