// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: warehouses.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const almacenesDelPedidoSinMedir = `-- name: AlmacenesDelPedidoSinMedir :many

SELECT sucursal_codigo, motivo, codigo, nombre, pedidos AS cuantos, desde, hasta
FROM almacenes_del_pedido_sin_medir
WHERE $1::text[] IS NULL
   OR sucursal_codigo = ANY($1::text[])
ORDER BY pedidos DESC, sucursal_codigo ASC, motivo ASC
LIMIT $2
`

type AlmacenesDelPedidoSinMedirParams struct {
	Sucursales []string `json:"sucursales"`
	Tope       int32    `json:"tope"`
}

type AlmacenesDelPedidoSinMedirRow struct {
	SucursalCodigo *string            `json:"sucursal_codigo"`
	Motivo         *string            `json:"motivo"`
	Codigo         *string            `json:"codigo"`
	Nombre         *string            `json:"nombre"`
	Cuantos        int64              `json:"cuantos"`
	Desde          pgtype.Timestamptz `json:"desde"`
	Hasta          pgtype.Timestamptz `json:"hasta"`
}

// ---------------------------------------------------------------------------
// Los pedidos que NO se midieron desde su propio almacén
// ---------------------------------------------------------------------------
// QUÉ ALMACENES ESTÁN HACIENDO QUE SE MIDA DESDE OTRO SITIO, Y POR QUÉ.
//
// Es la mitad visible de la regla «nada se descarta en silencio» (`CLAUDE.md` §4). Un pedido
// cuyo almacén no se pudo usar no se tira y no se cambia por el principal a escondidas: se
// guarda su código y su nombre tal cual, se mide desde donde se pudo, y sale AQUÍ con el
// motivo para que alguien lo arregle.
//
// LOS MOTIVOS SE ARREGLAN EN SITIOS DISTINTOS y por eso viajan separados: dar de alta el
// almacén en Accesos, ponerle el punto, ponerle el código, o que PEDIDO empiece a mandar el
// campo. Y el peor —`sucursal-sin-almacen-con-punto`— no se midió desde ningún almacén, sino
// desde el punto de la sucursal.
//
// SE ACOTA POR CÓDIGO DE SUCURSAL: `sucursales` NULL es «todas» —el caso de administración—
// y con una lista sólo salen ésas. Sin esto, unir esta vista a una respuesta de la API le
// enseñaría Santiago al logístico de Camagüey, que es la regla 1 de la casa y ya pasó una vez
// en delivery.
//
// `pedidos AS cuantos` no es un capricho: cuando el SELECT es exactamente las columnas de la
// vista y en su orden, sqlc reutiliza el modelo de la vista y lo llama
// `AlmacenesDelPedidoSinMedirum`. Con un alias emite un `...Row` que se puede leer.
func (q *Queries) AlmacenesDelPedidoSinMedir(ctx context.Context, arg AlmacenesDelPedidoSinMedirParams) ([]AlmacenesDelPedidoSinMedirRow, error) {
	rows, err := q.db.Query(ctx, almacenesDelPedidoSinMedir, arg.Sucursales, arg.Tope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlmacenesDelPedidoSinMedirRow
	for rows.Next() {
		var i AlmacenesDelPedidoSinMedirRow
		if err := rows.Scan(
			&i.SucursalCodigo,
			&i.Motivo,
			&i.Codigo,
			&i.Nombre,
			&i.Cuantos,
			&i.Desde,
			&i.Hasta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const diasConFacturacion = `-- name: DiasConFacturacion :many
SELECT
    date_trunc('day', vf.fecha)::timestamptz AS dia,
    count(*)                                 AS lineas,
    max(vf.traido_at)::timestamptz           AS traido_at
FROM ventas_facturadas vf
WHERE ($1::text IS NULL
       OR vf.sucursal_codigo = $1::text)
  AND ($2::timestamptz IS NULL OR vf.fecha >= $2::timestamptz)
GROUP BY date_trunc('day', vf.fecha)
ORDER BY dia DESC
`

type DiasConFacturacionParams struct {
	SucursalCodigo *string            `json:"sucursal_codigo"`
	Desde          pgtype.Timestamptz `json:"desde"`
}

type DiasConFacturacionRow struct {
	Dia      pgtype.Timestamptz `json:"dia"`
	Lineas   int64              `json:"lineas"`
	TraidoAt pgtype.Timestamptz `json:"traido_at"`
}

// Cuántas líneas hay por día, para ver de un vistazo qué días están bajados y cuáles no.
// Un día que falta no sale como cero: sale como que no está, y eso es lo correcto — un
// cero inventado se lee como «ese día no se vendió nada».
func (q *Queries) DiasConFacturacion(ctx context.Context, arg DiasConFacturacionParams) ([]DiasConFacturacionRow, error) {
	rows, err := q.db.Query(ctx, diasConFacturacion, arg.SucursalCodigo, arg.Desde)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiasConFacturacionRow
	for rows.Next() {
		var i DiasConFacturacionRow
		if err := rows.Scan(&i.Dia, &i.Lineas, &i.TraidoAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const guardarVentaFacturada = `-- name: GuardarVentaFacturada :one
INSERT INTO ventas_facturadas (
    ventra_id, sucursal_codigo, fecha, oper_number, cliente_codigo,
    cliente_nombre, producto_codigo, producto_nombre, cantidad, precio_usd, traido_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, now()
)
ON CONFLICT (ventra_id) DO UPDATE SET
    sucursal_codigo = excluded.sucursal_codigo,
    fecha           = excluded.fecha,
    oper_number     = excluded.oper_number,
    cliente_codigo  = excluded.cliente_codigo,
    cliente_nombre  = excluded.cliente_nombre,
    producto_codigo = excluded.producto_codigo,
    producto_nombre = excluded.producto_nombre,
    cantidad        = excluded.cantidad,
    precio_usd      = excluded.precio_usd,
    traido_at       = excluded.traido_at
RETURNING id, ventra_id, sucursal_codigo, oper_number, traido_at
`

type GuardarVentaFacturadaParams struct {
	VentraID       string             `json:"ventra_id"`
	SucursalCodigo string             `json:"sucursal_codigo"`
	Fecha          pgtype.Timestamptz `json:"fecha"`
	OperNumber     string             `json:"oper_number"`
	ClienteCodigo  *string            `json:"cliente_codigo"`
	ClienteNombre  string             `json:"cliente_nombre"`
	ProductoCodigo *string            `json:"producto_codigo"`
	ProductoNombre string             `json:"producto_nombre"`
	Cantidad       float64            `json:"cantidad"`
	PrecioUsd      *float64           `json:"precio_usd"`
}

type GuardarVentaFacturadaRow struct {
	ID             uuid.UUID          `json:"id"`
	VentraID       string             `json:"ventra_id"`
	SucursalCodigo string             `json:"sucursal_codigo"`
	OperNumber     string             `json:"oper_number"`
	TraidoAt       pgtype.Timestamptz `json:"traido_at"`
}

// Alta o actualización por `ventra_id`, que es el id de la LÍNEA en Ventra y por el que se
// reconoce entre pasadas. Aquí sí hay `ON CONFLICT`: el esquema lo declara UNIQUE.
//
// Va sin alcance: la bajada entra con clave de servicio y recorre las ocho sucursales.
func (q *Queries) GuardarVentaFacturada(ctx context.Context, arg GuardarVentaFacturadaParams) (GuardarVentaFacturadaRow, error) {
	row := q.db.QueryRow(ctx, guardarVentaFacturada,
		arg.VentraID,
		arg.SucursalCodigo,
		arg.Fecha,
		arg.OperNumber,
		arg.ClienteCodigo,
		arg.ClienteNombre,
		arg.ProductoCodigo,
		arg.ProductoNombre,
		arg.Cantidad,
		arg.PrecioUsd,
	)
	var i GuardarVentaFacturadaRow
	err := row.Scan(
		&i.ID,
		&i.VentraID,
		&i.SucursalCodigo,
		&i.OperNumber,
		&i.TraidoAt,
	)
	return i, err
}

const listarVentasFacturadas = `-- name: ListarVentasFacturadas :many


SELECT
    vf.id, vf.ventra_id, vf.sucursal_codigo, vf.fecha, vf.oper_number,
    vf.cliente_codigo, vf.cliente_nombre, vf.producto_codigo,
    vf.producto_nombre, vf.cantidad, vf.precio_usd, vf.traido_at
FROM ventas_facturadas vf
WHERE
    ($1::text IS NULL
     OR vf.sucursal_codigo = $1::text)
    AND ($2::timestamptz IS NULL OR vf.fecha >= $2::timestamptz)
    AND ($3::timestamptz IS NULL OR vf.fecha <= $3::timestamptz)
    AND ($4::text IS NULL OR vf.oper_number = $4::text)
    AND (
        $5::text IS NULL
        OR vf.cliente_nombre  ILIKE '%' || $5::text || '%'
        OR vf.producto_nombre ILIKE '%' || $5::text || '%'
    )
ORDER BY vf.fecha DESC, vf.oper_number ASC
`

type ListarVentasFacturadasParams struct {
	SucursalCodigo *string            `json:"sucursal_codigo"`
	Desde          pgtype.Timestamptz `json:"desde"`
	Hasta          pgtype.Timestamptz `json:"hasta"`
	OperNumber     *string            `json:"oper_number"`
	Q              *string            `json:"q"`
}

type ListarVentasFacturadasRow struct {
	ID             uuid.UUID          `json:"id"`
	VentraID       string             `json:"ventra_id"`
	SucursalCodigo string             `json:"sucursal_codigo"`
	Fecha          pgtype.Timestamptz `json:"fecha"`
	OperNumber     string             `json:"oper_number"`
	ClienteCodigo  *string            `json:"cliente_codigo"`
	ClienteNombre  string             `json:"cliente_nombre"`
	ProductoCodigo *string            `json:"producto_codigo"`
	ProductoNombre string             `json:"producto_nombre"`
	Cantidad       float64            `json:"cantidad"`
	PrecioUsd      *float64           `json:"precio_usd"`
	TraidoAt       pgtype.Timestamptz `json:"traido_at"`
}

// Almacenes y facturación de Ventra — el lado de la base.
//
// LOS ALMACENES NO VIVEN AQUÍ. Son de Accesos y se piden por HTTP: `/api/almacenes` los
// trae firmados y `PUT` se los devuelve tal cual. No se copian a esta base a propósito —
// un almacén copiado se separa del de verdad en cuanto alguien mueve unas coordenadas
// allá, y con esas coordenadas se mide el domicilio que se le cobra al cliente.
//
// Lo que sí es de aquí son dos cosas:
//  1. QUÉ códigos de sucursal puede ver quien pregunta, para filtrar lo que devuelve
//     Accesos. Esa consulta vive en `branches.sql` (`CodigosDeSucursalesVisibles`), que
//     es donde está la tabla.
//  2. La facturación bajada de Ventra (`ventas_facturadas`), que es el almacén de datos
//     propiamente dicho.
//
// AQUÍ NO SE ESCRIBE EL COTEJO. El cotejo pedido-contra-factura lo hace PEDIDO —el pedido
// es suyo y es allí donde se corrige cuando la factura dice otra cosa—. Aquí sólo llega el
// resultado, por el espejo, en `orders.factura_estado`.
// ---------------------------------------------------------------------------
// Ventas facturadas
// ---------------------------------------------------------------------------
// Las líneas facturadas de una sucursal en un rango de fechas.
//
// EL ALCANCE VA POR CÓDIGO: `ventas_facturadas` no tiene `branch_id`, tiene
// `sucursal_codigo`, y aquí es NOT NULL — una venta sin sucursal no existe. El llamante
// traduce su sucursal con `branches.external_id`; NULL significa todas.
func (q *Queries) ListarVentasFacturadas(ctx context.Context, arg ListarVentasFacturadasParams) ([]ListarVentasFacturadasRow, error) {
	rows, err := q.db.Query(ctx, listarVentasFacturadas,
		arg.SucursalCodigo,
		arg.Desde,
		arg.Hasta,
		arg.OperNumber,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarVentasFacturadasRow
	for rows.Next() {
		var i ListarVentasFacturadasRow
		if err := rows.Scan(
			&i.ID,
			&i.VentraID,
			&i.SucursalCodigo,
			&i.Fecha,
			&i.OperNumber,
			&i.ClienteCodigo,
			&i.ClienteNombre,
			&i.ProductoCodigo,
			&i.ProductoNombre,
			&i.Cantidad,
			&i.PrecioUsd,
			&i.TraidoAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerFacturaPorOperacion = `-- name: ObtenerFacturaPorOperacion :many
SELECT
    vf.id, vf.ventra_id, vf.sucursal_codigo, vf.fecha, vf.oper_number,
    vf.cliente_codigo, vf.cliente_nombre, vf.producto_codigo,
    vf.producto_nombre, vf.cantidad, vf.precio_usd, vf.traido_at
FROM ventas_facturadas vf
WHERE vf.oper_number = $1
  AND vf.sucursal_codigo = $2
ORDER BY vf.producto_nombre ASC
`

type ObtenerFacturaPorOperacionParams struct {
	OperNumber     string `json:"oper_number"`
	SucursalCodigo string `json:"sucursal_codigo"`
}

type ObtenerFacturaPorOperacionRow struct {
	ID             uuid.UUID          `json:"id"`
	VentraID       string             `json:"ventra_id"`
	SucursalCodigo string             `json:"sucursal_codigo"`
	Fecha          pgtype.Timestamptz `json:"fecha"`
	OperNumber     string             `json:"oper_number"`
	ClienteCodigo  *string            `json:"cliente_codigo"`
	ClienteNombre  string             `json:"cliente_nombre"`
	ProductoCodigo *string            `json:"producto_codigo"`
	ProductoNombre string             `json:"producto_nombre"`
	Cantidad       float64            `json:"cantidad"`
	PrecioUsd      *float64           `json:"precio_usd"`
	TraidoAt       pgtype.Timestamptz `json:"traido_at"`
}

// Una factura entera. `oper_number` ES la factura: varias líneas comparten número, y el
// que las agrupa es ése y no `ventra_id`, que identifica la LÍNEA.
func (q *Queries) ObtenerFacturaPorOperacion(ctx context.Context, arg ObtenerFacturaPorOperacionParams) ([]ObtenerFacturaPorOperacionRow, error) {
	rows, err := q.db.Query(ctx, obtenerFacturaPorOperacion, arg.OperNumber, arg.SucursalCodigo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ObtenerFacturaPorOperacionRow
	for rows.Next() {
		var i ObtenerFacturaPorOperacionRow
		if err := rows.Scan(
			&i.ID,
			&i.VentraID,
			&i.SucursalCodigo,
			&i.Fecha,
			&i.OperNumber,
			&i.ClienteCodigo,
			&i.ClienteNombre,
			&i.ProductoCodigo,
			&i.ProductoNombre,
			&i.Cantidad,
			&i.PrecioUsd,
			&i.TraidoAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resumenDeCotejo = `-- name: ResumenDeCotejo :one
SELECT
    count(*)                                                    AS total,
    count(*) FILTER (WHERE o.factura_estado = 'igual')          AS cuadran,
    count(*) FILTER (WHERE o.factura_estado = 'cambiado')       AS cambiados,
    count(*) FILTER (WHERE o.factura_estado = 'sin_factura')    AS sin_factura,
    count(*) FILTER (WHERE o.factura_estado IS NULL)            AS sin_cotejar
FROM orders o
WHERE ($1::uuid IS NULL OR o.branch_id = $1::uuid)
  AND ($2::timestamptz IS NULL
       OR coalesce(o.order_date, o.created_at) >= $2::timestamptz)
`

type ResumenDeCotejoParams struct {
	Sucursal pgtype.UUID        `json:"sucursal"`
	Desde    pgtype.Timestamptz `json:"desde"`
}

type ResumenDeCotejoRow struct {
	Total      int64 `json:"total"`
	Cuadran    int64 `json:"cuadran"`
	Cambiados  int64 `json:"cambiados"`
	SinFactura int64 `json:"sin_factura"`
	SinCotejar int64 `json:"sin_cotejar"`
}

// Lo cotejado de una sucursal, para comparar contra la de Next mientras las dos están en
// pie. Los NULL se cuentan aparte de los `sin_factura`: no son lo mismo y confundirlos es
// exactamente lo que hay que poder ver.
func (q *Queries) ResumenDeCotejo(ctx context.Context, arg ResumenDeCotejoParams) (ResumenDeCotejoRow, error) {
	row := q.db.QueryRow(ctx, resumenDeCotejo, arg.Sucursal, arg.Desde)
	var i ResumenDeCotejoRow
	err := row.Scan(
		&i.Total,
		&i.Cuadran,
		&i.Cambiados,
		&i.SinFactura,
		&i.SinCotejar,
	)
	return i, err
}

const ultimaFacturacionDeSucursal = `-- name: UltimaFacturacionDeSucursal :one
SELECT
    max(vf.fecha)::timestamptz     AS hasta_fecha,
    max(vf.traido_at)::timestamptz AS traido_at,
    count(*)                       AS lineas
FROM ventas_facturadas vf
WHERE vf.sucursal_codigo = $1
`

type UltimaFacturacionDeSucursalRow struct {
	HastaFecha pgtype.Timestamptz `json:"hasta_fecha"`
	TraidoAt   pgtype.Timestamptz `json:"traido_at"`
	Lineas     int64              `json:"lineas"`
}

// Hasta cuándo se tiene facturación de una sucursal.
//
// Es lo que distingue «este pedido no está facturado» de «de ese día todavía no hemos
// bajado nada». Las dos cosas dejan `factura_estado` en NULL y desde fuera son idénticas;
// la diferencia es que la primera es un problema del pedido y la segunda es que la VPN a
// Ventra lleva caída desde el lunes. Con esa confusión se armó una ruta con un pedido sin
// facturar el 2 de septiembre.
func (q *Queries) UltimaFacturacionDeSucursal(ctx context.Context, sucursalCodigo string) (UltimaFacturacionDeSucursalRow, error) {
	row := q.db.QueryRow(ctx, ultimaFacturacionDeSucursal, sucursalCodigo)
	var i UltimaFacturacionDeSucursalRow
	err := row.Scan(&i.HastaFecha, &i.TraidoAt, &i.Lineas)
	return i, err
}
