// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const apuntarEnvioDelWebhook = `-- name: ApuntarEnvioDelWebhook :exec

INSERT INTO envios_del_webhook (destino, mandados, aceptados, rechazados, http, motivo, duracion_ms)
VALUES (
    $1, $2, $3,
    $4, $5, $6, $7
)
`

type ApuntarEnvioDelWebhookParams struct {
	Destino    string  `json:"destino"`
	Mandados   int32   `json:"mandados"`
	Aceptados  int32   `json:"aceptados"`
	Rechazados int32   `json:"rechazados"`
	Http       *int32  `json:"http"`
	Motivo     *string `json:"motivo"`
	DuracionMs int32   `json:"duracion_ms"`
}

// ---------------------------------------------------------------------------
// Lo que sale
// ---------------------------------------------------------------------------
func (q *Queries) ApuntarEnvioDelWebhook(ctx context.Context, arg ApuntarEnvioDelWebhookParams) error {
	_, err := q.db.Exec(ctx, apuntarEnvioDelWebhook,
		arg.Destino,
		arg.Mandados,
		arg.Aceptados,
		arg.Rechazados,
		arg.Http,
		arg.Motivo,
		arg.DuracionMs,
	)
	return err
}

const apuntarRecepcionDelWebhook = `-- name: ApuntarRecepcionDelWebhook :exec


INSERT INTO recepciones_del_webhook (origen, traidos, escritos, rechazados, motivos, duracion_ms)
VALUES (
    $1, $2, $3,
    $4, $5, $6
)
`

type ApuntarRecepcionDelWebhookParams struct {
	Origen     string  `json:"origen"`
	Traidos    int32   `json:"traidos"`
	Escritos   int32   `json:"escritos"`
	Rechazados int32   `json:"rechazados"`
	Motivos    *string `json:"motivos"`
	DuracionMs int32   `json:"duracion_ms"`
}

// EL WEBHOOK, EN LOS DOS SENTIDOS, Y CÓMO VA.
//
// `avisos_a_pedido` (00010) dice qué pasó con CADA aviso. Estas dos tablas dicen qué pasó
// con cada TANDA: si la llamada llegó, qué contestó el otro lado y cuánto tardó. Son
// preguntas distintas y las dos hacen falta — un aviso sin enviar puede ser «PEDIDO está
// caído» o «PEDIDO lo rechazó», y desde fuera se ven igual.
// ---------------------------------------------------------------------------
// Lo que entra
// ---------------------------------------------------------------------------
func (q *Queries) ApuntarRecepcionDelWebhook(ctx context.Context, arg ApuntarRecepcionDelWebhookParams) error {
	_, err := q.db.Exec(ctx, apuntarRecepcionDelWebhook,
		arg.Origen,
		arg.Traidos,
		arg.Escritos,
		arg.Rechazados,
		arg.Motivos,
		arg.DuracionMs,
	)
	return err
}

const listarEnviosDelWebhook = `-- name: ListarEnviosDelWebhook :many
SELECT id, destino, mandados, aceptados, rechazados, http, motivo, duracion_ms, created_at
FROM envios_del_webhook
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListarEnviosDelWebhook(ctx context.Context, tope int32) ([]EnviosDelWebhook, error) {
	rows, err := q.db.Query(ctx, listarEnviosDelWebhook, tope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnviosDelWebhook
	for rows.Next() {
		var i EnviosDelWebhook
		if err := rows.Scan(
			&i.ID,
			&i.Destino,
			&i.Mandados,
			&i.Aceptados,
			&i.Rechazados,
			&i.Http,
			&i.Motivo,
			&i.DuracionMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarRecepcionesDelWebhook = `-- name: ListarRecepcionesDelWebhook :many
SELECT id, origen, traidos, escritos, rechazados, motivos, duracion_ms, created_at
FROM recepciones_del_webhook
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListarRecepcionesDelWebhook(ctx context.Context, tope int32) ([]RecepcionesDelWebhook, error) {
	rows, err := q.db.Query(ctx, listarRecepcionesDelWebhook, tope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecepcionesDelWebhook
	for rows.Next() {
		var i RecepcionesDelWebhook
		if err := rows.Scan(
			&i.ID,
			&i.Origen,
			&i.Traidos,
			&i.Escritos,
			&i.Rechazados,
			&i.Motivos,
			&i.DuracionMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resumenDelWebhook = `-- name: ResumenDelWebhook :one

SELECT
    (SELECT max(created_at) FROM recepciones_del_webhook)::timestamptz AS ultima_entrada,
    (SELECT max(created_at) FROM envios_del_webhook)::timestamptz      AS ultima_salida,
    (SELECT coalesce(sum(escritos), 0)::bigint
       FROM recepciones_del_webhook
      WHERE created_at > now() - interval '24 hours')              AS escritos_hoy,
    (SELECT coalesce(sum(rechazados), 0)::bigint
       FROM recepciones_del_webhook
      WHERE created_at > now() - interval '24 hours')              AS rechazados_al_entrar,
    (SELECT count(*)::bigint FROM avisos_a_pedido
      WHERE situacion = 'pendiente')                               AS avisos_pendientes,
    (SELECT count(*)::bigint FROM avisos_a_pedido
      WHERE situacion = 'rechazado')                               AS avisos_rechazados,
    -- El más viejo sin mandar. Es el número que dice si esto está atascado: veinte
    -- pendientes de hace un minuto es el ritmo normal; uno de hace seis horas, no.
    (SELECT min(created_at) FROM avisos_a_pedido
      WHERE situacion = 'pendiente')::timestamptz                  AS pendiente_mas_viejo
`

type ResumenDelWebhookRow struct {
	UltimaEntrada      pgtype.Timestamptz `json:"ultima_entrada"`
	UltimaSalida       pgtype.Timestamptz `json:"ultima_salida"`
	EscritosHoy        int64              `json:"escritos_hoy"`
	RechazadosAlEntrar int64              `json:"rechazados_al_entrar"`
	AvisosPendientes   int64              `json:"avisos_pendientes"`
	AvisosRechazados   int64              `json:"avisos_rechazados"`
	PendienteMasViejo  pgtype.Timestamptz `json:"pendiente_mas_viejo"`
}

// ---------------------------------------------------------------------------
// Cómo va, en una lectura
// ---------------------------------------------------------------------------
//
// Las horas de la última tanda de cada lado son lo primero que se mira: un webhook que
// lleva seis horas sin recibir nada no da ningún error, sólo deja de pasar cosas. Y
// `null` es «nunca», que no es lo mismo que «hace mucho» y se dice con otras palabras.
func (q *Queries) ResumenDelWebhook(ctx context.Context) (ResumenDelWebhookRow, error) {
	row := q.db.QueryRow(ctx, resumenDelWebhook)
	var i ResumenDelWebhookRow
	err := row.Scan(
		&i.UltimaEntrada,
		&i.UltimaSalida,
		&i.EscritosHoy,
		&i.RechazadosAlEntrar,
		&i.AvisosPendientes,
		&i.AvisosRechazados,
		&i.PendienteMasViejo,
	)
	return i, err
}
