// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApunteEstado string

const (
	ApunteEstadoAplicado  ApunteEstado = "aplicado"
	ApunteEstadoRechazado ApunteEstado = "rechazado"
)

func (e *ApunteEstado) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApunteEstado(s)
	case string:
		*e = ApunteEstado(s)
	default:
		return fmt.Errorf("unsupported scan type for ApunteEstado: %T", src)
	}
	return nil
}

type NullApunteEstado struct {
	ApunteEstado ApunteEstado `json:"apunte_estado"`
	Valid        bool         `json:"valid"` // Valid is true if ApunteEstado is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApunteEstado) Scan(value interface{}) error {
	if value == nil {
		ns.ApunteEstado, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApunteEstado.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApunteEstado) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApunteEstado), nil
}

type Aparato struct {
	ID        uuid.UUID          `json:"id"`
	Persona   string             `json:"persona"`
	BranchID  uuid.UUID          `json:"branch_id"`
	Nombre    *string            `json:"nombre"`
	VistoAt   pgtype.Timestamptz `json:"visto_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AparatoEstado struct {
	AparatoID   uuid.UUID          `json:"aparato_id"`
	BajadaAt    pgtype.Timestamptz `json:"bajada_at"`
	BajadaHasta pgtype.Timestamptz `json:"bajada_hasta"`
	SubidaAt    pgtype.Timestamptz `json:"subida_at"`
	Pendientes  int32              `json:"pendientes"`
	Rechazados  int32              `json:"rechazados"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Apunte struct {
	AparatoID uuid.UUID          `json:"aparato_id"`
	Clave     string             `json:"clave"`
	Metodo    string             `json:"metodo"`
	Ruta      string             `json:"ruta"`
	Estado    ApunteEstado       `json:"estado"`
	IDCreado  pgtype.UUID        `json:"id_creado"`
	HechoAt   pgtype.Timestamptz `json:"hecho_at"`
	ExpiraAt  pgtype.Timestamptz `json:"expira_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ApuntesRechazado struct {
	ID          uuid.UUID          `json:"id"`
	AparatoID   uuid.UUID          `json:"aparato_id"`
	Clave       string             `json:"clave"`
	Motivo      string             `json:"motivo"`
	RechazadoAt pgtype.Timestamptz `json:"rechazado_at"`
	Cuerpo      *string            `json:"cuerpo"`
	AtendidoAt  pgtype.Timestamptz `json:"atendido_at"`
	AtendidoPor *string            `json:"atendido_por"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type IdsProvisionale struct {
	AparatoID   uuid.UUID          `json:"aparato_id"`
	Provisional string             `json:"provisional"`
	IDReal      uuid.UUID          `json:"id_real"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
