// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ===========================================================================
	// 2 · Estado de sincronización
	// ===========================================================================
	// La fila de estado se abre en el alta, vacía. Así el panel enseña al aparato recién dado
	// de alta como «nunca ha subido» en vez de no enseñarlo: un aparato que no aparece es un
	// aparato del que nadie se acuerda.
	//
	// Va sin RETURNING y como `:exec` a propósito: con `DO NOTHING` la fila que ya existía no
	// se devuelve, así que un `:one` daría «no hay filas» justo en el caso normal de volver a
	// abrirla. Para leerla está `EstadoDeAparato`.
	AbrirEstado(ctx context.Context, aparatoID uuid.UUID) error
	// Las consultas del sincronizador, para sqlc.
	//
	// Están escritas a partir de las preguntas que se hacen de verdad, no de las tablas:
	//
	//   «¿qué sucursal lleva sin reportar?»      → PanelDeEstado, AparatosSinSubir
	//   «¿he visto ya esta clave?»               → BuscarApunte
	//   «¿qué le queda a este aparato?»          → EstadoDeAparato, AparatosConPendientes
	//   «¿qué se le rechazó y por qué?»          → RechazosSinAtender, RechazosDeAparato
	//   «¿de qué ruta hablaba este local-…?»     → ResolverProvisional
	//
	// Los índices del esquema son los de estas consultas y de ninguna más.
	//
	// CONVENCIÓN DE PARÁMETROS, la misma que en `api/db/queries`:
	//
	//   El alcance por sucursal es SEGURIDAD y va SIEMPRE en el SQL, nunca en Go. Se expresa
	//   con un solo parámetro que admite «todas las sucursales» como NULL — el Super Admin:
	//
	//       (sqlc.narg('sucursal')::uuid IS NULL OR a.branch_id = sqlc.narg('sucursal')::uuid)
	//
	//   Aquí importa el doble, porque el panel es justo lo que enseña quién no ha subido: sin
	//   esa línea, el logístico de Camagüey vería la cola y los rechazos de las otras nueve
	//   sucursales. El `::uuid` explícito es lo que obliga a sqlc a generarlo como anulable.
	// ===========================================================================
	// 1 · Registro de aparatos
	// ===========================================================================
	// El alta de una instalación: `POST /sync/aparato`. El uuid lo pone la base y es lo que el
	// aparato guarda; nunca se lo inventa él.
	AltaAparato(ctx context.Context, arg AltaAparatoParams) (Aparato, error)
	// Se anota DESPUÉS de aplicarlo y en la misma transacción que el cambio en el reparto. Al
	// revés —anotar y luego aplicar— un corte en medio dejaría la clave marcada como hecha con
	// el trabajo sin hacer, y el reintento contestaría `repetido` sobre algo que no existe.
	AnotarApunteAplicado(ctx context.Context, arg AnotarApunteAplicadoParams) (Apunte, error)
	// El rechazo también se anota: `rechazado` no se reintenta, así que si el aparato vuelve a
	// mandarlo hay que contestarle lo mismo y no volver a evaluarlo.
	AnotarApunteRechazado(ctx context.Context, arg AnotarApunteRechazadoParams) (Apunte, error)
	// Tras servir `GET /sync/bajada`. `bajada_hasta` es el `hasta` que se le devolvió — lo
	// pone el servidor, nunca el aparato.
	AnotarBajada(ctx context.Context, arg AnotarBajadaParams) error
	// ===========================================================================
	// 5 · Identificadores provisionales
	// ===========================================================================
	// Se anota al aplicar el apunte que creó la cosa, junto con el id que se devuelve.
	//
	// Si ese `local-…` ya está traducido, LA TRADUCCIÓN BUENA ES LA PRIMERA. Sobrescribirla
	// con un id nuevo dejaría huérfano al de verdad —la ruta ya creada— y es justamente cómo
	// se duplica una ruta armada sin conexión.
	//
	// Por eso el `DO UPDATE` se asigna el valor que ya tenía: no cambia nada, pero devuelve la
	// fila que manda. Con `DO NOTHING` no volvería ninguna y quien llama no sabría con qué id
	// contestarle al aparato, que es lo único que necesita.
	AnotarProvisional(ctx context.Context, arg AnotarProvisionalParams) (IdsProvisionale, error)
	// ===========================================================================
	// 4 · Los rechazados
	// ===========================================================================
	// Se escribe en la misma transacción que `AnotarApunteRechazado`: el apunte y su motivo
	// entran juntos o no entra ninguno. Un apunte marcado rechazado sin motivo en la bandeja
	// es exactamente el descarte en silencio que esto viene a impedir.
	AnotarRechazo(ctx context.Context, arg AnotarRechazoParams) (ApuntesRechazado, error)
	// Tras procesar un lote de `POST /sync/subida`. Los `pendientes` los dice el aparato (la
	// cola vive en el teléfono); los rechazos del lote se SUMAN al contador, no lo sustituyen.
	AnotarSubida(ctx context.Context, arg AnotarSubidaParams) error
	AparatoPorId(ctx context.Context, id uuid.UUID) (Aparato, error)
	// Los que tienen trabajo sin subir ahora mismo, el que más primero.
	AparatosConPendientes(ctx context.Context, sucursal pgtype.UUID) ([]AparatosConPendientesRow, error)
	// Los aparatos de una sucursal. Con el alcance cerrado por sucursal, es lo que puede ver
	// quien no es Super Admin.
	AparatosDeSucursal(ctx context.Context, branchID uuid.UUID) ([]Aparato, error)
	// «¿Qué aparatos llevan más de N horas sin subir?» — la llamada de teléfono.
	//
	// `IS NULL OR` y no sólo la comparación: un aparato que NUNCA subió no cumple ninguna
	// comparación de fechas y se quedaría fuera de la lista justo el que más falta hace ver.
	AparatosSinSubir(ctx context.Context, arg AparatosSinSubirParams) ([]AparatosSinSubirRow, error)
	// Una persona lo dio por visto. No se borra nunca: queda con quién lo atendió y cuándo.
	// Si no devuelve fila es que ya estaba atendido —otro llegó antes—, no que no exista.
	AtenderRechazo(ctx context.Context, arg AtenderRechazoParams) (ApuntesRechazado, error)
	// ===========================================================================
	// 3 · Idempotencia
	// ===========================================================================
	// «¿He visto ya esta clave?» Se pregunta una vez por cada apunte del lote, antes de
	// aplicarlo, y es la consulta más repetida de todo el servicio: va por la primaria.
	//
	// Trae el motivo con LEFT JOIN porque para contestar `repetido` hay que devolver la MISMA
	// respuesta de la primera vez, y si aquella fue un rechazo, la respuesta incluye su motivo.
	BuscarApunte(ctx context.Context, arg BuscarApunteParams) (BuscarApunteRow, error)
	// «¿Qué le queda a este aparato?», de un tirón.
	EstadoDeAparato(ctx context.Context, id uuid.UUID) (EstadoDeAparatoRow, error)
	// EL PANEL: `GET /sync/estado`. Todo lo que hay que ver de todos los aparatos, con el que
	// peor está arriba.
	//
	// El orden es el de la urgencia, no el alfabético: primero el que nunca subió (NULLS
	// FIRST), luego el que lleva más tiempo sin hacerlo. Ordenar por sucursal dejaría a Palma
	// enterrada entre nueve filas verdes.
	PanelDeEstado(ctx context.Context, sucursal pgtype.UUID) ([]PanelDeEstadoRow, error)
	// Los del aparato, para poder mandarle el mapeo entero si perdió el suyo.
	ProvisionalesDeAparato(ctx context.Context, aparatoID uuid.UUID) ([]IdsProvisionale, error)
	// La barrida de caducados, para que la tabla no crezca para siempre. Sólo los APLICADOS:
	// los rechazados se quedan hasta que una persona decida, y además su fila hace falta para
	// la clave ajena de la bandeja.
	PurgarApuntes(ctx context.Context) (int64, error)
	// Todo lo que se le rechazó a un aparato, atendido o no.
	RechazosDeAparato(ctx context.Context, aparatoID uuid.UUID) ([]RechazosDeAparatoRow, error)
	// LA BANDEJA: lo que está esperando a que una persona decida, lo más reciente arriba.
	// Con la sucursal y el aparato, porque el motivo solo no dice a quién hay que llamar.
	RechazosSinAtender(ctx context.Context, sucursal pgtype.UUID) ([]RechazosSinAtenderRow, error)
	// Cuántos quedan sin atender por sucursal. Es el número rojo de la cabecera del panel.
	RechazosSinAtenderPorSucursal(ctx context.Context, sucursal pgtype.UUID) ([]RechazosSinAtenderPorSucursalRow, error)
	// «¿De qué era este local-…?» Se pregunta cuando llega un apunte que todavía trae el
	// provisional en la ruta: el aparato se cortó antes de sustituirlo en el resto de su cola.
	// Traducirlo aquí es lo que evita el 404 sobre el trabajo de toda la tarde.
	ResolverProvisional(ctx context.Context, arg ResolverProvisionalParams) (uuid.UUID, error)
	// La señal de vida. Se llama en CADA petición del aparato, baje o suba: es lo que
	// distingue «el teléfono está apagado en un cajón» de «el teléfono trabaja pero no sube».
	TocarAparato(ctx context.Context, id uuid.UUID) error
	// Lo último que mandó un aparato, para mirar un caso concreto cuando algo no cuadra.
	UltimosApuntesDeAparato(ctx context.Context, arg UltimosApuntesDeAparatoParams) ([]Apunte, error)
}

var _ Querier = (*Queries)(nil)
